### ISSUE TITLE
Create card... Component so can be used anywhere.

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#118]
<img width="301" alt="Screenshot 2023-05-08 at 5 38 03 PM" src="https://user-images.githubusercontent.com/88332977/236820058-7416d94c-9a52-40d9-bf49-5b0a4b15473c.png">

**Comment by Saloni0512** [comment]
I would like to work on this issue as a gssoc contributor.
Thank you

**Comment by anmode** [comment]
oh great! please

**Comment by anmode** [comment]
hey? @Saloni0512 you can create a draft pR. So i can see the progress

**Comment by Saloni0512** [comment]
Actually I haven't made much progress like I am still going through the codebase , I have my exams going on as well. Also can you elaborate a bit on what exactly I need to fix here. If you need this issue fixed immediately, then you can assign it to someone else.Sorry for the delay.

**Comment by anmode** [comment]
So when you go to your Gmail.. When you click on the profile a card comes in. So same to be created. can you tell me when you will get free? i'll decide then

**Comment by Saloni0512** [comment]
Okay got it . My exams will get over tomorrow,then I'll be free

**Comment by Saloni0512** [comment]
I am facing difficulty in fixing this, you can assign the issue to someone else.

**Comment by Abhinavcode13** [comment]
Ok cool @Saloni0512

**Comment by anmode** [comment]
> I am facing difficulty in fixing this, you can assign the issue to someone else.

no problem. In this case, you can create PR and we can guide you. Keep contributing there can be small issues. Just check the website carefully.
