### ISSUE TITLE
[Bug] Links not Working

### ISSUE THREAD

**Issue by parthpathakpp1** [anmode/grabtern-frontend#119]
When we click on any hackathon it does not redirect us to their official site instead it takes us top the Grabtern's hero section . 
I will add link to hackathon cards which will redirect us to their website.  

https://github.com/anmode/grabtern-frontend/assets/85991449/315f5a1a-1efb-452d-ae9f-756bd1932a9d

**Comment by parthpathakpp1** [comment]
Assign this issue to me under GSSOC'23.

**Comment by anmode** [comment]
Sure. Please fix all the links and add more hackathons that you know and also internships..Uses of svgs or compressed images would be appriciated.

**Comment by parthpathakpp1** [comment]
> es of svgs or compr

ok.
