### ISSUE TITLE
Add ContributingGuidelines.md

### ISSUE THREAD

**Issue by shanvijha30** [anmode/grabtern-frontend#122]
The Contributing Guideline documentation will contain set of guidelines that will help contributors during the contribution process.
File type markdown.

**Comment by shanvijha30** [comment]
@anmode Could you please assign this issue to me under GSSOC 23.
Thank you!

**Comment by anmode** [comment]
All the templates would you complete under #128. you comment there and create pR on one of the templates. And also there are many bugs please find out!

**Comment by AmanJain18** [comment]
The issue doesn't get counted dear, only merged Pr tag will get counted.
