### ISSUE TITLE
Fix Session card and make it responsive

### ISSUE THREAD

**Issue by VSatwika** [anmode/grabtern-frontend#123]
- The Book Review and User Form page have extra space at the bottom.
 - Eliminating the space will give the pages cleaner look

    Book Review Page
     ![bspace4](https://github.com/anmode/grabtern-frontend/assets/112561024/b4a8c496-41a6-4138-b956-a3eb19dd28c7)

    User Login Page
     ![bextra](https://github.com/anmode/grabtern-frontend/assets/112561024/30401192-78b3-473c-a6cb-5d2d7b2f42a4)

     Could this issue be assigned to me under GSSoC'23?

**Comment by anmode** [comment]
could you improve UI of one of the page?

**Comment by anmode** [comment]
@VSatwika up for it?

**Comment by VSatwika** [comment]
> @VSatwika up for it?

Hello! I've been trying but I'm unable to make the desired changes.

**Comment by shivang-16** [comment]
can I do this?

**Comment by anmode** [comment]
> > @VSatwika up for it?
> 
> Hello! I've been trying but I'm unable to make the desired changes.

oh np! Please find other bugs and you can fix them. thanks
