### ISSUE TITLE
⚠️ Important UI change: Navbar height

### ISSUE THREAD

**Issue by shaikahmadnawaz** [anmode/grabtern-frontend#124]
I will make this Navbar attractive by doing improvements in Navbar styling, by reducing its height.

![Screenshot (845)](https://github.com/anmode/grabtern-frontend/assets/96189881/149d680a-ff68-4da5-855b-125b3ef73ee8)

I'm in GSSOC'23, please assign this issue to me.

**Comment by anmode** [comment]
ok! but make sure you have to modify for mobile too. and also before and after login too! please carefully debug

**Comment by shaikahmadnawaz** [comment]
> ok! but make sure you have to modify for mobile too. and also before and after login too! please carefully debug

Okay 👍🏻

**Comment by anmode** [comment]
got for it!! waiting for pR

**Comment by anmode** [comment]
hey? you can create draft pR so i can see the progress.

**Comment by Anmol-Baranwal** [comment]
Hi, @anmode. I would like to contribute this issue :)

**Comment by anmode** [comment]
great

**Comment by Anmol-Baranwal** [comment]
@anmode,

This issue has already been resolved in #202. I explicitly mentioned not to assign #259 to someone else. I'm not complaining, just stating that it takes time to analyze the website and determine how I can contribute. Nonetheless, thank you for your assistance. Now, I have nothing else to do :)

**Comment by anmode** [comment]
> @anmode,
> 
> This issue has already been resolved in #202. I explicitly mentioned not to assign #259 to someone else. I'm not complaining, just stating that it takes time to analyze the website and determine how I can contribute. Nonetheless, thank you for your assistance. Now, I have nothing else to do :)

Ah, oh ok, I didn't noticed.
Actually we are told that not to assign simultaneously issues. Nd that's the reason. Otherwise i too think if author wnna work on created his/her issue they can.
