### ISSUE TITLE
Adding Hover Effect(Gssoc'23)

### ISSUE THREAD

**Issue by shwetazade27** [anmode/grabtern-frontend#125]
Hover effect can be added on these cards 
![420_new](https://github.com/anmode/grabtern-frontend/assets/84389800/fb4c9ece-6809-493a-8488-0e09a73d7ed2)

**Comment by anmode** [comment]
Not needed...assigned you one of this issue! feel free to work on that. thanks

**Comment by shwetazade27** [comment]
@anmode okay.. Thankyou for reply
