### ISSUE TITLE
[Feature] Team Page

### ISSUE THREAD

**Issue by prrockzed** [anmode/grabtern-frontend#127]
When we click on the names of each and every people, it takes us to the home page again. I would like it redirect to one of their social media handles like linkedin/github.

Please assign it to me under gssoc23.

**Comment by prrockzed** [comment]
@anmode if you would like me handle the issue, then please assign it to me under gssoc23 or else close it. Thanks.

**Comment by anmode** [comment]
I would be removing the grabtern community! Moving it to a different page...As a Team, R u up for creating team page?

**Comment by prrockzed** [comment]
yeah sure, will be delighted to do that. Do update me regarding this.

**Comment by anmode** [comment]
Great!

**Comment by Abhinavcode13** [comment]
What's the progress of the work? @prrockzed

**Comment by ePSA-eJya** [comment]
I am a gssoc contributor. i would like to work on this issue @anmode

**Comment by anmode** [comment]
@ePSA-eJya you are working on a issue.. This issue will be assigned to you after completing that. thank you!

**Comment by anmode** [comment]
@prrockzed ?

**Comment by Abhinavcode13** [comment]
Closing it @anmode
