### ISSUE TITLE
[BUG] Redesigning Top Hackathons page

### ISSUE THREAD

**Issue by dhrumishah** [anmode/grabtern-frontend#132]
The name of hackathon is not visible on the image until someone hovers on it. I would like to fix it.

![image](https://github.com/anmode/grabtern-frontend/assets/84569241/3a6fd244-1c47-4d0e-aea8-f4663c488741)

**Comment by anmode** [comment]
It's good! Please wait to this pR to be merged https://github.com/anmode/grabtern-frontend/pull/121.
