### ISSUE TITLE
[FEAT] Improving UI of Login page

### ISSUE THREAD

**Issue by dhrumishah** [anmode/grabtern-frontend#133]
The UI of current login page is not visually appealing. I would like to work under GSSoC.

![image](https://github.com/anmode/grabtern-frontend/assets/84569241/3b32b06b-e52e-4c6f-992e-bf53eb06d3d4)

**Comment by anmode** [comment]
Cool!

**Comment by anmode** [comment]
I have assigned an issue to u please complete it...then I'll assign this! THANKS

**Comment by jayantsingh-22** [comment]
I want to work on this project!!. Kindly assign it to me.

**Comment by anmode** [comment]
> can I start working on it?

yeah sure!!

**Comment by anmode** [comment]
> I want to work on this project!!. Kindly assign it to me.

@dhrumishah comes first.. could you please look at other issues.. a major fixes

**Comment by dhrumishah** [comment]
Hey @anmode, actually by mistake I made the commit for revamping the login page in pr #146 where I solved the bug for issue #132. Can you please have a look at it?
