### ISSUE TITLE
Add proper template for issue generating

### ISSUE THREAD

**Issue by k-deepak04** [anmode/grabtern-frontend#135]
i can creat one template for creating the issue so it would be in proper format
with idea/functionality and bug as option

![image](https://github.com/anmode/grabtern-frontend/assets/96341431/95ac0ad5-9126-484f-ba3d-ab34d1953fdb)
![image](https://github.com/anmode/grabtern-frontend/assets/96341431/c1ec0447-4921-4b40-8b5b-7ee9160e739f)

please assign this to me under GSSOC-23

**Comment by anmode** [comment]
already there- https://github.com/anmode/grabtern-frontend/issues/128
