### ISSUE TITLE
Readme Improvisation

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#138]
Include all the test case..and how to fix them
like as if prettier test failed-
Run `npx prettier --write .`

**Comment by anmode** [comment]
sure

**Comment by anmode** [comment]
@prrockzed r u up for it! ?

**Comment by abhi03ruchi** [comment]
I want to add Technology Stack used in the ReadMe. This would be quite helpful for contributors who are looking forward to contributing to the project.

This would enhance the readMe section.
Plz, assign me this task.
