### ISSUE TITLE
Adding on-hover animation to the "Featured internship" section

### ISSUE THREAD

**Issue by abhinav-m22** [anmode/grabtern-frontend#140]
Adding hover effects to the card components on the "Featured internship" section will improve the UX of the page.
Also it will maintain the consistency throughout the web page.

Image for refernence:

<img width="959" alt="image" src="https://github.com/anmode/grabtern-frontend/assets/113239388/3725c5da-241d-440f-bf7e-61e48d3181a3">

I want to work on this feature.
Please assign me task under GSSoC'23.

**Comment by anmode** [comment]
Not needed please look for other UI improvisation like a mentor page or mentor card..or registration form.
