### ISSUE TITLE
Missing Issue Template in Repository 

### ISSUE THREAD

**Issue by Nishitbaria** [anmode/grabtern-frontend#142]
**Description:**

I noticed that the repository does not have an issue template. Having an issue template can greatly improve the clarity and consistency of issue reports, making it easier for contributors and maintainers to understand and address the problems or feature requests effectively.

**Comment by Nishitbaria** [comment]
I have Created Template you can review the pull Request and then merge it: https://github.com/anmode/grabtern-frontend/pull/141

**Comment by anmode** [comment]
Done!
