### ISSUE TITLE
💡 [REQUEST] - a button on bottom right of page which will take on top of website

### ISSUE THREAD

**Issue by RJ025** [anmode/grabtern-frontend#144]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.

---

| Section                   | Description                                                        |
| ------------------------- | ------------------------------------------------------------------ |
| **Concise Description**   | if a person want to go on top of website they will have to scroll i will add a button which directly take user to top of website |
| **Solution Proposed**     |a button on bottom right of page which will take on top of website  |

                                 

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by k-deepak04** [comment]
@RJ025 have you checked 
i guess it's already there

**Comment by RJ025** [comment]
thank you for assigning me this issue will start working on it
