### ISSUE TITLE
{GSSOC'23} fixing a error in UI of mentors page 

### ISSUE THREAD

**Issue by thekirti02** [anmode/grabtern-frontend#145]
### Description

There is a description about the mentor which is coming out form the boundaries.

### Screenshots

<img width="947" alt="issue 2 in grabtern" src="https://github.com/anmode/grabtern-frontend/assets/105008820/a61c924d-3ddd-40e7-816a-c073c8d7b07f">

### Additional information

I would like to fix this bug, please assign it to me.

**Comment by Ayushhgupta39** [comment]
I want to work on this issue, please assign this to me.

**Comment by anmode** [comment]
@thekirti02  are u working.. or i assign this to @Ayushhgupta39 ?

**Comment by thekirti02** [comment]
I am working on this please give me some time.

**Comment by anmode** [comment]
sure! you can create draft pR. i can see the progress too

**Comment by Abhinavcode13** [comment]
What's the update can I know @thekirti02 ?

**Comment by thekirti02** [comment]
Yes, I changed the mentor's card size, but it took up a lot of space. I am just trying to minimize it. I will be done with this issue within 2-3 days.

**Comment by Ayushhgupta39** [comment]
Instead of changing the card size, try to adjust the text inside it.

**Comment by anmode** [comment]
@thekirti02 @Ayushhgupta39 ? anyone working

**Comment by Ayushhgupta39** [comment]
I guess @thekirti02 was. I'm out of town now, so can't work for now

**Comment by anmode** [comment]
no worries.. will catch up later
