### ISSUE TITLE
Improve the UI of the Return Policy Page, T&C , Privacy Policy

### ISSUE THREAD

**Issue by divya-2910** [anmode/grabtern-frontend#147]
![image](https://github.com/anmode/grabtern-frontend/assets/113793606/2dc7b0c6-d4d1-4d31-ba1f-1258f575c2b0)

I want to improve the UI of this page and make it look in sync with the styles of the other pages.
 @anmode Can you please assign this to me under GSSOC'23??

**Comment by anmode** [comment]
Sure please and also the other page too! T&C and Privacy Policy!
