### ISSUE TITLE
Enhance: Navbar buttons

### ISSUE THREAD

**Issue by kasturimandlik** [anmode/grabtern-frontend#148]
### Description

Hello,
I would like to add CSS to nav bar and hover the buttons.
I would like to work on this issue under GSSOC'23.
Please assign me this issue.

**Comment by StillAbeginnerr** [comment]
I have assigned you the task. All the best

**Comment by kasturimandlik** [comment]
Thank you for assigning me this issue. I will create a pr according to the requirements. Please give me some time till next week I will create the pr as I have my exams going on.

**Comment by StillAbeginnerr** [comment]
The issue is solved in pr #158.
