### ISSUE TITLE
Fix the links of Internships buttons

### ISSUE THREAD

**Issue by divya-2910** [anmode/grabtern-frontend#149]
### Description

![image](https://github.com/anmode/grabtern-frontend/assets/113793606/b96ab79b-5f91-406c-b44e-3118e7d5f020)

On clicking the links, they are just redirecting to the home page rather than the specific internship pages. 
I want to work on this under GSSOC'23. 
@anmode Can you please assign it to me??

**Comment by anmode** [comment]
You have been assigned an issue...could you carry this one in that PR, please? as this is simple one.

**Comment by divya-2910** [comment]
Okay sure
