### ISSUE TITLE
💡 [REQUEST] - Adding Dark Mode For the Website

### ISSUE THREAD

**Issue by akuldeepj** [anmode/grabtern-frontend#154]
- [ Yes] I am from GSSoC'23.
- [Yes ] I would like to be assigned this task.

---

The current website doesn't have a dark Mode. So I would Like to create the dark mode for the complete website.So please assign me for this issue

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [ Yes] I follow the Contributing Guidelines of this project.
- [ YES] I have checked the current issues for duplicate problems.
- [ YES] I have read the readme of this repository.

**Comment by mandliyarajendra11** [comment]
@anmode  @AmanJain18  this issue is still open ??? i want to work on this issue .......

**Comment by AmanJain18** [comment]
Will update u give me some time

**Comment by mandliyarajendra11** [comment]
> Will update u give me some time

ok sir

**Comment by akuldeepj** [comment]
Actually @anmode put this issue on hold
