### ISSUE TITLE
💡 [REQUEST] - Add more bots to github. Improve optimization

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#155]

**Comment by Isha988** [comment]
@anmode I want to work on this issue under gssoc program. I have never worked on github bots but I am interested in learning more about it.
Also I would like to know which bots do you want to add.

**Comment by crocmons** [comment]
Also I want to know how to add bots in github?

**Comment by anmode** [comment]
So bots are added in GitHub.. We have to write their code in the .github folder in our repo.
@Isha988...can you do some research? I mean what bots are required and are necessary..It would be a great contribution.

**Comment by Isha988** [comment]
> So bots are added in GitHub.. We have to write their code in the .github folder in our repo. @Isha988...can you do some research? I mean what bots are required and are necessary..It would be a great contribution.

Hey, @anmode I already have an issue assigned to me, I would love to do this after that.
If @crocmons want to do, she can go ahead.

**Comment by crocmons** [comment]
Let's try..want to work this issue..
