### ISSUE TITLE
💡 [REQUEST] - <title>Scroll to top 

### ISSUE THREAD

**Issue by Abhishek8287** [anmode/grabtern-frontend#156]
- [ ALT + 0215] I am from GSSoC'23.
- [ALT + 0215 ] I would like to be assigned this task.

---

| Section                   | Description                                                        |
| ------------------------- | ------------------------------------------------------------------ |
| **Concise Description**   |A sroll to top button that will take the user directly on the top after clicking on it .|
| **Solution Proposed**     | A scroll to top button                              |
| **Alternative Solutions** | Describe any alternative solutions you can think of                |
| **Additional Context**    | Write any other contexts related to the feature request            |
| **Screenshots**           | [Provide screenshots here]                                         |

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [ALT + 0215 ] I follow the Contributing Guidelines of this project.
- [ALT + 0215 ] I have checked the current issues for duplicate problems.
- [ALT + 0215] I have read the readme of this repository.

**Comment by anmode** [comment]
ok! but think of other navigation..then that contribution will be meaningful

**Comment by Abhishek8287** [comment]
@anmode  what do u mean by that i couldn't understand...........should i start working on the feature

**Comment by anmode** [comment]
> @anmode what do u mean by that i couldn't understand...........should i start working on the feature

yes please! I mean top to bottom...seeek for other navigation

**Comment by Abhishek8287** [comment]
ok sure

**Comment by Abhinavcode13** [comment]
Tell me the progress of our work till now @Abhishek8287 !!

**Comment by Abhishek8287** [comment]
Actually I'am traveling right now therefore I can't show you ....i"ll complete it by 3 Jan ...
