### ISSUE TITLE
IMPROVE EXPLORE TOP HACKTHON SECTION

### ISSUE THREAD

**Issue by whizzy23** [anmode/grabtern-frontend#157]
As there links that are are appearing over the images which is making them look jumbled .
I would like to add hover effect on those links so that they only appear when cursor is moved over them . 
Please assign this issue to me.

https://github.com/anmode/grabtern-frontend/assets/129520458/9162823c-345f-45e1-99b3-c0b4e2d28c17

leftmost is the earlier , and the other three are the one I changed

**Comment by anmode** [comment]
Hey, Thanks for raising the issue. sorry, but we won't need...there are many improvements. Please look at those!!. I will be creating issues. please comment on that
