### ISSUE TITLE
UI Improvement for Login Page

### ISSUE THREAD

**Issue by crocmons** [anmode/grabtern-frontend#159]
### Description

**Login Page UI should be improve for better user experience.** @anmode Can you please assign this to me under GSSOC'23?? 

### Screenshots

![Screenshot (352)](https://github.com/anmode/grabtern-frontend/assets/106610322/bde75128-7753-4802-8197-587eb1d3812c)

**Comment by AmanJain18** [comment]
@anmode Assign this issue to me

**Comment by anmode** [comment]
ok! @crocmons is working on another issues...So by guidelines, I can assign!
