### ISSUE TITLE
UI Improvement: Navbar taking too space of the screen

### ISSUE THREAD

**Issue by crocmons** [anmode/grabtern-frontend#160]
### Description

Navbar width taking too space of the screen which is not good for UX ..we have to decrease the width of the navbar for all devices..@anmode Can you please assign this to me under GSSOC'23??

### Screenshots

![Screenshot (354)](https://github.com/anmode/grabtern-frontend/assets/106610322/dcab27c8-9713-4826-b3bb-853bac3772d8)
![Screenshot (356)](https://github.com/anmode/grabtern-frontend/assets/106610322/2698054a-fbfb-4f90-8d41-b14db2a2ed7f)

**Comment by anmode** [comment]
Ok! please fix that in mobile and desktop too. also seek if you any new idea about nav!. I'll mark at NavBar Development

**Comment by AmanJain18** [comment]
assign it to me if possible

**Comment by AmanJain18** [comment]
assign it to me if possible, as already discussed with u earlier

**Comment by anmode** [comment]
Ah yes! my bad @crocmons I have assigned you mentor card optimization. We will discuss more about there. Thanks.
I have  to dasssign this as one time one issue would be assigned

**Comment by crocmons** [comment]
ok I will take mentor card optimization you can assign the navbar issue to  @AmanJain18

**Comment by anmode** [comment]
Ok!

**Comment by ananyakushal** [comment]
Hey @anmode if no one is doing this task, please assign this to me under gssoc2023.

**Comment by anmode** [comment]
I think @AmanJain18 is up for it.
