### ISSUE TITLE
UI Change: Find Mentor, Contact Us of these Containers

### ISSUE THREAD

**Issue by crocmons** [anmode/grabtern-frontend#161]
### Description

**Find Mentor, Contact Us these containers are taking too space of the screen.. we have to fix this by decreasing the padding inside this container so that it enhance the better UI for users..@anmode Can you please assign this to me under GSSOC'23??**

### Screenshots

Now it looks like:
![Screenshot (359)](https://github.com/anmode/grabtern-frontend/assets/106610322/e22fdf48-caf9-41d7-907b-85d0a835512c)

After Decreasing the padding it looks like this:
![Screenshot (358)](https://github.com/anmode/grabtern-frontend/assets/106610322/685b138d-d78b-4ff2-b429-6288339d6f1d)

**Comment by anmode** [comment]
Ok!. Optimize the mentor page.

**Comment by Abhinavcode13** [comment]
Is the issue resolved ? @anmode

**Comment by crocmons** [comment]
> Is the issue resolved ? @anmode

Already merged
