### ISSUE TITLE
Hover Effect on Featured Cards

### ISSUE THREAD

**Issue by crocmons** [anmode/grabtern-frontend#162]
### Description

**we can implement hover effects on each Featured Cards for better UI..@anmode Can you please assign this to me under GSSOC'23??**

### Screenshots

Now it looks like:
![screenshot-www grabtern com-2023 05 27-14_26_54](https://github.com/anmode/grabtern-frontend/assets/106610322/85d94592-6cb4-407c-9495-3a12d334aadd)

After adding the hover effect for each card it will look like this with blur drop-
[screencast-retink-lime.vercel.app-2023.05.25-14_13_05.webm](https://github.com/anmode/grabtern-frontend/assets/106610322/e742d6ed-0913-4faf-b3d4-a62088f2fb85)

**Comment by anmode** [comment]
Could you please look at other UI development. At this time this is not required!!
