### ISSUE TITLE
Mentor card is overflowing 

### ISSUE THREAD

**Issue by Isha988** [anmode/grabtern-frontend#164]
### Description

Mentor card is overflowing.

### Screenshots

![Screenshot_2023-05-27-16-21-45-71_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/anmode/grabtern-frontend/assets/89572340/15edf538-9457-421e-a818-4b19952b2182)

### Additional information

I want to work on this issue under gssoc program.

**Comment by anmode** [comment]
https://github.com/anmode/grabtern-frontend/issues/83 please comment here.
