### ISSUE TITLE
Improve After login Card...Hover on profile and also create card

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#166]
### Description

As in Gmail when we click our profile a card comes... So create one

**Comment by shivaniyuvrajyadav** [comment]
hey @anmode will please describe little bit about this issue . i want to work on it under GSSOC'23 program

**Comment by Arioum** [comment]
Hey @anmode, could I take up this issue?

**Comment by Visbhavesh** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by Visbhavesh** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by anmode** [comment]
Really sorry! This issue will be on hold for some time.. I'll ping whenever I resume and the first commentator will be assigned. Thanks
