### ISSUE TITLE
💡 [Caching] - Enable Use of Cookie

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#167]
We are currently using local storage...... so want to migrate to cookies. Main Aim is to increase speed.

**Comment by archiejain28** [comment]
Hi @anmode, I would like to work on this issue under Gssoc'23. Please assign it to me.

**Comment by anmode** [comment]
that's cool!

**Comment by anmode** [comment]
Are you sure? you can do this? this is hard one and also level 3

**Comment by archiejain28** [comment]
Yes, I previously worked with cookies. I think I can do that.

**Comment by anmode** [comment]
@archiejain28 ?

**Comment by archiejain28** [comment]
Hi @anmode,
Sorry for the delay. I am available now. 
I can connect once you are free to understand the requirements better.

**Comment by Abhinavcode13** [comment]
@archiejain28 update us please?

**Comment by archiejain28** [comment]
Hi @Abhinavcode13 , I already discussed the updates with Anmol.

@anmode Opened the PR, please review.
