### ISSUE TITLE
💡 [REQUEST] - Create A mentor page

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#168]
see -
https://mentro.tech/mentor

We want a mentor page....this would be nice issue

**Comment by Isha988** [comment]
@anmode I want to work on this issue

**Comment by anmode** [comment]
great!...It would be descent contribution

**Comment by Isha988** [comment]
> @anmode I want to work on this issue

Thank you assigning it, can you tell me which  sections are required in mentor page?

**Comment by anmode** [comment]
> > @anmode I want to work on this issue
> 
> Thank you assigning it, can you tell me which sections are required in mentor page?

I tagged a link in the description..same sections!

**Comment by Abhinavcode13** [comment]
progress of your work @Isha988 ?

**Comment by Isha988** [comment]
@Abhinavcode13 I am sorry, due to some urgent work I was unable to start working on this issue but now will try to complete it as soon as possible.

**Comment by anmode** [comment]
no worries...create PR. and keep working on that. while we can provide our suggestion too
