### ISSUE TITLE
💡 [REQUEST] - Blog section

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#169]
So there would be a separate blog section.
This is only frontend work- 
You can take inspiration from - https://www.amupedia.com/blog

**Comment by Tushar98644** [comment]
I have completed the previous pr , please assign it to me

**Comment by anmode** [comment]
It is not completed! Contribution matter... Please I advice to focus now on that.. I make sure current PR would be a descent contribution... Thinking to include all bots.

**Comment by Arioum** [comment]
Hey @anmode, I can take up this issue.

**Comment by anmode** [comment]
sure!

**Comment by Arioum** [comment]
Thanks! I'll work on it!

**Comment by ePSA-eJya** [comment]
i would want to work on this issue. i am a gssoc 23 contributor.

**Comment by anmode** [comment]
@ePSA-eJya assigned you a issue! Waiting to see your first pR merged.
@Arioum what's the update you can create working in progress PR

**Comment by Arioum** [comment]
Sure! I'll create one tomorrow!

Please confirm whether the blogs section is to be on a separate page, if so where should the link be on the homepage to access the blogs page?

**Comment by ePSA-eJya** [comment]
@anmode @AmanJain18  I would waant to work on this.i am a gssoc23 contributor.please assign this issue to me.

**Comment by anmode** [comment]
@ePSA-eJya author said he will resume on 28th.. if he not do so.. you can takeover this issue on 30th thanks
