### ISSUE TITLE
Improve the footer section [Not well organised]

### ISSUE THREAD

**Issue by rohan9024** [anmode/grabtern-frontend#171]
### Description

![image](https://github.com/anmode/grabtern-frontend/assets/64919642/25d274cf-90d5-4ad1-93ea-6dbcb974c7b7)

We can make it look even better than before.

Please assign me this issue

**Comment by anmode** [comment]
This would be cool! optimize for mobile then too! Thanks

**Comment by AmanJain18** [comment]
@anmode  This is the footer for Amupedia and i already assign it someone else... Kindly check it

**Comment by anmode** [comment]
oh yess!!..I should close and it also doesn't look cool!. 
@rohan9024 please could you look at other issues in codebase?
