### ISSUE TITLE
Adding 404 Error page

### ISSUE THREAD

**Issue by SagarPatil007** [anmode/grabtern-frontend#172]
### Description

I want to add 404 error page according to website design.
@anmode can you please assign me this role ?

### Screenshots

[
![image](https://github.com/anmode/grabtern-frontend/assets/58733512/026d2441-470e-4c38-9a1d-5173291940a6)
](url)

**Comment by anmode** [comment]
Sure!

**Comment by anmode** [comment]
@SagarPatil007 ?

**Comment by Deepanshu0703** [comment]
can you now assign it to me i want to work on it

**Comment by Deepanshu0703** [comment]
Is it looking good, matching with rest of your website or should i implement by adding new theme 

![image](https://github.com/anmode/grabtern-frontend/assets/114489502/ef7138dd-c799-4eaf-b490-1ba00c7bedcb)


please see this @anmode

**Comment by AmanJain18** [comment]
The theme is good, change the Image which refers to the context of error page

**Comment by AmanJain18** [comment]
Use 1st image @Deepanshu0703

**Comment by Abhinavcode13** [comment]
@Deepanshu0703 update of work?
