### ISSUE TITLE
🐛 [BUG] - Improve validation of Registration form [User]

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#173]
There is scope of validation:
1. Mentor registration form
2. Login 
3. Registration

TBR- There is server-side validation too!

**Comment by Bhakti087** [comment]
Does one have to Implement Custom Validation Logic?

**Comment by Bhakti087** [comment]
Also , please assign me this under gssoc 23

**Comment by anmode** [comment]
> Does one have to Implement Custom Validation Logic?

hmm like that!
