### ISSUE TITLE
Optimize footer and add discord link to it!

### ISSUE THREAD

**Issue by thakurdiwakar** [anmode/grabtern-frontend#178]
### Description

When a user clicks on any social media icon in the footer section, the expected behavior should be for the link to open in a new tab. However, in this case, the desired action does not occur, and the link fails to open in a new tab.

I am a GSSOC CONTRIBUTOR ,PLEASE  assign me this task.

**Comment by anmode** [comment]
I chaged it, R u up for it?

**Comment by thakurdiwakar** [comment]
Yes i am ready

**Comment by anmode** [comment]
great

**Comment by anmode** [comment]
@thakurdiwakar ?
