### ISSUE TITLE
💡 [REQUEST] - add pre push hook

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#179]
Before pushing... Linter should run and check formatting validation. if not then suggest the command to fix it!

**Comment by AishwaryaSatpute1** [comment]
please assign me the task of implementing a linter to validate code formatting before pushing. The goal is to ensure consistent formatting and suggest automated fixes. Your guidance in this process would be greatly appreciated.

**Comment by Abhinavcode13** [comment]
@AishwaryaSatpute1 are you up for this issue?

**Comment by AishwaryaSatpute1** [comment]
I wanted to express my willingness to address the issue at hand. I am more than happy to take it on and contribute to finding a solution. However, I also want to emphasize that I greatly value guidance from others, as their insights and expertise can be invaluable.

If you have any suggestions, recommendations, or guidance regarding this matter, I would be sincerely grateful to receive them. Your input will undoubtedly help me navigate this issue more effectively and efficiently.

**Comment by anmode** [comment]
so @AishwaryaSatpute1 are you up for it? sure I'll provide some help over it. come to discord please

**Comment by AishwaryaSatpute1** [comment]
#!/bin/bash

# Run the linter command (replace `lint-command` with the actual command you use)
lint-command

# Check the exit code of the linter
if [ $? -ne 0 ]; then
    echo "Linting failed. Please fix the formatting issues."
    exit 1
fi

# If the linter succeeded, automatically fix the formatting (replace `fix-command` with the command to fix formatting)
fix-command

# Add the fixed files to the staging area
git add .

# Display a success message
echo "Formatting issues fixed. Ready to push."

# Exit with a success code
exit 0
Open a text editor and paste the above code into a new file.

Replace lint-command with the actual command you use to run the linter. This could be a command like npx eslint . or black ., depending on the linter you're using.

Replace fix-command with the command you use to automatically fix formatting issues. For example, npx eslint --fix . or black . --check --diff.

Save the file as pre-push (without any file extension) in the .git/hooks/ directory of your local repository.

Make the script executable by running the following command in your terminal: chmod +x .git/hooks/pre-push
