### ISSUE TITLE
[DOCS] Adding Tech Stacks used in ReadMe

### ISSUE THREAD

**Issue by abhi03ruchi** [anmode/grabtern-frontend#180]
### Description

 want to add Technology Stack used in the ReadMe. This would be quite helpful for contributors who are looking forward to contributing to the project.

This would enhance the readMe section.
Plz, assign me this task.

### Screenshots

Sample :- 
<img width="558" alt="Screenshot 2023-05-25 at 10 06 44 PM" src="https://github.com/anmode/grabtern-frontend/assets/105661636/91062681-bfa7-46bd-9dbc-70bbb08d72bc">

### Additional information

Plz assign me this task under gssoc'23.

**Comment by anmode** [comment]
could you please comment on this- https://github.com/anmode/grabtern-frontend/issues/138
