### ISSUE TITLE
[DOCS] Add Contributors Graph

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [anmode/grabtern-frontend#183]
### Description

I would like to incorporate a contributor graph in the README.md file as a means of acknowledging and appreciating the work of contributors. I kindly request to be assigned this particular issue.

### Screenshots

Here is an example of the work I aspire to undertake within this project.

![Screenshot (80)](https://github.com/anmode/grabtern-frontend/assets/112751524/5f0a3c15-0a22-456c-95d4-34193a6175b9)

**Comment by anmode** [comment]
Sorry! already a contributor working on the same...Readme Improvisation include this issue!. THanks please look out other issues
