### ISSUE TITLE
💡 [REQUEST] - Add a custom scroll-bar

### ISSUE THREAD

**Issue by abhinav-m22** [anmode/grabtern-frontend#184]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.

---

| Section                   | Description                                                        |
| ------------------------- | ------------------------------------------------------------------ |
| **Concise Description**   | Change the basic scroll bar to a custom stylish scroll bar which matches the theme of the website. It will improve the overall design and UX of the web page. |
| **Solution Proposed**     | The custom scroll bar can be designed by adding basic CSS styles to the webkit-scrollbar class.                  |
| **Additional Context**    | A custom scrollbar adds uniqueness and originality to the design, making it more fascinating for users.            |

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by anmode** [comment]
Do you wanna work on that? I am not sure I'll merge or not. if it look good. Surely be merged? wanna work ?

**Comment by abhinav-m22** [comment]
It will look good surely.... I'll add the scroll bar and share a screenshot here!

**Comment by MohitGupta121** [comment]
@abhinav-m22 feel free to make PR for that along with recording, so it's looks good we can merge it.
