### ISSUE TITLE
💡 [REQUEST] - <Font properties of the website>

### ISSUE THREAD

**Issue by shruti8302** [anmode/grabtern-frontend#187]
-  I am from GSSoC'23.
- I would like to be assigned this task.

I would  like to improve the font properties of the homepage. Kindly assign this issue to me.

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by anmode** [comment]
Please improve font of whole site then! You can suggest some fonts and we can provide some feedback on the same

**Comment by shruti8302** [comment]
@anmode Sure I will
