### ISSUE TITLE
💡 [REQUEST] - <UI Improvement> Navbar and User login page

### ISSUE THREAD

**Issue by arpittyagirocks** [anmode/grabtern-frontend#192]
Hello, I would like to improve the UI of Login page for users, it really needs attention
Also the Navbar seems very thick, Please assign me this Issue

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by anmode** [comment]
great!

**Comment by AmanJain18** [comment]
@arpittyagirocks Both issues are already assigned to me dear 
Check #159, #160

**Comment by anmode** [comment]
oh yes yess!! It's my bad. I forgot.
