### ISSUE TITLE
UI Issue: Profile Icon should be middle of the screen in mobile device

### ISSUE THREAD

**Issue by crocmons** [anmode/grabtern-frontend#193]
### Description

UI Issue: Profile Icon should be on middle of the screen in mobile device...Can you assign this issue to me as GSSOC23 contributor?
![Screenshot (373)](https://github.com/anmode/grabtern-frontend/assets/106610322/d9f98d3d-5a44-43c9-b12d-a1ef6e6c3773)

**Comment by anmode** [comment]
Could you optimize the mentor form?

**Comment by crocmons** [comment]
yeah, sure I can do... @anmode

**Comment by anmode** [comment]
great!

**Comment by anmode** [comment]
you can continue that commit... of reverting that line in this pR.

**Comment by crocmons** [comment]
> you can continue that commit... of reverting that line in the pR of this issue!

Are you talking about that line gap:25px in css which I mentioned you on discord?

**Comment by anmode** [comment]
yes yes!. I'll change the issue to mentor form improvisation.

**Comment by anmode** [comment]
one thing.. i noticed there is issue. https://github.com/anmode/grabtern-frontend/issues/48.

**Comment by anmode** [comment]
I'll close this issue! R u willing to contribute to this? I'll assign you then https://github.com/anmode/grabtern-frontend/issues/75

**Comment by crocmons** [comment]
> I'll close this issue! R u willing to contribute to this? I'll assign you then #75

ok then, you can close this issue...
