### ISSUE TITLE
💡 [REQUEST] - Break Global CSS into Modular CSS components

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#194]
This is really nice! and an easy one. But it will take time.

**Comment by anmode** [comment]
https://github.com/anmode/grabtern-frontend/pull/106

**Comment by Vidip-Ghosh** [comment]
Can I work on this issue?

**Comment by anmode** [comment]
On a first come first serve basis! @Vidip-Ghosh ....but i think it would be great if you both can pair for this issue.. To speed up the work...
what's say?

**Comment by anmode** [comment]
I have assigned this issue to @Vidip-Ghosh. 
@Swarnlataaa could you work on other issues? I'll create more issues by tonight

**Comment by anmode** [comment]
@Vidip-Ghosh ? are you there.

**Comment by Vidip-Ghosh** [comment]
Yes I am here.
