### ISSUE TITLE
Optimising Mentors cards and the font.

### ISSUE THREAD

**Issue by kartikkc** [anmode/grabtern-frontend#195]
I am from GSSOC'23, and I have noticed that,
The cards on the mentors page would be better with some enlarged font and less space on them. I want to work on it.
Could you assign me this issue?

**Comment by anmode** [comment]
if you can create a figma design.. if the design better then the current one.. I will accept. Thank you!

**Comment by kartikkc** [comment]
Sure, I have created this  Figma design for the design I am trying to propose. 

link: https://www.figma.com/file/c5Su5SK52bAJgKB5waSC4n/Mentor-Cards?type=design&node-id=0%3A1&t=trd1ao8N03OAut5v-1

**Comment by anmode** [comment]
Great! But a thing to notice. Profile pic section will be not great. as pic we fetch from google and should be rounded circle.. Neverthless. I see you good at figma. Mentor dashboard needs a fresh look? I'll change the issue and assign you. Nd it would be level 3!! So r u up for it?

**Comment by kartikkc** [comment]
Mentor Dashboard is this one? right?!
![Mentor-Dashboard](https://github.com/anmode/grabtern-frontend/assets/63699242/434a5633-15d3-429b-843c-890aca9ab2f6)

**Comment by anmode** [comment]
Oh no! It's a dashboard page....ok btw you can try to give this ( Mentor page) a new fresh look!

**Comment by kartikkc** [comment]
I will take up this at first and then will do that too. 
First I will provide you with the Figma Design and after your approval then I will start on the coding part.

**Comment by ePSA-eJya** [comment]
> It's not a dashboard page....ok btw you can try to give this ( Mentor page) a new fresh look!

i would want to work on this issue. i am a gssoc 23 contributor.

**Comment by anmode** [comment]
> I will take up this at first and then will do that too. First I will provide you with the Figma Design and after your approval then I will start on the coding part.

cool!

**Comment by kartikkc** [comment]
> It's not a dashboard page....ok btw you can try to give this ( Mentor page) a new fresh look!

I have created the design. check this out and confirm that if I can start working on this?

link : https://www.figma.com/file/Pc2Ij7CGi868q1GcYxcdaO/Mentor's-Page?type=design&node-id=0%3A1&t=Drq4j2mDCLFbodvc-1

**Comment by navinkrv** [comment]
![image](https://github.com/anmode/grabtern-frontend/assets/97692286/e9981852-ccc4-421b-96f8-b437d59871bd)

here is a sample design. please assign me the issue then we can make neccessary changes to it

**Comment by MohitGupta121** [comment]
@navinkrv please feel free to make a PR.
Thanks!

**Comment by anmode** [comment]
@navinkrv ? it looks cool please make pR
