### ISSUE TITLE
[UI Improvement] : Hackathons Section

### ISSUE THREAD

**Issue by archiejain28** [anmode/grabtern-frontend#198]
### Description

**Problem**:
Hackathon's titles are not visible properly until we hover the card under 'Explore Top Hackathons' section.  Also on hover, borders of the images are not aligned properly.
This needs to be improved for better user experience. 

**Solution**:
**Option (1)** Remove the blue layer from hover effect and adding it on the cards permanently. And correct the borders.
**Option (2)** Hide the title, and it should be visible only on hover.

Hi @anmode, Could please look into this and assign this to me. Please let me know if you have any other suggestions. 

### Screenshots

**Before**:

![image](https://github.com/anmode/grabtern-frontend/assets/82926210/6ba0efac-4d4b-4df4-a9ed-c4114aa1aa7f)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
![image](https://github.com/anmode/grabtern-frontend/assets/82926210/db956b3a-64a4-4b75-b757-4766fd53352e)

**Solution:** 
**Option (1)** 
![image](https://github.com/anmode/grabtern-frontend/assets/82926210/464c283f-bac6-44d8-b825-1fc32514cf43)

**Option (2)**
![image](https://github.com/anmode/grabtern-frontend/assets/82926210/292e8487-adc5-47de-843d-437338db4c65)

**Comment by anmode** [comment]
nice! See for the new UI card.. something 3d or shadow effect ( Just a suggestion)
