### ISSUE TITLE
Add CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by ImranNawar** [anmode/grabtern-frontend#201]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.

Hi there!
I recommend adding a **CODE_OF_CONDUCT.md** file to your repository. This file would serve as a guide for potential contributors, providing them with a clear set of expectations, guidelines, and behavior standards for participating in your project. It plays an essential role in creating a welcoming and inclusive environment for everyone involved.

I would like to work on this issue. Please assign it to me under **GSSoC'23**.

Thank you!                               

By submitting this issue, you agree to follow our Code of Conduct.
- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by anmode** [comment]
ok
