### ISSUE TITLE
💡 [REQUEST] - Privacy Policy Page

### ISSUE THREAD

**Issue by parthpathakpp1** [anmode/grabtern-frontend#203]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.

---

| Section                   | Description                                                        |
| ------------------------- | ------------------------------------------------------------------ |
| **Concise Description**   | Privacy policy page does not look good , no css and animations in it . |
| **Solution Proposed**     | I will improve the UI of this page by adding css and animations.                           |
| **Alternative Solutions** | Describe any alternative solutions you can think of                |
| **Additional Context**    | Write any other contexts related to the feature request            |
| **Screenshots**           | ![grabternprivateplociyissue](https://github.com/anmode/grabtern-frontend/assets/85991449/46d06566-5c11-4022-97a7-b62f155341fd)|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by anmode** [comment]
https://github.com/anmode/grabtern-frontend/pull/153 carrying out in this... if pR author did not response you can take over. thanks
