### ISSUE TITLE
💡 [REQUEST] - MAKING TEXT VISIBLE FOR HACKATHONS SECTION

### ISSUE THREAD

**Issue by 0xabdulkhalid** [anmode/grabtern-frontend#209]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.

---

| Section                   | Description                                                        |
| ------------------------- | ------------------------------------------------------------------ |
| **Concise Description**   | The white color text is not visible with images which are not in lower contrast, So that the user might be struggle to read the text |
| **Solution Proposed**     | I'm going to add black background with lower opacity, So that the text could be visible   |
| **Additional Context**    | I'm also going to add smooth zoom-in, zoom-out transition for the `img` which gives a nice look in terms of UX   |
| **BEFORE**           | ![Screenshot 2023-05-31 at 09-12-15 GrabTern](https://github.com/anmode/grabtern-frontend/assets/92252895/5d1d588a-c70f-4e47-931c-61435f9b2c10) |
| **AFTER**           | ![Screenshot 2023-05-31 at 09-13-20 GrabTern](https://github.com/anmode/grabtern-frontend/assets/92252895/6cc0bb9e-f200-4cdc-b203-122078656a21) |

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by anmode** [comment]
already a issue! I assigned for hackathon card improvment
