### ISSUE TITLE
Add ContributingGuidelines.md

### ISSUE THREAD

**Issue by shanvijha30** [anmode/grabtern-frontend#210]
### Description

The Contributing Guideline documentation will contain set of guidelines that will help contributors during the contribution process.
File type markdown.

**Comment by shanvijha30** [comment]
@anmode Could you please assign this issue to me under GSSOC 23.
Thank you!

**Comment by anmode** [comment]
Hi! Thanks for raising this issue. actually, previously a contributor works on it. I forget to add it. Could you please look for other issue may be some UI improvement or bug fix or optimization.
