### ISSUE TITLE
Footer Section Improvement

### ISSUE THREAD

**Issue by Vidip-Ghosh** [anmode/grabtern-frontend#212]
### Description

Footer Section is distorted for smaller and medium devices like words getting overlapped, overflow etc.

### Screenshots

<img width="893" alt="Screenshot 2023-05-31 at 21 10 17" src="https://github.com/anmode/grabtern-frontend/assets/91741581/a4abdd49-1ac9-4d05-ab59-b9b47def175a">

<img width="518" alt="Screenshot 2023-05-31 at 21 09 33" src="https://github.com/anmode/grabtern-frontend/assets/91741581/398b5d72-caf6-45a9-b675-32932bd3ae54">

<img width="568" alt="Screenshot 2023-05-31 at 21 11 22" src="https://github.com/anmode/grabtern-frontend/assets/91741581/04e0700f-5552-4994-9fd5-0b132fac3a9f">

### Additional information

I would like to work on this issue under GSSOC'23.

**Comment by anmode** [comment]
I guess you are working on CSS modules??

**Comment by Vidip-Ghosh** [comment]
@anmode I apologize for opening issue in the wrongg repository. Its my mistake.
