### ISSUE TITLE
💡 [REQUEST] - Improve Nav bar and also make it responsive

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#214]
There are numerous issues with nav.  Mainly in the case of the mobile view. Please try to seek for issues by running the project locally

**Comment by ananyakushal** [comment]
Hey @anmode, please assign me this task under gssoc2023.

**Comment by anmode** [comment]
R u sure? It would be a tough one... actually, you have to optimize it full.

**Comment by ananyakushal** [comment]
Yes, I'm sure. Also, it would be great if you could tell me about some features which you exactly want.

**Comment by anmode** [comment]
That's cool! No no Just make it responsive and I think it good to remove the hover effect of glowing.

**Comment by ananyakushal** [comment]
Thanks for assigning!

**Comment by anmode** [comment]
Are you working @ananyakushal ?

**Comment by anmode** [comment]
Are you working @ananyakushal ?
