### ISSUE TITLE
[Defect] - UI is broken with the latest changes

### ISSUE THREAD

**Issue by archiejain28** [anmode/grabtern-frontend#217]
**Description:** 

I see UI is streched when I run localhost with the latest changes. It looks vague, need to be fixed as soon as possible for better user experience.

Screenshots:

Before - 

![image](https://github.com/anmode/grabtern-frontend/assets/82926210/faae4ad1-29c8-4dd5-b46c-f5691174cc69)

![image](https://github.com/anmode/grabtern-frontend/assets/82926210/d96f1491-5ff3-42a0-b1af-826a795c843b)

After - (With latest changes)

![image](https://github.com/anmode/grabtern-frontend/assets/82926210/3ab20c4f-65cb-4ee8-9f2a-994c86e18708)

![image](https://github.com/anmode/grabtern-frontend/assets/82926210/46d0879c-9e4f-47a0-b7ee-a4ec349273fb)

**Comment by anmode** [comment]
Hey! @Visbhavesh there are improvement please could you see and fix them.
