### ISSUE TITLE
[DOCS] <description> provide the author accounts in effective manner in readme

### ISSUE THREAD

**Issue by ishikagoyal02** [anmode/grabtern-frontend#218]
### Description

Author profiles of LinkedIn, GitHub, and Twitter will be displayed in a beautiful manner. By creating buttons of these.

**Comment by anmode** [comment]
Hey, Thanks but it not needed.. could you look out older issues may be you find a perfect fit and if author is inactive I'll aisign you.

**Comment by AmanJain18** [comment]
SS ?
