### ISSUE TITLE
💡 [REQUEST] - Add hover effects to social media icons and to the tabs.

### ISSUE THREAD

**Issue by ePSA-eJya** [anmode/grabtern-frontend#220]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.

---

| Section                   | Description                                                        |
| ------------------------- | ------------------------------------------------------------------ |
| **Concise Description**   | Adding hover effects on the tabs and social media icons |
| **Solution Proposed**     | on hovering the social media icons change colour and also grow in size , the home, mentors tabs etc show  selection effect when hovered                         |
| **Screenshots**           | ![image](https://github.com/anmode/grabtern-frontend/assets/120899038/1b032f7b-301e-4396-af2f-a383e658d878)                                         |

![image](https://github.com/anmode/grabtern-frontend/assets/120899038/f7eb0a3d-ee4f-4552-b3f1-dc792181458e)

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by RajivRnjan** [comment]
I am interested to work on this issue under Quine. So please assign me this issue to me.

**Comment by Pratipada013** [comment]
interested I can solve these please assign me these projects under  3GSSOC2023

**Comment by MohitGupta121** [comment]
@Pratipada013 please go ahead
