### ISSUE TITLE
add social media icons on mentor page

### ISSUE THREAD

**Issue by ePSA-eJya** [anmode/grabtern-frontend#221]
### Description

add the social media icons on the mentor page

### Screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/120899038/91516147-25c1-4091-8c30-712c2d12ce4a)

**Comment by anmode** [comment]
assigned you an issue! You can get assigned this when you complete that one. Or you have the choice to choose one. Thank you keep contributing.

**Comment by anmode** [comment]
> i would want to work on this. please assign me this issue as soon as i complete the other one.

sure! but as of guidelines i cannot assign two issue to single person at one time.

**Comment by ePSA-eJya** [comment]
i have finished working on this. if you could assign this task to me then i would be able to make aPR @anmode .
Meanwhile i am working on the other issue as well.

**Comment by ePSA-eJya** [comment]
i have raised a pr on this issue. if you could please review and merge it @anmode .

**Comment by anmode** [comment]
Hii, i reviewed and left you some comments.... making you PR a good contribution

**Comment by ePSA-eJya** [comment]
> Hii, i reviewed and left you some comments.... making you PR a good contribution

yes thanks
