### ISSUE TITLE
💡 [REQUEST] - <Search bar on mentors page>

### ISSUE THREAD

**Issue by ePSA-eJya** [anmode/grabtern-frontend#222]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.

---

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by ePSA-eJya** [comment]
yes sure . i will complete it within a week

**Comment by Abhinavcode13** [comment]
@ePSA-eJya update please?

**Comment by ePSA-eJya** [comment]
Need a week more. @Abhinavcode13

**Comment by Abhinavcode13** [comment]
@ePSA-eJya okay take your time , ping me here if you have any issues!
