### ISSUE TITLE
💡 [REQUEST] - <contributor page>

### ISSUE THREAD

**Issue by ePSA-eJya** [anmode/grabtern-frontend#223]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.

---

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by anmode** [comment]
sorry it it not needed! this project is part of a startup. We will appreciate contributors to our project repo.. That's on GitHub
For getting a contributor page on Grabtern I have to discuss.
