### ISSUE TITLE
Enhance : UI of Our Featured Internship section.

### ISSUE THREAD

**Issue by Pragati-3003** [anmode/grabtern-frontend#226]
I would like to changes the ui of the cards.
![grab5](https://github.com/anmode/grabtern-frontend/assets/132778037/2cca4dab-f8bc-4004-a0d3-7f5d242b560c)
I would like to add some hover effects and box shadows .
So,please assign this to me under gssoc23.

**Comment by anmode** [comment]
it is good! there are many Ui improvements please have a look at them
