### ISSUE TITLE
Improve Navbar UI

### ISSUE THREAD

**Issue by Ayush9951** [anmode/grabtern-frontend#227]
### Description

Hi, I am a contributor in GSSOC'23.
Navbar Icons are not aligned properly vertically.
I want to work on fixing this issue.
please assign me this task under label gssoc'23

### Screenshots

![Screenshot 2023-06-02 001310](https://github.com/anmode/grabtern-frontend/assets/60573378/a715cfd8-4ebb-475a-8c91-fa5aaaf40763)

**Comment by Visbhavesh** [comment]
please assign it to me

**Comment by anmode** [comment]
@Ayush9951 ? are you up for it?

**Comment by anmode** [comment]
Here are some point:

1. Create a separate CSS file named header.js
2. Redesign the CSS and add some good properties.( You can suggesting a UI)
3. Please keep the class name meaningful
4. Remove that CSS from global CSS or any place all CSS should be in one file corresponding to that component / Page

Concept: Modular CSS
For Help refer : https://github.com/anmode/grabtern-frontend/commit/28db8d25a0bdac3670a984348e273f96197c37c7

**Comment by muskandn** [comment]
If it is still open can you assign this to me... I want to work on this

**Comment by Ayush9951** [comment]
Hi @anmode, you can assign me the issue

**Comment by Ayush9951** [comment]
Hi @muskandn, your portfolio website is looking really good you can change the colors maybe. I just want to know how to create good portfolio website?

**Comment by anmode** [comment]
@Ayush9951 are you working on this or I assign this to @muskandn or @Visbhavesh ?

**Comment by Ayush9951** [comment]
Hi @anmode, you can assign the issue to them.

**Comment by navinkrv** [comment]
if its still open please assign it to me. i can fix it up

**Comment by Akash1965** [comment]
Hi @anmode If it's still open please assign it to me. I would love to work on this
