### ISSUE TITLE
💡 [REQUEST] - Adding a resource page and share helpful resources and links

### ISSUE THREAD

**Issue by Ishita-Ghosh-25** [anmode/grabtern-frontend#231]
- [ ] I am from GSSoC'23.
- [ ] I would like to be assigned this task.

---

| Section                   | Description                                                        |
| ------------------------- | ------------------------------------------------------------------ |
| **Concise Description**   | Resources are getting redirected to the same page instead of opening a new page |
| **Solution Proposed**     |  Creating a resource page and adding resources to it in the form of card |
| **Alternative Solutions** | Describe any alternative solutions you can think of                |
| **Additional Context**    | Write any other contexts related to the feature request            |
| **Screenshots**           |
<img width="946" alt="image" src="https://github.com/anmode/grabtern-frontend/assets/70560812/3c2c51a1-e5d6-43c8-95a5-0cdb4b7f9b09">
 |

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by anmode** [comment]
I just add that link.. for maintaining the UI. could you think of what we can add in the resource page? :)

**Comment by brohithkr** [comment]
What are some resources that you would like to be added?

**Comment by anmode** [comment]
tbh.. as of now I do not have any idea what can be added. pinging @glokta1 , @AmanJain18 @Riyazul555 @sayyedarib
