### ISSUE TITLE
💡 [REQUEST] - UI of Login page

### ISSUE THREAD

**Issue by Hemant2335** [anmode/grabtern-frontend#234]
- [ x] I am from GSSoC'23.
- [x ] I would like to be assigned this task.

---

| Section                   | Description                                                        |
| ------------------------- | ------------------------------------------------------------------ |
| **Concise Description**   |Improvement in Login Page UI |
| **Solution Proposed**     | I would like to make it more similar with the current theme also adding some alerts  |
| **Alternative Solutions** |Other solution could be changing the colours of the card to more bright colour  |
| **Screenshots**           |  
![Screenshot (102)](https://github.com/anmode/grabtern-frontend/assets/85656999/560ef2ed-2986-4b03-9cf5-4e668756214e)
 |

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [ x] I follow the Contributing Guidelines of this project.
- [ x] I have checked the current issues for duplicate problems.
- [ x] I have read the readme of this repository.

**Comment by anmode** [comment]
cool!
