### ISSUE TITLE
Fixing The description box in Be A Mentor Section

### ISSUE THREAD

**Issue by JAYESHBATRA** [anmode/grabtern-frontend#235]
### Description

The Description Box in Be A Mentor needs to have a minimum height so that it looks professional. 

Also the length of the description box should automatically change on the amount of text content in it.

I will fix this issue. 

Kindly Assign me this issue under GSSOC'23

### Screenshots

Before:
<img width="899" alt="image" src="https://github.com/anmode/grabtern-frontend/assets/112322302/c724eae9-47d5-4949-a175-0447fce128c8">

After:
<img width="685" alt="image" src="https://github.com/anmode/grabtern-frontend/assets/112322302/4c458c67-53cd-4d4b-a724-50330cb3a210">

**Comment by JAYESHBATRA** [comment]
@anmode Please assign me this issue.

**Comment by anmode** [comment]
I would love to cover it in https://github.com/anmode/grabtern-frontend/issues/48
