### ISSUE TITLE
💡 [REQUEST] - Make CSS Modular ( MentorLogin.page.js )

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#236]
1. Create a separate CSS file named MentorLogin.css
2. Redesign the CSS and add some good properties.
3. Please keep class name meaningful

Concept: Modular CSS
For Help refer : https://github.com/anmode/grabtern-frontend/commit/28db8d25a0bdac3670a984348e273f96197c37c7

**Comment by Sage-2001** [comment]
Hey, I think I can work on this issue.
