### ISSUE TITLE
💡 [REQUEST] - Make CSS modular Privacy Policy

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#237]
1. Create a separate CSS file named privacypolicy.css
2. Redesign the CSS and add some good properties.
3. Please keep the class name meaningful
4. Remove that CSS from global CSS or any place all CSS should be in one file corresponding to that component / Page

Concept: Modular CSS
For Help refer : https://github.com/anmode/grabtern-frontend/commit/28db8d25a0bdac3670a984348e273f96197c37c7

**Comment by Abhinavcode13** [comment]
HEY @anmode can i take up this issue ;) hehe

**Comment by anmode** [comment]
haa sure why not!
