### ISSUE TITLE
💡 [REQUEST] - Make Modular Registration.page.js

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#238]
1. Create a separate CSS file named Registration.css
2. Redesign the CSS and add some good properties.
3. Please keep the class name meaningful
4. Remove that CSS from global CSS or any place all CSS should be in one file corresponding to that component / Page
5. You can make a new UI too with css file

Concept: Modular CSS
For Help refer : https://github.com/anmode/grabtern-frontend/commit/28db8d25a0bdac3670a984348e273f96197c37c7

**Comment by Pragati-3003** [comment]
> 1. Create a separate CSS file named Registration.css
> 2. Redesign the CSS and add some good properties.
> 3. Please keep the class name meaningful
> 4. Remove that CSS from global CSS or any place all CSS should be in one file corresponding to that component / Page
> 5. You can make a new UI too with css file
> 
> Concept: Modular CSS For Help refer : [28db8d2](https://github.com/anmode/grabtern-frontend/commit/28db8d25a0bdac3670a984348e273f96197c37c7)
I would like to work on this ,please assign this to me
