### ISSUE TITLE
💡 [REQUEST] - Make Modular CSS for footer

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#239]
1. Create a separate CSS file named footer.css that corresponds to the footer.js ( componenet)
2. Redesign the CSS and add some good properties.
3. Please keep the class name meaningful
4. Remove that CSS from global CSS or any place all CSS should be in one file corresponding to that component / Page

Concept: Modular CSS
For Help refer : https://github.com/anmode/grabtern-frontend/commit/28db8d25a0bdac3670a984348e273f96197c37c7

**Comment by Pragati-3003** [comment]
> 1. Create a separate CSS file named footer.css that corresponds to the footer.js ( componenet)
> 2. Redesign the CSS and add some good properties.
> 3. Please keep the class name meaningful
> 4. Remove that CSS from global CSS or any place all CSS should be in one file corresponding to that component / Page
> 
> Concept: Modular CSS For Help refer : [28db8d2](https://github.com/anmode/grabtern-frontend/commit/28db8d25a0bdac3670a984348e273f96197c37c7)

i would like to work on this ,please assign this to me .

**Comment by anmode** [comment]
oops sorry! I think i am doing this is  another PR. could you comment on other related issue?

**Comment by Pragati-3003** [comment]
> oops sorry! I think i am doing this is another [PR](https://github.com/anmode/grabtern-frontend/pull/230). could you comment on other related issue?

Okie
