### ISSUE TITLE
💡 [REQUEST] - Make Modular CSS for internship.js

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#240]
1. Create a separate CSS file named Internship.css
2. Redesign the CSS and add some good properties.
3. Please keep the class name meaningful
4. Remove that CSS from global CSS or any place all CSS should be in one file corresponding to that component / Page

Concept: Modular CSS
For Help refer : https://github.com/anmode/grabtern-frontend/commit/28db8d25a0bdac3670a984348e273f96197c37c7

**Comment by Vidip-Ghosh** [comment]
I would like to work on this issue under GSSoC'23

**Comment by Asthasingh-2002** [comment]
Can I also work on the same issue?

**Comment by anmode** [comment]
@Asthasingh-2002 interested?
