### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Harshu467** [anmode/grabtern-frontend#241]
### Description

Given Favicon is irrelevant to the project , It should be removed

### Screenshots

![Screenshot from 2023-06-03 12-11-52](https://github.com/anmode/grabtern-frontend/assets/89975347/5e08c4f8-4727-4845-bcc2-96e003b9c562)

**Comment by Abhinavcode13** [comment]
Not required there are already many good first issue , you can check em out first.

thankyou
