### ISSUE TITLE
Fix: Error with Issue form

### ISSUE THREAD

**Issue by Anmol-Baranwal** [anmode/grabtern-frontend#244]
### Description

@anmode 
- Fix error in Feature Request Issue Form
- I am tagging you, since I believe this is urgent.

You can check out my work on GitHub issue forms in this pull request: https://github.com/dailydotdev/daily/pull/864. It demonstrates my familiarity with the concept and implementation.

### Screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/74038190/bc790f5a-d474-4234-a94a-be62b4d45542)

### Additional information

- I will quickly solve this issue, by making a PR.

Please assign me, and I will start contributing to this issue by creating a pull request.

**Comment by anmode** [comment]
yep there is issue with form! and also needed some bots too! could you work on these?

**Comment by anmode** [comment]
will cover this too! https://github.com/anmode/grabtern-frontend/issues/243

**Comment by anmode** [comment]
I would be happy if i can have technical improvement such as optimization and enhancement in UI

**Comment by Anmol-Baranwal** [comment]
> will cover this too! #243

I don't understand, are you suggesting to cover both issues in one PR?

**Comment by anmode** [comment]
> > will cover this too! #243
> 
> I don't understand, are you suggesting to cover both issues in one PR?
> 
> > I would be happy if i can have technical improvement such as optimization and enhancement in UI
> 
> Sure, I will see what I can contribute :)

ah ok! you can create a seperate PR! thanks
