### ISSUE TITLE
[DOCS] Update Contributing guidelines

### ISSUE THREAD

**Issue by Anmol-Baranwal** [anmode/grabtern-frontend#245]
### Description

I would like to add a few points:

- I would like to include some basic guidelines for first-time contributors, outlining the GitHub workflow they should follow.
- Additionally, I want to emphasize that Pull Requests without an associated issue will not be accepted. It is important for contributors to have an assigned issue, whether it has already been opened or raised by them, before creating a Pull Request. This requirement helps maintain organization and clarity throughout the development cycle.

### Additional information

I would like to contribute to this under GSSoC'23. 

> Please assign me, and I will start contributing to this issue by creating a pull request.

**Comment by anmode** [comment]
Not needed! as of now

**Comment by Anmol-Baranwal** [comment]
> Not needed! as of now

Thanks for letting me know.
