### ISSUE TITLE
[FEATURE] Add social media links in Grabtern Community

### ISSUE THREAD

**Issue by Anmol-Baranwal** [anmode/grabtern-frontend#257]
### Description

- Basic social media links, such as `GitHub`, `LinkedIn`, and `Twitter`, can be included.

- I will add a hover effect and utilize modern practices for the same.

### Solution Proposed

A maximum of 3 social media links should be added, and since it is mainly developers, I believe the above suggested ones are appropriate. Feel free to suggest any other social media icons if you think they would be suitable. 

I will separate the data if possible.

### Checklist

- [X] I have checked the existing [issues](https://github.com/anmode/grabtern-frontend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/anmode/grabtern-frontend/blob/develop/CONTRIBUTING.md)
- [X] I would like to be assigned this task.
- [X] I am a GSSoC'23 contributor

**Comment by anmode** [comment]
Not required.. as i am thinking to remove that section. Thanks
