### ISSUE TITLE
[FEATURE] Top Contributors Section

### ISSUE THREAD

**Issue by Anmol-Baranwal** [anmode/grabtern-frontend#258]
### Description

I would like to create a section similar to the Grabtern Community that showcases the top contributors. For each contributor, I intend to display the following:

- Their GitHub profile avatar, linked to their GitHub profile URL.
- A link to their commit history.
- A link to their GitHub profile.

To ensure consistency, I will implement a logic that only displays contributors who have made at least 5 contributions.

Please let me know if you have any suggestions or if there are any specific requirements to consider.

### Checklist

- [X] I have checked the existing [issues](https://github.com/anmode/grabtern-frontend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/anmode/grabtern-frontend/blob/develop/CONTRIBUTING.md)
- [X] I would like to be assigned this task.
- [X] I am a GSSoC'23 contributor

**Comment by anmode** [comment]
Sorry! We can't have this..... On Readme we can have. But yes we are thinking to have best contributor to our site home page.

**Comment by Anmol-Baranwal** [comment]
The idea of showcasing only the best contributor often undermines the overall purpose because project administrators or collaborators tend to have the highest number of commits due to their special privileges. Even merging a commit is considered a contribution in their commit history. Overall, its up to you.
