### ISSUE TITLE
[FEATURE] Semantic Suggestion with other UX Changes

### ISSUE THREAD

**Issue by Anmol-Baranwal** [anmode/grabtern-frontend#260]
### Description

- As depicted in the screenshot, both the `logo` and `HOME` link redirect to the home page, which can cause confusion for users. I would remove `HOME`

- There is no clear distinction when someone clicks on the navigation link.

- Additionally, the formatting of the login button is unclear, which is another issue I would address.

### Screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/74038190/6209005d-bac3-4ba7-9322-dc767d29d4c3)

### Checklist

- [X] I have checked the existing [issues](https://github.com/anmode/grabtern-frontend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/anmode/grabtern-frontend/blob/develop/CONTRIBUTING.md)
- [X] I would like to be assigned this task.
- [X] I am a GSSoC'23 contributor

**Comment by anmode** [comment]
yep! Actually there is pR for improvment of this. Let's see afterwards
