### ISSUE TITLE
[FEATURE] Overlay with text on Mentor Registration page

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#262]
### Description

I will be attaching a pic. 

### Screenshots

![Screenshot 2023-06-05 at 5 24 00 PM](https://github.com/anmode/grabtern-frontend/assets/88332977/33b4441a-1a00-4dc4-9de7-ab2f69a20350)

### Additional Context

This is a good issue

### Checklist

- [X] I have checked the existing [issues](https://github.com/anmode/grabtern-frontend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/anmode/grabtern-frontend/blob/develop/CONTRIBUTING.md)
- [ ] I would like to be assigned this task.
- [ ] I am a GSSoC'23 contributor

**Comment by Vidip-Ghosh** [comment]
I would like to work on this issue

**Comment by anmode** [comment]
please start this ASAP!
