### ISSUE TITLE
[FEATURE] Improve section 2

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#264]
### Description

Please improve the section using 3D animated git or 3d icons. 
Use off good css required

### Screenshots

<img width="1207" alt="Screenshot 2023-06-05 at 5 38 03 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/a9ba1ab6-ea38-475d-b841-e543eac93fab">

### Checklist

- [X] I have checked the existing [issues](https://github.com/anmode/grabtern-frontend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/anmode/grabtern-frontend/blob/develop/CONTRIBUTING.md)
- [ ] I would like to be assigned this task.
- [ ] I am a GSSoC'23 contributor

**Comment by ManavMalhotra** [comment]
I would like to work on this issue and improve the section using 3D animated git or 3d icons. I have experience with CSS. 
Please assign this issue to me and let me know if you have any feedback or suggestions.

**Comment by anmode** [comment]
great

**Comment by anmode** [comment]
@ManavMalhotra ?
