### ISSUE TITLE
[FEATURE] Improve UI of this section

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#266]
### Description

Please improve the CSS for this section. Creation of Figma design would be appriciated

### Screenshots

<img width="1232" alt="Screenshot 2023-06-05 at 5 37 55 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/c7b6a985-7140-4140-b522-888320787044">

### Checklist

- [X] I have checked the existing [issues](https://github.com/anmode/grabtern-frontend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/anmode/grabtern-frontend/blob/develop/CONTRIBUTING.md)
- [ ] I would like to be assigned this task.
- [ ] I am a GSSoC'23 contributor

**Comment by abhi03ruchi** [comment]
I would like to work on this issue. I am well-versed in CSS. Plz, assign me this task.

**Comment by Yoogiitaa** [comment]
I would like to work on the UI design of this section using figma. Please assign me this issue

**Comment by anmode** [comment]
@Yoogiitaa ? are up for this/

**Comment by anmode** [comment]
@Yoogiitaa there are more issues! please could you look them out or you can create any enhacnement issue

**Comment by Yoogiitaa** [comment]
@anmode can i work upon redesigning the login page/box?

**Comment by Abhinavcode13** [comment]
@Yoogiitaa yeah sure create issue for that !

**Comment by abhi03ruchi** [comment]
I have created a pr , plz review and merge.
