### ISSUE TITLE
[FEATURE] New hero section.

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#267]
### Description

This is Issue required a figma design as hero section is main section of site and it should be impressive.
you can suggest some design and then afterwards can start working.afterward

This is a level 3 issue.

### Additional Context

<img width="1270" alt="Screenshot 2023-06-05 at 5 54 34 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/2e17badb-850b-45cf-b5ea-9666be137cb8">

### Checklist

- [X] I have checked the existing [issues](https://github.com/anmode/grabtern-frontend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/anmode/grabtern-frontend/blob/develop/CONTRIBUTING.md)
- [ ] I would like to be assigned this task.
- [ ] I am a GSSoC'23 contributor

**Comment by ManavMalhotra** [comment]
Hi, I'm interested in working on this issue. 
I have some experience with creating hero sections for websites and I can help you implement the feature. Do you have any figma design or mockup that you can share with me? 
I would like to see your vision and inspiration for the new hero section. 
Thanks!

**Comment by anmode** [comment]
<img width="740" alt="Screenshot 2023-06-05 at 6 37 54 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/767afad5-1000-43b4-ba47-628d0197d5ed">
I like this...if you have some deisgn you can suggest

**Comment by anmode** [comment]
@AmanJain18 up for it? as this issue is now `grabtern team`

**Comment by anmode** [comment]
@itsmohit097 https://github.com/anmode/grabtern-frontend/issues/295
