### ISSUE TITLE
[FEATURE] Mentor Form Re Design

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#268]
### Description

So we will be diving mentor registration form into 2 step process:
1. Personal Details
2. Contact Details

### Checklist

- [X] I have checked the existing [issues](https://github.com/anmode/grabtern-frontend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/anmode/grabtern-frontend/blob/develop/CONTRIBUTING.md)
- [ ] I would like to be assigned this task.
- [ ] I am a GSSoC'23 contributor

**Comment by Isha988** [comment]
@anmode @AmanJain18 I want to work on this.

**Comment by anmode** [comment]
Oh your working on this issue... can we convo before starting this issue. Please ping me on discord if you are up for this.

**Comment by Isha988** [comment]
Ya sure

**Comment by Isha988** [comment]
Should I start working on this?

**Comment by anmode** [comment]
Will see it after the dashboard.!

**Comment by anmode** [comment]
@Isha988 if you are ready? can we start working on this before the dashboard? As i Disscussed

**Comment by Isha988** [comment]
Ya I am ready

**Comment by anmode** [comment]
great then!! I had already given what the form looks like... if you want me to brief you again or have some doubts feel free to ask we can have to meet too. thanks

**Comment by Isha988** [comment]
1.Personal details 
image 
name 
username 
email
phone bio

2.Contact details
intern 
current status 
Linked 
Twitter

3. Session timing  and price

Is this the correct format of pages and should I also include password field?
