### ISSUE TITLE
[FEATURE] Create Mentor Dashboard

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#269]
### Description

This is great issue of level 3
Here you have to create the frontend part of the mentor dashboard.
you can suggest a dashboard design. we are open to suggestions and then we will start working.

### Checklist

- [X] I have checked the existing [issues](https://github.com/anmode/grabtern-frontend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/anmode/grabtern-frontend/blob/develop/CONTRIBUTING.md)
- [ ] I would like to be assigned this task.
- [ ] I am a GSSoC'23 contributor

**Comment by Isha988** [comment]
@anmode and @AmanJain18 I want to work on this.

**Comment by anmode** [comment]
@Isha988 up for this? as your pR about to complete

**Comment by Isha988** [comment]
@anmode I will start working on this after redesign task.

**Comment by vishnu9865** [comment]
@anmode and Guys, Can I work on this issue ?
I can suggest a design in Figma as a Start.
Regards,
Jeyavishnu @vishnu9865

**Comment by anmode** [comment]
yeah sure @vishnu9865 it would be cool. and I request you to break this issue into two or three issues and all are of level 3
