### ISSUE TITLE
[FEATURE] Enhancing UI of Contact Page

### ISSUE THREAD

**Issue by abhi03ruchi** [anmode/grabtern-frontend#272]
### Description

I would like to improve the UI of the Contact page.

### Additional Context

Plz assign me this task under gssoc'23..

### Checklist

- [X] I have checked the existing [issues](https://github.com/anmode/grabtern-frontend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/anmode/grabtern-frontend/blob/develop/CONTRIBUTING.md)
- [X] I would like to be assigned this task.
- [X] I am a GSSoC'23 contributor

**Comment by anmode** [comment]
@abhi03ruchi ? are you there

**Comment by abhi03ruchi** [comment]
yes, I was unable to complete my assigned work for GSSoC'23 due to the process of moving into my new house. However, I assure you that I will submit it by Tuesday.

**Comment by Abhinavcode13** [comment]
closing this issue
