### ISSUE TITLE
[DOCS] Workflows for the codebase

### ISSUE THREAD

**Issue by Anmol-Baranwal** [anmode/grabtern-frontend#273]
### Description

@anmode,

You requested me to work on implementing proper workflows using GitHub Actions, as shown in the picture. I would like to know the specific workflows you would like to add. Here are some examples, and if approved, I will create separate pull requests for each workflow to maintain a clean commit history:

- Workflow to update dependencies: This workflow will handle updating dependencies as demonstrated in the image you provided.

![image](https://github.com/anmode/grabtern-frontend/assets/74038190/69ba6152-51a7-4c2e-8975-5c2af7cc0c89)

- Comment on creating new issues: This workflow will automatically comment on newly created issues, providing relevant information or guiding users to read the contribution guidelines.

- Comment on creating new pull requests: This workflow will comment on new pull requests, requesting mandatory information such as greetings, reminding contributors to read the contribution guidelines, or advising them to wait for maintainers to review the pull request.

- Workflows related to continuous integration and deployment: These workflows will address criteria related to continuous integration and deployment, which may lead to multiple workflows depending on the specific requirements.

- Closing old pull requests: This workflow will focus on closing old pull requests that are no longer relevant to the codebase.

Please review these suggestions, and which of these meet your requirements, I will provide separate descriptions for each issue and create distinct pull requests for further discussion.

> Please don't assign this to others, since it takes expertise and effort to write a workflow with proper conventions.

Okay! Sure feel free to work. 

### Checklist

- [X] I have checked the existing [issues](https://github.com/anmode/grabtern-frontend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/anmode/grabtern-frontend/blob/develop/CONTRIBUTING.md)
- [X] I would like to be assigned this task.
- [X] I am a GSSoC'23 contributor

**Comment by anmode** [comment]
Cool!

**Comment by AmanJain18** [comment]
@Anmol-Baranwal Sorry, Mate u don't have to do this now.. Already Completed

**Comment by anmode** [comment]
So sorry @Anmol-Baranwal. I forget that Aman was already working on this issue. There is a need for bot improvisation you can carry forward. Remember there would be nice cases I'll discuss in pR

**Comment by Anmol-Baranwal** [comment]
@anmode,
Let's discuss the cases and the overall idea of BOT improvisation. Why create a new issue to discuss something when we can easily address it here? If the discussion proves fruitful, then I will create a formal issue accordingly.

**Comment by anmode** [comment]
That's cool, Thank you really, So as you can see. when the author or maintainer raises an issue bot treat them as a contributor...they should be greeted differently and 2nd-time contributor differently and the same for pRs.
and seek other GitHub actions. 

I request there are numerous frontend issues. If are up for it. See in the Issue tracker some past issue hasn't had any activity.
