### ISSUE TITLE
Adding drop shadow to the Card Items in Home page

### ISSUE THREAD

**Issue by muskandn** [anmode/grabtern-frontend#274]
### Description

![Screenshot from 2023-06-05 23-48-02](https://github.com/anmode/grabtern-frontend/assets/99585352/00b7e8fb-c477-4e86-bf6d-6e558bfdb924)

I would like to add some shadow in the card items as the color of the card items and the background is not distinguishable. 
And adding to this we can also give some hover effect to the card items.

### Checklist

- [X] I have checked the existing [issues](https://github.com/anmode/grabtern-frontend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/anmode/grabtern-frontend/blob/develop/CONTRIBUTING.md)
- [X] I would like to be assigned this task.
- [X] I am a GSSoC'23 contributor

**Comment by anmode** [comment]
@muskandn thanks for raising issue. But sorry we don't need this. Please look for other improvements

**Comment by muskandn** [comment]
Ohh okay... No problem.
