### ISSUE TITLE
📚 [Documentation / WorkFlow] - Fix Heading in Mentors Page

### ISSUE THREAD

**Issue by Sriparno08** [anmode/grabtern-frontend#282]
### Description ✍️

The below heading can be fixed in two ways:

- here's -> here
- Capitalize the first letter of each word (since it's a heading)

![Screenshot 2023-06-06 181247](https://github.com/anmode/grabtern-frontend/assets/89148144/08fe34f3-81a5-4eae-89bb-424ba1824693)

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Abhinavcode13** [comment]
Assigned to you start working @Sriparno08
