### ISSUE TITLE
🚀 [Feature Request] - Work on page name, Meta Tag, SEO , Name In URL. 

### ISSUE THREAD

**Issue by itsmohit097** [anmode/grabtern-frontend#284]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement 
 
The title is not defining the site as it opens. It would be better if  the title name is similar to site name.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Replace the current title with the "GrabTern"
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Abhinavcode13** [comment]
Elaborate @itsmohit097

**Comment by itsmohit097** [comment]
When we open the site on the title bar "Internship | Education" is showing with a green tick icon.
It would be better if the site name "GrabTern" with its logo display on the title bar. It defines to the user on which site they are.



And i'm also interested to work on the new hero section  if someone is working on it then we can distribute it by working on the seperate components. It will easier the work load.
Thanks!

**Comment by anmode** [comment]
I have changed the issue title! if you are up for it and can do it. please go ahead. and this issue will be assigned to you

**Comment by itsmohit097** [comment]
I already did it. You just have to assign it to me and as i assigned i raised a PR and you just have to  review it and merge it. That's it.
Changes made :
Before:
![Screenshot 2023-06-07 021339](https://github.com/anmode/grabtern-frontend/assets/125040386/8a351006-a066-44f7-8bb5-fd53897bf573)

After:
![Screenshot 2023-06-08 023019](https://github.com/anmode/grabtern-frontend/assets/125040386/842f076d-cf65-4ddf-b63b-7c110e5c6180)

**Comment by itsmohit097** [comment]
@anmode any further changes you want to it. You can mention that.

**Comment by anmode** [comment]
> @anmode any further changes you want to it. You can mention that.

please for mentor page do like grabtern|mentors so optimize all pages
