### ISSUE TITLE
🚀 [Feature Request] - Make site to loader faster.

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#285]
### Is your feature request related to a problem ? Please describe. ✍️

1. Convert all images to webp or svg
2. Mentor images need to reduced ( Should be compressed while storing in database)

Find out the way. as the mentor card takes time to load.

### Additional context or screenshots
As when you see the api: ( Try in postman)
`https://grabtern-frontend-develop.onrender.com/api/mentors/mentorLists`

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
sure!

**Comment by anmode** [comment]
deassigning previous one then! As i have to follow guidelines of assigning one issue at a time

**Comment by anmode** [comment]
@vishnu9865 ?

**Comment by vishnu9865** [comment]
Sir, I am almost finished, sorry I had semester exam in the middle 😅😊😊.

**Comment by anmode** [comment]
thanks! @vishnu9865 ....
