### ISSUE TITLE
🚀 [Feature Request] - Normal CSS ----> Tailwind

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#287]
### Is your feature request related to a problem ? Please describe. ✍️

We are trying to move our application design to tailwind

### Describe briefly how you would implement this enhancement.

```bash
So target component one by one.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by vishnu9865** [comment]
@Anmol-Baranwal Sir, 
Please assign me this issue under GSSoC'23.
Thank you.
Regards,
Jeyavishnu @vishnu9865

**Comment by MAXASSASSINS** [comment]
Hey, @anmode can I work on this issue?

**Comment by Abhinavcode13** [comment]
yeah sure @MAXASSASSINS

**Comment by Abhinavcode13** [comment]
Go ahead !

**Comment by MAXASSASSINS** [comment]
@Abhinavcode13 I have one query most of the spacing is done using pixels so should I change them to rem wherever it is possible? 
For example:-  If padding is 16px then I will go with tw-p-4 rather than p-[16px]
And If the padding is 15px then I will go with tw-p-[15px].
Or should I go with the latter for all the spacing?
Thanks.

**Comment by anmode** [comment]
yeah please why not! use relative.. and please test changes your changes,,, as it should be responsive and use of relative property is good!

**Comment by MAXASSASSINS** [comment]
Hey, @anmode I am changing the tailwind.config.js file. I have added the different screen widths but for the colours part I need the list of colour names with their value so I can add them. Could you please provide it to me or should I create them on my own?

### Screen Widths List
`screens: {
        mobile: "576px",

        tablet: "768px",

        laptop: "992px",

        desktop: "1200px",
        "2xl": "1600px",
      },`
