### ISSUE TITLE
Enhancing the UI of login dropdown buttons

### ISSUE THREAD

**Issue by MAXASSASSINS** [anmode/grabtern-frontend#292]
### Description
I would like to improve the hover effect on the login dropdown buttons.

### Solutions Proposed
No response

#### Before
![screenshot-2023-06-08-20-03-26](https://github.com/anmode/grabtern-frontend/assets/97503316/a2444705-3436-41dc-9a87-6ad520177d85)

#### After
![screenshot-2023-06-08-20-10-24](https://github.com/anmode/grabtern-frontend/assets/97503316/13681eec-790e-4db8-b7b1-79cf74b8750e)

### Additional Context
Please assign me this task under GSSoC'23

### Checklist
- [x]  I have checked the existing [issues](https://github.com/anmode/grabtern-frontend/issues)
- [x]  I have read the [Contributing Guidelines](https://github.com/anmode/grabtern-frontend/blob/develop/CONTRIBUTING.md)
- [x]  I would like to be assigned this task.
- [x]  I am a GSSoC'23 contributor

**Comment by anmode** [comment]
cool@

**Comment by MAXASSASSINS** [comment]
Hey @MohitGupta121 and @anmode please review my PR. Let me know if you need any changes. 
Thanks
