### ISSUE TITLE
🚀 [Feature Request] - Adding Social Media Icons 

### ISSUE THREAD

**Issue by muskandn** [anmode/grabtern-frontend#293]
### Is your feature request related to a problem ? Please describe. ✍️

![image](https://github.com/anmode/grabtern-frontend/assets/99585352/31513ad8-32e1-47ef-83b7-4bc205c1d4e0)

Here under the picture of each member of Grabtern community ... we can add social media icons like Linkedin, Twitter, Github icons.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Swapnil-Singh-99** [comment]
Please assign this issue to me under GSSOC'23
I will be able to add social media links to each Community member

**Comment by muskandn** [comment]
@anmode please review my PR #311  . Let me know if you need any changes.
Thanks

**Comment by ankushdhavale** [comment]
Added the social icon to community member  assign me that issue

**Comment by anmode** [comment]
please please...I haven't assign as we will be removing this section. and moving to another page. sorry.
