### ISSUE TITLE
🚀 [Feature Request] - Scrollbar Removal

### ISSUE THREAD

**Issue by muskandn** [anmode/grabtern-frontend#294]
### Is your feature request related to a problem ? Please describe. ✍️

![image](https://github.com/anmode/grabtern-frontend/assets/99585352/fdd658f4-f497-42c2-92e2-c76765648bf3)

I would like to remove the horizontal and vertical scrollbar from the website. 

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
what the screen resolution? it is 100% or more than or less than.... click `ctrl+`?

**Comment by muskandn** [comment]
@anmode I was not intended to change the screen resolution... just thought of hiding the scroll bars.

**Comment by anmode** [comment]
Oh okay!

**Comment by Swapnil-Singh-99** [comment]
Please assign me this issue under GSSOC'23
I would like to work upon this

**Comment by muskandn** [comment]
@anmode please review my PR #310 . Let me know if you need any changes.
Thanks

**Comment by muskandn** [comment]
@anmode I am new to Open Source... so it would be a great help if you let me know why my PRs are getting failed... I did the changes in local space... the changes i made seemed working perfctly but it is getting failed ... according to my observation, along with writing the code for the issue i need to add some more content to the other files... please correct  me if I m wrong

**Comment by anmode** [comment]
no worries.. I'll review the pr and then can tell you why test are failing.... first of all apply your changes and push your code
