### ISSUE TITLE
🚀 [New FrontPage Issue#1] - Convert the Hero section and you have to optimize for mobile view too.

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#295]
### Is your feature request related to a problem ? Please describe. ✍️

So you have to transform the hero section.
Use Vector and apply the designing techniques if need help we are here for you.

Our theme color new is `#845ec2`
Remember background should not be pure white* See the new theme

### Describe briefly how you would implement this enhancement.

```bash
Null
```

### Additional context or screenshots

<img width="1280" alt="Screenshot 2023-06-09 at 12 33 03 AM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/31b44f3a-7e75-451f-9254-bf6d751b9552">

<img width="1278" alt="Screenshot 2023-06-09 at 12 32 42 AM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/3bab82e5-e4ab-49b3-9ddf-719c4bb831a9">

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by itsmohit097** [comment]
I understood the issue.
can you assign it to me. So, i start working on it.
@anmode

**Comment by ankushdhavale** [comment]
I understood the issue. I will modified the style.
can you assign it to me. So, I start working on it.

**Comment by anmode** [comment]
As @itsmohit097 asked first.. I have to assign him @ankushdhavale there are issue pile with this please comment on that. I'll assign you for sure.

**Comment by anmode** [comment]
for faster dev: here is demo code i showed in new theme- https://github.com/anmode/doctor @itsmohit097

**Comment by anmode** [comment]
@itsmohit097 are you working? please let me know and one more thing you create PR and continue development.

**Comment by itsmohit097** [comment]
yes i'm working on it but my end sem exams will be going from 15-26june so i'm not able to focus too much on this . I need more time to make it  happen. 

are u saying about after forking it i have to create a draft pr ?

**Comment by anmode** [comment]
okay, @itsmohit097...This issue is the main of the Home page as you know. but okkk
so yeah actually you can create PR! ( after minimal change too) but it would be a good focus on the exam right now. 
For discord server: join gssoc discord,....move to #self roles....select the grabtern... you will see a private channel will comes

**Comment by itsmohit097** [comment]
Ok, I'll raised a PR by tomorrow evening whatever the changes i h've made till now then continue working on it after my exams end
This will be okay ryt? @anmode

**Comment by anmode** [comment]
sure, it would be good!
