### ISSUE TITLE
🚀 [New Frontpage Issue#2] - Nav designing and also optimize for mobile.

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#296]
### Is your feature request related to a problem ? Please describe. ✍️

So you have to transform the hero section.
Use Vector and apply the designing techniques if need help we are here for you.

Our theme color new is `#845ec2`
Remember background should not be pure white* See the new theme

### Describe briefly how you would implement this enhancement.

```bash
Null
```

### Additional context or screenshots

<img width="1276" alt="Screenshot 2023-06-09 at 12 34 18 AM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/24875df2-4c98-4df5-8bdf-8331cb8069e9">

<img width="1279" alt="Screenshot 2023-06-09 at 12 34 05 AM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/64e997fb-5d7e-46b0-aa45-662622e1a099">

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Vidip-Ghosh** [comment]
I would like to work on this issue. Please assign this to me under GSSOC'23.

**Comment by suryanshsoni120** [comment]
I would like to contribute to this issue. Please assign it to me under GSSOC'23.

**Comment by anmode** [comment]
you both have assigned issue! please complete them.

**Comment by crocmons** [comment]
can I take this issue?

**Comment by crocmons** [comment]
Also one thing I notice when developing the dropdown card we added button over there but it's not a efficient way to do this... we have to add nextJS Links instead of buttons...

**Comment by anmode** [comment]
@crocmons sure... no no grabtern is grabtern.. We are moving to this new theme.
Reasone:
1. New Home page will look good
2. We want to remove all scss ( Mostly used in home page).
3. Want to use tailwind

**Comment by anmode** [comment]
> Also one thing I notice when developing the dropdown card we added button over there but it's not a efficient way to do this... we have to add nextJS Links instead of buttons...

I was too thinking the same.. 
We should have card component. and we can any no. of links. and this card component could be used anywhere.

**Comment by crocmons** [comment]
yeap, so that I can changed the menu options with nextJS link?

**Comment by anmode** [comment]
> yeap, so that I can changed the menu options with nextJS link?
> 

Yess! I mean afterwards..first could you design this new nav.
We will continue card then.

**Comment by crocmons** [comment]
ok great

**Comment by anmode** [comment]
for faster dev: here is demo code i showed in new theme- https://github.com/anmode/doctor

**Comment by anmode** [comment]
@crocmons after this.... you can carry on card issue. Please create that issue and I'll assign you! and I have more good level issue. Will share afterward.

**Comment by crocmons** [comment]
> @crocmons after this.... you can carry on card issue. Please create that issue and I'll assign you! and I have more good level issue. Will share afterward.

yeah, sure

**Comment by anmode** [comment]
Hi @crocmons if you haven't started working on this issue..Just to update it would be great if you can optimize the current Nav and optimize it for mobile too.

**Comment by crocmons** [comment]
yeah currently I'm working on it, tomorrow I will give you the pr..

**Comment by anmode** [comment]
thanks!!

**Comment by crocmons** [comment]
@anmode done.. but I'm not added the search functionality here because I don't know which api endpoint you gonna use in this search functionality so it's up to you.. and other rest of the things are done...also the toggle button is not working for header I don't know why is it...you can check.

**Comment by anmode** [comment]
> @anmode done.. but I'm not added the search functionality here because I don't know which api endpoint you gonna use in this search functionality so it's up to you.. and other rest of the things are done...also the toggle button is not working for header part only I don't know why is it...you can check.

That's great. Thanks i checked... could you remove that search and toggle I think we do not need that. as of now. Just comment it out.
When backend would be ready for this search we will comment it out and same for dark mode
