### ISSUE TITLE
🚀 [New FrontendPage Issue#3] - Improvise section to look good.

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#297]
### Is your feature request related to a problem ? Please describe. ✍️

Optimize this section.
Use Vector and apply the designing techniques if need help we are here for you.

Our theme color new is `#845ec2`
Remember background should not be pure white* See the new theme

### Describe briefly how you would implement this enhancement.

```bash
Null
```

### Additional context or screenshots

<img width="1193" alt="Screenshot 2023-06-09 at 12 42 25 AM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/9290827e-a8af-4a96-917e-9e64877320d0">
<img width="1218" alt="Screenshot 2023-06-09 at 12 42 38 AM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/6a7ce298-7058-4781-9fe6-45531049eef8">

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by muskandn** [comment]
@anmode I would like to work in this issue under GSSoC2023.

**Comment by suryanshsoni120** [comment]
I would like to contribute to this issue. Please assign it to me under GSSOC'23.

**Comment by anmode** [comment]
@muskandn you been assigned a issue. Please that first

**Comment by anmode** [comment]
for faster dev: here is demo code i showed in new theme- https://github.com/anmode/doctor

**Comment by anmode** [comment]
@suryanshsoni120 ?

**Comment by muskandn** [comment]
@anmode I am done with the assigned issue. 
If @suryanshsoni120 is not up for this... I want to work on it.

**Comment by suryanshsoni120** [comment]
Sorry for the delay. I was stuck in some other work. It will get completed today.

**Comment by anmode** [comment]
@suryanshsoni120 ??
