### ISSUE TITLE
🚀 [New FrontPage Issue#4] - Improve section 2

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#298]
### Is your feature request related to a problem ? Please describe. ✍️

So you have to transform the section.
Use Vector and apply the designing techniques if need help we are here for you.

Our theme color new is `#845ec2`
Remember background should not be pure white* See the new theme

### Describe briefly how you would implement this enhancement.

```bash
Null
```

### Additional context or screenshots

<img width="1197" alt="Screenshot 2023-06-09 at 12 46 21 AM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/2728c0ba-3948-465e-8eca-38fddbc38b51">
<img width="1155" alt="Screenshot 2023-06-09 at 12 46 30 AM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/2d4a0856-09da-4b11-9232-f189c6e95d54">

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by muskandn** [comment]
@anmode I would like to work on this issue under GSSoc2023.

**Comment by anmode** [comment]
assigned you a issue!

**Comment by Isha988** [comment]
@anmode I want to work on this.

**Comment by anmode** [comment]
for faster dev: here is demo code i showed in new theme- https://github.com/anmode/doctor

**Comment by Isha988** [comment]
> for faster dev: here is demo code i showed in new theme- https://github.com/anmode/doctor

Is this the new theme/design of the website? Actually, It is looking awesome.

**Comment by anmode** [comment]
> > for faster dev: here is demo code i showed in new theme- https://github.com/anmode/doctor
> 
> Is this the new theme/design of the website? Actually, It is looking awesome.

yess new theme... actually we trying to move our home page in this theme

**Comment by Isha988** [comment]
That's great

**Comment by Abhinavcode13** [comment]
please give a update of your work @Isha988

**Comment by Isha988** [comment]
@Abhinavcode13 please go through the discussion made on the pr linked to this issue.
@anmode Currently I am having exams that's why I am a bit inactive in contribution and will start contributing from Monday.
