### ISSUE TITLE
🚀 [Need Testimonial Section] - Implement Testimonial 

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#300]
### Is your feature request related to a problem ? Please describe. ✍️

attached the design

### Describe briefly how you would implement this enhancement.

```bash
Null
```
<img width="1253" alt="Screenshot 2023-06-09 at 12 50 37 AM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/71584cfc-9221-48cf-aa25-48ccf8203569">

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by muskandn** [comment]
@anmode I would like to work on this testimonial feature under GSSoC2023.

**Comment by muskandn** [comment]
@anmode  Please let me know in which part of the website I have to add the testimonial section.

**Comment by anmode** [comment]
above the grabtern community section! and please optimize for mobile too

**Comment by anmode** [comment]
for faster dev: here is demo code i showed in new theme- https://github.com/anmode/doctor

**Comment by muskandn** [comment]
ohkay sure... I m on it @anmode
