### ISSUE TITLE
🚀 [New Footer] - Footer design and optimization

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#301]
### Is your feature request related to a problem ? Please describe. ✍️

Attached the design
Use Vector and apply the designing techniques if need help we are here for you.

Our theme color new is `#845ec2`
Remember background should not be pure white* See the new theme

### Describe briefly how you would implement this enhancement.

```bash
nil
```

### Additional context or screenshots

<img width="1280" alt="Screenshot 2023-06-09 at 12 47 48 AM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/554b1c6c-554d-455b-b06a-00f915921cfa">
<img width="1276" alt="Screenshot 2023-06-09 at 12 48 11 AM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/98473e2a-ce8e-4183-af53-052946ed38e3">

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by muskandn** [comment]
@anmode I would like to work on this issue.

**Comment by Vidip-Ghosh** [comment]
I would like to work on this issue

**Comment by suryanshsoni120** [comment]
I would like to contribute to this issue. Please assign it to me under GSSOC'23.

**Comment by anmode** [comment]
@suryanshsoni120 you have been assigned..
assigning you vidip.. Please try to use tailwind!

**Comment by anmode** [comment]
for faster dev: here is demo code i showed in new theme- https://github.com/anmode/doctor

**Comment by ShreyaDhiman24** [comment]
I want to work on this issue under GSSoC'23
