### ISSUE TITLE
🚀 feat: password visibility toggle button for user and mentor!

### ISSUE THREAD

**Issue by SINJINI-G** [anmode/grabtern-frontend#303]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. I will add the toggle button in password section of User login
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
cool!

**Comment by Abhinavcode13** [comment]
@SINJINI-G update please ?

**Comment by SINJINI-G** [comment]
> @SINJINI-G update please ?

Almost done. Will make a PR soon.
