### ISSUE TITLE
🚀 [Feature Request] - Grabtern NEW LOGO 

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#307]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Pratipada013** [comment]
need to add new logo right?
will you please elaborate these issue?

**Comment by anmode** [comment]
yes! We are open to a new logo! we will add that logo to our website header......it would be great contribution

**Comment by Abhinavcode13** [comment]
@anmode im taking up this issue?

**Comment by anmode** [comment]
@Abhinavcode13 Up for this?? or 404

**Comment by Abhinavcode13** [comment]
![image](https://github.com/anmode/grabtern-frontend/assets/126642111/4e3cc7a6-1e6c-4f89-bd31-2dffda171ca5)

**Comment by Abhinavcode13** [comment]
![image](https://github.com/anmode/grabtern-frontend/assets/126642111/870c533b-7278-4923-9b02-506a2d067bcf)

@anmode

**Comment by anmode** [comment]
Naah! Logo design krna pdega scratch se... i think whi work krega

**Comment by Abhinavcode13** [comment]
yeah go ahead @Vidip-Ghosh

**Comment by Vidip-Ghosh** [comment]
https://www.canva.com/design/DAFlzVM_kfs/FJmsajDd_Kv2PgN0VF5UzQ/edit?utm_content=DAFlzVM_kfs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
Proposed design of the logo

**Comment by anmode** [comment]
> does not look that great @Vidip-Ghosh , you can improve it
> 
> what do you say @anmode ?

Current logo se toh better h! Btw yeah there is a scope for improvement....Whi best ke liye we have to try hard.

**Comment by anmode** [comment]
Actually, if you go for professional logo..they do not contain the name... Logo reveals the idea of the company.
Best example- apple
