### ISSUE TITLE
🚀 [Logic In frontend] - Use Overlay On Mentor Registration form

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#316]
### Is your feature request related to a problem ? Please describe. ✍️

We have overlay JS.
You have to use it on the Registration form, After google sign in we should come back on Registration with some details should be filled from that data we get from google. as we are currently doing. 

### Describe briefly how you would implement this enhancement.

```bash
All things are present you have to find a way to connect
```

### Additional context or screenshots

https://user-images.githubusercontent.com/88332977/243345094-33b4441a-1a00-4dc4-9de7-ab2f69a20350.png

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
@Anmol-Baranwal wanna try?

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal wanna try?

I have my semester exams, so it will take 4-5 days to complete this. I would suggest keeping it open and i will ask u to assign me whenever i am free to work on this.

**Comment by AmanJain18** [comment]
@anmode What is this for ?

**Comment by anmode** [comment]
see the pic attached

**Comment by vishnu9865** [comment]
@anmode, I would like to work on this issue under GSSoC'23.
Thank you in advance. 🚀🚀👍🏽😊
Regards,
Jeyavishnu @vishnu9865

**Comment by anmode** [comment]
okk @vishnu9865
