### ISSUE TITLE
🚀 [Feature Request] - Improve Mentor page. and optimize for Mobile view

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#319]
### Is your feature request related to a problem ? Please describe. ✍️

The UI of the mentor page is not good.
here is the page - `pages/mentor/[mentorUsername].page.js`

Our theme color new is `#845ec2`
Remember background should not be pure white* See the new theme
https://doctor-ruby.vercel.app/. ( keep the light mode)

### Describe briefly how you would implement this enhancement.

```bash
Use tailwind...
```

### Additional context or screenshots

Ideas could be taken from any profile ..how profile looks like.. as this is mentor profile

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by vishnu9865** [comment]
@anmode Sir, I would like to work on this issue under GSSoC'23.
Thank you in advance.
Regards,
Jeyavishnu @vishnu9865

**Comment by anmode** [comment]
Sure, Please create a design first. can be figma. i will also look at some design and provide you, So you can kick start dev

**Comment by vishnu9865** [comment]
@anmode Sir,
Please do feel free to ask for changes to this design if required.
regards,
Jeyavishnu @vishnu9865 
Figma File Link: https://www.figma.com/file/mcGBmU9AwU7KQg7NrH00cO/Grabtern-Mentor-Page?type=design&node-id=0%3A1&t=UcvQFmVpRwmFiGd4-1
![image](https://github.com/anmode/grabtern-frontend/assets/91585213/9a93736e-631c-4fd1-ac9d-846d3ee9eb83)

**Comment by anmode** [comment]
It's cool. @Illaf @Abhinavcode13 @MohitGupta121 any suggestions?

**Comment by anmode** [comment]
Some recommadation:
1. Our theme color ( see in issue description)
2. Space not utilized effectively 
3. Mobile optimized! ( This is imp. how it looks in mobile view)

btw great work @vishnu9865 seeing to get coded now!

**Comment by MohitGupta121** [comment]
@anmode It's really awesome from my side final.

**Comment by vishnu9865** [comment]
@anmode Sir,
Thank you for the Suggestion. I changed the Theme Colour, I didn't use all the space due to little content to show.
Figma File: https://www.figma.com/file/mcGBmU9AwU7KQg7NrH00cO/Grabtern-Mentor-Page?type=design&node-id=0%3A1&t=UcvQFmVpRwmFiGd4-1

**Comment by anmode** [comment]
Good! @vishnu9865 let's start coding now!. Please ping this figma in PR( when you create) too. make it public.

**Comment by Illaf** [comment]
@anmode yes it's looking good👍
