### ISSUE TITLE
🚀 [Feature Request] - Improving the share profile feature

### ISSUE THREAD

**Issue by kailashchoudhary11** [anmode/grabtern-frontend#321]
### Is your feature request related to a problem ? Please describe. ✍️

Currently the message displayed after copying the text is like this 
![image](https://github.com/anmode/grabtern-frontend/assets/75559082/26476fa3-3597-4856-a904-e0f34c3374b3)
This can be improved and we can change it to somewhat like this 
![image](https://github.com/anmode/grabtern-frontend/assets/75559082/ab3c0b04-547c-4629-9a61-d2bdaed7900e)
![image](https://github.com/anmode/grabtern-frontend/assets/75559082/c3bd6d91-9f34-4675-b6f8-8356716f70f4)

In addition if you want we can provide share with option by clicking on which the user will be provided with various social media options to share the link on.

### Describe briefly how you would implement this enhancement.

```bash
I would like to work on this.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Hi, thanks.
Our theme color new is `#845ec2`
Remember background should not be pure white

We are trying to modify the mentor page...

**Comment by Abhinavcode13** [comment]
@kailashchoudhary11 update please ?

**Comment by kailashchoudhary11** [comment]
> @kailashchoudhary11 update please ?

I've added the icons for social medias but what I'm wondering from where should I get copy link icon 🥲

**Comment by Abhinavcode13** [comment]
Internet pe dekho ser @kailashchoudhary11
