### ISSUE TITLE
🚀 [Feature Request] - Creating Side Navbar for Mentor Dashboard

### ISSUE THREAD

**Issue by Isha988** [anmode/grabtern-frontend#322]
### Is your feature request related to a problem ? Please describe. ✍️

Create Sidebar  for mentor dashboard page. 

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 Create dashboard Page
2. Step 2 Adding Side bar component
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
@Isha988 Any update?

**Comment by Isha988** [comment]
@anmode I was having exams this whole week even today was my last exam that's why I was unable to work on it will be completing it soon approximately till Tuesday.

**Comment by anmode** [comment]
> @anmode I was having exams this whole week even today was my last exam that's why I was unable to work on it will be completing it soon approximately till Tuesday.

Ohh i wasn't aware.. okay!.

**Comment by Isha988** [comment]
A issue #530 has been created which serve the same purpose so closing this issue.

**Comment by anmode** [comment]
> A issue #530 has been created which serve the same purpose so closing this issue.

Oh no! I didn't noticed....forgot..

**Comment by anmode** [comment]
Actually there is issue for nav bar behavior after login?
If you are up for this issue can create pR.

**Comment by Isha988** [comment]
> > A issue #530 has been created which serve the same purpose so closing this issue.
> 
> Oh no! I didn't noticed....forgot..

No problem, even I forgot about it, by chance I saw it.

**Comment by Isha988** [comment]
> Actually there is issue for nav bar behavior after login? If you are up for this issue can create pR.

Okay, but please explain it in little detail.

**Comment by anmode** [comment]
> > Actually there is issue for nav bar behavior after login? If you are up for this issue can create pR.
> 
> Okay, but please explain it in little detail.

actually, After login, the nav should change like as the signup button should be hidden and the sign-in link too, and A profile pic should come. So user can get acknowledged that he/she logged in and on clicking on profile a card should appear with option dashboard and logout button ( there is already a card component)

**Comment by Isha988** [comment]
> actually, After login, the nav should change like as the signup button should be hidden and the sign-in link too, and A profile pic should come. So user can get acknowledged that he/she logged in and on clicking on profile a card should appear with option dashboard and logout button ( there is already a card component)

Okay, after this issue, I am willing to work on removing unnecessary css files (if project demands), I am very excited for the latter one.

**Comment by anmode** [comment]
> > actually, After login, the nav should change like as the signup button should be hidden and the sign-in link too, and A profile pic should come. So user can get acknowledged that he/she logged in and on clicking on profile a card should appear with option dashboard and logout button ( there is already a card component)
> 
> Okay, after this issue, I am willing to work on removing unnecessary css files (if project demands), I am very excited for the latter one.

Sure, cool. Yeah we need to remove those css files.

**Comment by anmode** [comment]
> > > actually, After login, the nav should change like as the signup button should be hidden and the sign-in link too, and A profile pic should come. So user can get acknowledged that he/she logged in and on clicking on profile a card should appear with option dashboard and logout button ( there is already a card component)
> > 
> > Okay, after this issue, I am willing to work on removing unnecessary css files (if project demands), I am very excited for the latter one.
> 
> Sure, cool. Yeah we need to remove those css files.

@Isha988 Actually I was thinking to launch new website till Saturday...
Please could you complete this nav task soon...
You just have to make nav after logging effect... remember to take in account two boolean `isMentorLoggedIn` nd `isUserLoggedIn`.
One small change in Hero section...
If `isMentorLoggedIn = True `....then `Be a Mentor` should changed to `dashboard`

**Comment by Isha988** [comment]
> @Isha988 Actually I was thinking to launch new website till Saturday...
> Please could you complete this nav task soon...

I will do it by tomorrow morning.
I hope this works for you.
