### ISSUE TITLE
🚀 [Feature Request] - Dark Mode Button

### ISSUE THREAD

**Issue by Soumyajit2825** [anmode/grabtern-frontend#327]
### Is your feature request related to a problem ? Please describe. ✍️

I want to add a dark mode button in the navbar which will toggle the theme into dark mode and light mode.

### Describe briefly how you would implement this enhancement.

```bash
First I will see the codebase and will understand it
Then I will try to create a dark mode button
And then I will add it to the website creating a new branch in my local 
I will then send a PR so that maintainers can review my code
```

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Pleas check issue and PR : https://github.com/anmode/grabtern-frontend/issues/154 And if author agrees you can work. But first of all see the convo in issue nd PR too. thanks
