### ISSUE TITLE
🐞 [BUG] - Site Overflow

### ISSUE THREAD

**Issue by ShreyaDhiman24** [anmode/grabtern-frontend#332]
### Description

Website is not having its overflow hidden.

### Current behaviour

Overflow is not hidden.

### Expected behaviour

It should be hidden.

### Reproduction steps

```bash
..
```

### Screenshots

[Screencast from 14-06-23 11:50:25 PM IST.webm](https://github.com/anmode/grabtern-frontend/assets/98320971/5bf32a88-3a06-45f5-a247-19120e18130e)

### Browsers

Chrome

### OS

Linux

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
yeah! On mentor page.... please fix it!
