### ISSUE TITLE
🚀 [Feature Request] - Footer Optimization 

### ISSUE THREAD

**Issue by ShreyaDhiman24** [anmode/grabtern-frontend#333]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 Footer is too large having large space.
2. Step 2 We can optimise its size as as well as we can add a line to separate copyright with above part of footer.
```

### Additional context or screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/98320971/450b2281-16f2-4972-b324-08e32ff294ac)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Abhinavcode13** [comment]
@ShreyaDhiman24 footer is already ready , you can work on other issues !!
