### ISSUE TITLE
🚀 [Feature Request] - Scroll to Top button

### ISSUE THREAD

**Issue by kaashikaagrawal** [anmode/grabtern-frontend#334]
### Is your feature request related to a problem ? Please describe. ✍️

Currently there is no way for the user to be taken to the top of the landing page once they have scrolled some way down.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Constructing a good looking button that will be placed near the scroll bar
2. Making sure it matches the theme of the webpage.
3. Coding for it to take the user to the top of the page

Please assign me this issue
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by kaashikaagrawal** [comment]
@anmode following up

**Comment by anmode** [comment]
ok

**Comment by kaashikaagrawal** [comment]
@anmode is it not possible to merge?
