### ISSUE TITLE
🚀 [Feature Request] - Better buttons on the navbar

### ISSUE THREAD

**Issue by kaashikaagrawal** [anmode/grabtern-frontend#335]
### Is your feature request related to a problem ? Please describe. ✍️

Only the login button changes color once the mouse is hovered over it on the navbar. Home, Mentors and Contact do not show the same behavior.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Improve the code for the other buttons to behave the same as the login button on the navbar
```

### Additional context or screenshots

Additional context

<img width="255" alt="image" src="https://github.com/anmode/grabtern-frontend/assets/97745349/8ed488a2-658f-4754-bea7-9ce36b9c9055">

Please assign me this issue

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Actually login have dropdown card..that's why we make it unique

**Comment by kaashikaagrawal** [comment]
ok I will make the other buttons change to a different color. But I can make the buttons more attractive.

**Comment by anmode** [comment]
could you please look at another improvement? Because I do not think by any chance there would be improvement. Unless a figma design presented
