### ISSUE TITLE
🐞 [BUG] - Mentor card Needs to fixed

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#338]
### Description

What can be done slice the info...
Keep the all card of same size with same amount of info ( one liner intern status and two or there liner current status

### Current behaviour

Bug

### Expected behaviour

Should be fixed

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

<img width="416" alt="Screenshot 2023-06-15 at 11 51 07 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/a3846384-cb96-4f30-bf30-e6d1e30733ea">

### Browsers

Chrome

### OS

Mac

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Illaf** [comment]
@anmode should i add a read more button in the card provided in the screenshot?
