### ISSUE TITLE
Profile image upload on mentor form registration not working properly

### ISSUE THREAD

**Issue by MAXASSASSINS** [anmode/grabtern-frontend#342]
### List of bugs:-

- #### Taking text files as valid input

https://github.com/anmode/grabtern-frontend/assets/97503316/429e62b1-4a91-4ba7-9b36-c68128ef0a5d

- ####  Getting error if nothing is selected after the first selection of the file. For clarity, please take a look at the video below.

https://github.com/anmode/grabtern-frontend/assets/97503316/6cac4fb1-bf6d-41c4-ab57-289ed2cfdd6d

### Current behaviour

Same as description

### Only images should be accepted
https://github.com/anmode/grabtern-frontend/assets/97503316/743a4fb2-7ce1-473d-95cf-6de5245bed4e

### For Bug 2: Please see the below video
https://github.com/anmode/grabtern-frontend/assets/97503316/60fd91fb-5d0a-4629-b3ba-996a68338615

### Reproduction steps

```bash
1. Go to the home page
2. Click on the login button
3. Choose mentor
4. Now at the bottom of the mentor login page click on "Register here".
5. Now do the same as I have done in the description videos.
```

### Screenshots

Everything is provided in the description.

### Logs

```bash
No logs
```

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS

Windows, Linux, Mac

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
That would be cool if you can optimize it. there are many new packages for that....just explore and find out..
As far as I know, many image uploads give the option to resize or zoom. 
We should compress image too!
