### ISSUE TITLE
🚀 [Feature Request] - Remove unnecessary caption to login card

### ISSUE THREAD

**Issue by MisterMickey** [anmode/grabtern-frontend#347]
### Is your feature request related to a problem ? Please describe. ✍️

There is already a placeholder in email input. There is no need for caption it should be removed.
There are duplicate labels, Email-Email, Password-Password, Not making much sense.
 
![Screenshot from 2023-06-17 00-32-18](https://github.com/anmode/grabtern-frontend/assets/93720428/e44166b3-c131-4935-be02-67a598bfa5c0)

### Describe briefly how you would implement this enhancement.

```bash
I'll simply remove the E-mail and Password caption and there will be only placeholders.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by VijayalakshmiGanesh** [comment]
Hi, I would like to work on this issue under GSSOC'23 label please.

**Comment by amanbairagi30** [comment]
I would like to contribute to this and I will remove captions for email and password inputs .
