### ISSUE TITLE
📚 [Documentation / WorkFlow] - Adding dependabot.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [anmode/grabtern-frontend#349]
### Description ✍️

*We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.*

@anmode please assign me this issue under gssoc'23.

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Abhinavcode13** [comment]
not required
