### ISSUE TITLE
📚 [Documentation / WorkFlow] - Adding auto_comment.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [anmode/grabtern-frontend#350]
### Description ✍️

*We need to add an auto-comment.yml that will automatically welcome, greet and provide necessary information to the contributors when they create new issues, PR, and when these will get assigned or merged respectively. This will promote motivation and performance*

@anmode Please assign me this issue under gssoc'23

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Abhinavcode13** [comment]
Not needed thanks @Anshika-Jain02
