### ISSUE TITLE
Redesigning Login page/box

### ISSUE THREAD

**Issue by Yoogiitaa** [anmode/grabtern-frontend#352]
### Is your feature request related to a problem ? Please describe. ✍️

The login box can be made with better UI. 
the current design is not matching with the other pages.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. we can design the new UI 
2. and change it in code.
```

### Additional context or screenshots

@Abhinavcode13 please assign this issue to me under gssoc'23

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
can you create one for this theme? just keep it other page separate do not remove the current login and registration page.
If up so create a sign-in and sign-up page. I have attached the new theme. Thanks

**Comment by Yoogiitaa** [comment]
yes I can do this. Assign me this.

**Comment by anmode** [comment]
@Yoogiitaa ?

**Comment by Yoogiitaa** [comment]
hey, i am working on it. got busy with college campus process. 
it will be done before 23.
