### ISSUE TITLE
🐞 [BUG] - Add Appropriate Route to "View More Hackathons" Button and Update Hackathons Section

### ISSUE THREAD

**Issue by Nishitbaria** [anmode/grabtern-frontend#353]
### Description

The "View More Hackathons" button in the hackathons section of the website currently reloads the page upon clicking, instead of navigating to a designated page or section displaying additional hackathons. This results in a poor user experience and does not provide users with the expected functionality to explore more hackathons. Additionally, the hackathons section needs to be updated with appropriate hackathon content to ensure accurate and up-to-date information.

Please assign me this issue,I will fix routes and add relevant hackthons in hackathon section 

### Current behaviour

Clicking the "View More Hackathons" button reloads the page, providing no additional hackathon content or navigation.

### Expected behaviour

Upon clicking the "View More Hackathons" button, users should be directed to a designated page or section that displays additional hackathons, allowing them to explore more opportunities. The hackathons section should also be regularly updated with appropriate hackathon content to reflect the latest and relevant information.

### Reproduction steps

```bash
1. Visit the website's homepage.
2. Locate the hackathons section.
3. Click the "View More Hackathons" button.
```

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
ok
