### ISSUE TITLE
🚀 [Feature Request] - New Mentor card design

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#364]
### Is your feature request related to a problem ? Please describe. ✍️

Create New Card design
 You can remove current status

Just card should reflect mentor name and social handles with #tag For gssoc who cracked gssoc.

### Describe briefly how you would implement this enhancement.

```bash
Null
```

### Additional context or screenshots

<img width="438" alt="Screenshot 2023-06-18 at 5 55 15 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/fbb2ca0f-b6a0-48a6-bafa-f6f38311fb33">

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Vidip-Ghosh** [comment]
I would like to work on this issue
