### ISSUE TITLE
🚀 [Feature Request] - Need improvement in Mentor Page

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#365]
### Is your feature request related to a problem ? Please describe. ✍️

As we fetch image from google ID: so using the bigger size as mentor pic is not a good choice
So you can redesign the card and optimize it for mobile too
keep circular section in place of current design

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

<img width="1128" alt="Screenshot 2023-06-18 at 6 23 59 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/9d28a716-1c7c-4246-a864-c94caf8bfe54">

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by abhi03ruchi** [comment]
I would like to work on the issue, plz assign this task to me under gssoc'23.

**Comment by anmode** [comment]
This is something urgent @abhi03ruchi!  please I hope to get PR soon. Actually, otherwise, I will say to team to resolve it.

**Comment by abhi03ruchi** [comment]
I have created a pr , plz review and merge .
