### ISSUE TITLE
🚀 [Feature Request] - Improvement of grabintern community seciton

### ISSUE THREAD

**Issue by Bhuvanchand26** [anmode/grabtern-frontend#367]
### Is your feature request related to a problem ? Please describe. ✍️

I've gone through the section of grabintern community on the home page, I found that the total grabintern community section has to be modified a bit. The arrow used to scroll is stuck to the sides of the page and make UI better of grabintern community.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. move those arrows from the walls so that it can be visible
2. Change the UI part of grabintern community according to the page's UI
```

### Additional context or screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/131843589/1ac45563-3247-419d-bfb1-9b2d357baaa6)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Please remove this component from here and move this to other page! and keep that link in footer thanks

**Comment by Pushti18** [comment]
Also when we click on the  Community Members there is hyperlink but loading the same page that needs to be change, we can keep it like the details of the person will be displayed with the contact details.

**Comment by anmode** [comment]
> Also when we click on the  Community Members there is hyperlink but loading the same page that needs to be change, we can keep it like the details of the person will be displayed with the contact details.

Yeah, nice catch.
So new page would contain social handles of the all of us...
This community page should be fetch contributor too.

**Comment by Bhuvanchand26** [comment]
Hey @anmode, what I've understood is that you want to move this part from this page to a new page. In there on each card, community member's socials also be attached, and down below the page all the contributor's list also be included.

@Pushti18 THANKS for the improvments.

**Comment by anmode** [comment]
yes!

**Comment by anmode** [comment]
so sorry I did not noticed your message could you please ping me on discord
