### ISSUE TITLE
🐞 [BUG] - In the mentor section button is not properly visible

### ISSUE THREAD

**Issue by SubhamB2003** [anmode/grabtern-frontend#373]
### Description

In the mentor section, the last card button was not visible properly.

### Current behaviour

You can see here

![image](https://github.com/anmode/grabtern-frontend/assets/94003231/934420b1-2d21-4740-a934-aab404fa9f41)

### Expected behaviour

![image](https://github.com/anmode/grabtern-frontend/assets/94003231/83c82317-55b9-41b1-a465-b9e806f6848f)

### Reproduction steps

```bash
Scroll to bottom then you can see the issue.
```

### Screenshots

![DESCRIPTION](LINK.png)

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
actually we have ongoing issue : https://github.com/anmode/grabtern-frontend/issues/364 We will fix it there.

**Comment by SubhamB2003** [comment]
> actually we have ongoing issue : #364 We will fix it there.

Hey, so can I start the work for your mentioned issue? I am really interested to work on it.

**Comment by anmode** [comment]
you ask from the assigned one! if he agrees..but i advice you to look out other improvments
Hint: Mobile mode needs many improvments

**Comment by SubhamB2003** [comment]
> Assigned to you @SubhamB2003

Hey, can I start work on it or move to another issue?
