### ISSUE TITLE
🐞 [BUG] - Issue with Contact Us page

### ISSUE THREAD

**Issue by swapn652** [anmode/grabtern-frontend#375]
### Description

Without entering any content into the input boxes and clicking on the "Send" button, an alert message is displayed indicating that the notification has been sent.

### Current behaviour

Without entering any content into the input boxes and clicking on the "Send" button, an alert message is displayed indicating that the notification has been sent.

### Expected behaviour

I want to make it such that it would required to fill the input boxes and if user fails to do so, he will get a warning alert.

### Reproduction steps

```bash
1. Go to 'Contact Us'
2. Click on 'Send', without typing anything in the input boxes.
4. See error
```

### Screenshots

<img width="966" alt="Screenshot 2023-06-19 at 7 29 24 PM" src="https://github.com/anmode/grabtern-frontend/assets/70851202/5e9cb659-e2bc-4946-9e08-14dde3a0423a">

### Browsers

Chrome

### OS

Mac

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Abhinavcode13** [comment]
Already assigned to someone @swapn652 thanks
