### ISSUE TITLE
🚀 [Feature Request] - Adding Search Button

### ISSUE THREAD

**Issue by ShreyaDhiman24** [anmode/grabtern-frontend#378]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement : Search button in mentor page is not there.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 Adding search button
```

### Additional context or screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/98320971/1d2c5a46-8b2e-420f-a8c2-ab1e312a297f)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
sorry! but not needed:
- why to put button if enter button can do that

**Comment by ShreyaDhiman24** [comment]
NoI want to say like this.. @anmode 
![image](https://github.com/anmode/grabtern-frontend/assets/98320971/73f4a147-4d5d-495f-bbe2-e4bfff617f07)
