### ISSUE TITLE
🚀 [Feature Request] - Adding Footer to Mentors page also

### ISSUE THREAD

**Issue by ShreyaDhiman24** [anmode/grabtern-frontend#379]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement: Footer not available in Mentors page 

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 Footer not available in Mentors page 
2. Step 2 Adding it there.
```

### Additional context or screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/98320971/d9f5428f-89a7-43f3-b17d-24066599364c)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Actually, that page will be infinite cards and a footer is not needed. Thanks
