### ISSUE TITLE
🚀 [Feature Request] - Hover Effect to home page Cards

### ISSUE THREAD

**Issue by ShreyaDhiman24** [anmode/grabtern-frontend#381]
### Is your feature request related to a problem ? Please describe. ✍️

Hover effect to home page cards to make them alive.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 To make website home page more alive adding effects to the cards.
```

### Additional context or screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/98320971/dc1385fb-ebb3-4a64-b492-9e7caf979d3a)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
No no please this is not needed.. thanks
