### ISSUE TITLE
🚀 [Feature Request] - 3d movement of photo to make it animated.

### ISSUE THREAD

**Issue by ShreyaDhiman24** [anmode/grabtern-frontend#382]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement: 3d movement

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 adding 3D horizontal movement to image with proper styling.
```

### Additional context or screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/98320971/a830756e-db27-4d0e-b0f4-57928a5d0ebe)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
yeah! you can improve this section if you agree

**Comment by ShreyaDhiman24** [comment]
okay
