### ISSUE TITLE
🚀 [Feature Request] - Show password in Login/Signup

### ISSUE THREAD

**Issue by VijayalakshmiGanesh** [anmode/grabtern-frontend#386]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement. Show password is necessary for the end user to check if they entered it correctly.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Add show password icon button in login/Signup form
```

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by VijayalakshmiGanesh** [comment]
I would like to work on this issue under GSSOC'23 label please. Kindly assign it to me

**Comment by anmode** [comment]
it is good

**Comment by VijayalakshmiGanesh** [comment]
Hi, For some reason not able to run the local server. Could you please help me with this
![image](https://github.com/anmode/grabtern-frontend/assets/104077094/a438224a-53c6-466c-a2c1-1ba68ece83b6)

**Comment by anmode** [comment]
so sorry I did not notice your comment.. will be creating more nice issues
