### ISSUE TITLE
🚀 [Feature Request] - footer section in mentor

### ISSUE THREAD

**Issue by mandliyarajendra11** [anmode/grabtern-frontend#387]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement  - mentor page doest have a footer section

### Describe briefly how you would implement this enhancement.

```bash
i can add footer in mentor page
```

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Due to infinite cards in future we do not footer there please look out other issues

**Comment by mandliyarajendra11** [comment]
@anmode for infinite cards we can add expand more button or pagination and search box too ,
and there is problem to add footer
