### ISSUE TITLE
🐞 [BUG] - Different photo heights in the 'Explore top hackathons' section

### ISSUE THREAD

**Issue by Soumyajit2825** [anmode/grabtern-frontend#390]
### Description

In the section 'Explore top hackathons' there are images with different height and width 
I want to fix it

### Current behaviour

'Solve for tomorrow' and 'Google girls's hackathon' is having different image height,width from the other elements

### Expected behaviour

All have to be with the same height and width

### Reproduction steps

```bash
1. Go to 'Explore Top Hackathons'
2. Click on 'Google Girl's Hackathon'
3. Click on 'Solve for tomorrow'
4. You can see error
```

### Screenshots

![Screenshot 2023-06-20 184312](https://github.com/anmode/grabtern-frontend/assets/100519291/93a6822f-9d34-4b20-b64e-05b67ea220a2)

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
there is pR for hackathon section! it would be great if you seek any feature request

**Comment by Soumyajit2825** [comment]
Can you provide me the PR link? @anmode

**Comment by anmode** [comment]
https://github.com/anmode/grabtern-frontend/pull/391
