### ISSUE TITLE
🐞 [BUG] - Contact form without any validation alert sent message

### ISSUE THREAD

**Issue by Geeta259** [anmode/grabtern-frontend#393]
### Description

After submit the contact form not validate it's field even empty field submit and alert message shown sent
@anmode  Want to contribute on this project by resolving this issue validate empty fields through JS add some border outside the fields .

### Current behaviour

Empty field submitted  and showing alert sent
![Screenshot (390)](https://github.com/anmode/grabtern-frontend/assets/75520947/60b056f0-e500-4c1a-8d5c-6900557ec45d)

### Expected behaviour

.

### Reproduction steps

```bash
.
```

### Screenshots

![DESCRIPTION](LINK.png)

### Logs

```bash
.
```

### Browsers

Microsoft Edge

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Shubham185y** [comment]
i can fix it assign this to me

**Comment by anmode** [comment]
@Shubham185y could you look out other issue? if author agree I'll assign you.

**Comment by Geeta259** [comment]
@anmode I am working on this issue.!!
