### ISSUE TITLE
Add the CodeQL workflow 

### ISSUE THREAD

**Issue by metabiswadeep** [anmode/grabtern-frontend#394]
### Is your feature request related to a problem ? Please describe. ✍️

Add the codeql analysis workflow to be run on every push and pull request to prevent any security vulnerabilities in the codebase.

I would like to work on this as a part of GSSoC 23.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Create a file codeql.yml in the .github/workflows folder 
2. Code the implementation of the codeql GitHub action
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
sure!
