### ISSUE TITLE
🚀 [Feature Request] - UI Improvement on mentor booking page

### ISSUE THREAD

**Issue by SubhamB2003** [anmode/grabtern-frontend#396]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

Hey, the current this page ui is not looking good same as the mobile view. So, I want to improve it. Can you please assign it to me under GSSOC'23?
![image](https://github.com/anmode/grabtern-frontend/assets/94003231/3d0b0acc-3bc1-4dff-8609-f35e0e1865e9)

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by SubhamB2003** [comment]
> Start working @SubhamB2003

Hey, I created the PR you can now review it

**Comment by anmode** [comment]
@SubhamB2003 there is already a pR ongoing.. sorry could you look out other feature request, there can be many features;
see topemate , mentro.tech for ideas

**Comment by anmode** [comment]
@SubhamB2003 you can see new UI now... if you think you can provide a better UI. I will consider after figma design if you agree
