### ISSUE TITLE
🚀 [Feature Request] - Redesign the contact form and page

### ISSUE THREAD

**Issue by ePSA-eJya** [anmode/grabtern-frontend#401]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

![image](https://github.com/anmode/grabtern-frontend/assets/120899038/7cd22fd3-ebb8-4d51-acbc-7c50727052c3)

i an gssoc23 contributor please assign this issue to me @anmode 

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Following our new theme and color code!

**Comment by ePSA-eJya** [comment]
thanks would complete in a week

**Comment by ShreyaDhiman24** [comment]
@anmode I guess you have already assigned this work #380.

**Comment by ePSA-eJya** [comment]
> @anmode I guess you have already assigned this work #380.

You have been asked to add hover effects

**Comment by anmode** [comment]
Oh yess!! @ePSA-eJya No worries... i have more issues in my mind. or you can suggest too
see look at topemate.io and metro.tech

**Comment by anmode** [comment]
https://github.com/anmode/grabtern-frontend/issues/403 @ePSA-eJya ? wanna takeover

**Comment by ePSA-eJya** [comment]
> topemate.io

yeah ok

**Comment by ePSA-eJya** [comment]
> Oh yess!! @ePSA-eJya No worries... i have more issues in my mind. or you can suggest too see look at topemate.io and metro.tech

these links arent working i guess

**Comment by anmode** [comment]
> > Oh yess!! @ePSA-eJya No worries... i have more issues in my mind. or you can suggest too see look at topemate.io and metro.tech
> 
> these links arent working i guess
These are platform similar to us-
www.topmate.io and www.mentor.tech

**Comment by anmode** [comment]
please comment there @ePSA-eJya !!
