### ISSUE TITLE
🐞 [Feature] - New UI Testimonial Section

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#403]
### Description

The testimonial section does not look good. Need new UI

### Current behaviour

distorted

### Expected behaviour

Just make changes which i showed in snippet and fix the footer

### Reproduction steps

```bash
null
```

### Browsers

Chrome

### OS

Mac

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Pushti18** [comment]
done

**Comment by anmode** [comment]
PR??

**Comment by ePSA-eJya** [comment]
Please assign this issue to me @anmode

**Comment by anmode** [comment]
updated issue! actually the author who created footer solved that! but no worries you have new Issue

**Comment by ePSA-eJya** [comment]
yeah alright.....would complete in aweek

**Comment by ePSA-eJya** [comment]
can you share ss of which testimonial section you are reffering to... @anmode

**Comment by ePSA-eJya** [comment]
> can you share ss of which testimonial section you are reffering to... @anmode

@anmode if you could help with this

**Comment by anmode** [comment]
Oh testimonial which are on home page! The card is not fully optimize and i think you can redesign testimonial template or you can take from internet too

**Comment by ePSA-eJya** [comment]
![image](https://github.com/anmode/grabtern-frontend/assets/120899038/bab8e4ba-8f9f-46ca-9345-7ca76f54c408)
 this one?

> Oh sorry, So testimonials are on the home page! The card is not fully optimized and i think you can redesign testimonial template or you can take from internet too

**Comment by anmode** [comment]
No no! Testimonials scroll down little.
see in light mode: https://grabtern-new-frontend.vercel.app/
please replicate this UI and if you want code you can take it from here-https://github.com/anmode/grabtern-NewFrontend

**Comment by ePSA-eJya** [comment]
yeah got it

**Comment by ePSA-eJya** [comment]
@anmode 
![image](https://github.com/anmode/grabtern-frontend/assets/120899038/0aa9fdfe-a110-4b6f-8daa-ecec1a579c4a)

also hovering enlarges the card...

https://github.com/anmode/grabtern-frontend/assets/120899038/e58ce057-f40f-40d8-80f0-d1e0ced3546b

**Comment by anmode** [comment]
NICE!
Needs some size change:
<img width="1280" alt="Screenshot 2023-06-23 at 1 01 35 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/704d8b7c-4129-423f-ac23-fcb24cacdb17">

Could you replicate same design?? you can code also i provided the repo

**Comment by ePSA-eJya** [comment]
Do you want ditto design? @anmode

**Comment by anmode** [comment]
yeahh!! Actually we are replicating the new homepage

**Comment by ePSA-eJya** [comment]
ok so i will replicate the image you sent

**Comment by ePSA-eJya** [comment]
should i keep the color 

> NICE! Needs some size change: <img alt="Screenshot 2023-06-23 at 1 03 41 PM" width="1280" src="https://user-images.githubusercontent.com/88332977/248202906-51cd809b-5265-41dd-a7c3-a2a3b5cb5ffb.png">
> 
> Could you replicate same design?? you can take code also I provided the repo

should i keep the same color scheme as you sent?

**Comment by anmode** [comment]
> ok so i will replicate the image you sent

yess! see there arrow you can check behaviour of testimonial by visiting to link

**Comment by anmode** [comment]
For now do not bother color scheme.. I will provide review in pR
main things:
How it should behave should be replidated from the theme i Provided

**Comment by Pushti18** [comment]
hover effect bhi dal dena

**Comment by ePSA-eJya** [comment]
i need some time to complete this @anmode

**Comment by ePSA-eJya** [comment]
https://github.com/anmode/grabtern-frontend/assets/120899038/011bc9c7-4092-4280-936a-a25c1199ce39

@anmode review this. i have added the arrow buttons.

**Comment by ePSA-eJya** [comment]
@anmode please review this

**Comment by Pushti18** [comment]
yes now it looks good

**Comment by ePSA-eJya** [comment]
> yes now it looks good

So shall i create a pr???

**Comment by Pushti18** [comment]
yes create

**Comment by ePSA-eJya** [comment]
https://github.com/anmode/grabtern-frontend/assets/120899038/279696ed-2250-4fe9-8411-0f8bc8e692c1

review this @Pushti18 @anmode

**Comment by ePSA-eJya** [comment]
i lost my files 😢

**Comment by Pushti18** [comment]
ohhhh

**Comment by ePSA-eJya** [comment]
> ohhhh

did everything again ....... 😫

**Comment by Vidip-Ghosh** [comment]
@anmode I will work on this issue
