### ISSUE TITLE
🚀 [Feature Request] - Password field in mentor registration form

### ISSUE THREAD

**Issue by shraddha761** [anmode/grabtern-frontend#412]
### Is your feature request related to a problem ? Please describe. ✍️

Mentor registration form should contain password and confirm password field which is not there  now

### Describe briefly how you would implement this enhancement.

```bash
Add password field in mentor registration form
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
This is currently in WIP. Actually we are redesigning it.
