### ISSUE TITLE
🚀 [Feature Request] - Dockerize the Application

### ISSUE THREAD

**Issue by Codeansh** [anmode/grabtern-frontend#415]
### Is your feature request related to a problem ? Please describe. ✍️

Docker containers encapsulate everything an application needs to run (and only those things), they allow applications to be shuttled easily between environments. So I think it would be helpful to dockerize this application.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
        Understand the code properly.
2. Step 2
        Find out the most suitable docker image for it.
3. Step 3
        Write the Dockerfile to run the application properly.

Additionally, I can add instructions in the readme file to run the application using docker.
```

### Additional context or screenshots

I think it is a very useful feature to add in order to manage and improve the application. Kindly allow me to work on this issue.
Thank You.

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Cool! make sure to hve multistage build!
