### ISSUE TITLE
[Feature-Request] -Implement Card Component for Internships

### ISSUE THREAD

**Issue by SVyusti** [anmode/grabtern-frontend#416]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Convert the Card in internship from html to nextUI and implement the same styling.
```

### Additional context or screenshots

![Screenshot from 2023-06-22 18-20-20](https://github.com/anmode/grabtern-frontend/assets/101053307/d60b60b3-f253-4603-92b7-18fd947a5569)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
ok fix overflowing here then please
