### ISSUE TITLE
[Bug]-Text overflowing in Internship cards

### ISSUE THREAD

**Issue by SVyusti** [anmode/grabtern-frontend#417]
### Description

![Screenshot from 2023-06-22 18-21-44](https://github.com/anmode/grabtern-frontend/assets/101053307/3e40e5d0-dafc-49d5-b6b7-190cc21818fc)

### Current behaviour

the description of the particular event in overflowing in particular screen sizes

### Expected behaviour

the text should remain within the card

### Reproduction steps

```bash
1. Go to 'https://www.grabtern.com/'
2. check featuring internships.
```

### Screenshots

![DESCRIPTION](LINK.png)

### Browsers

Firefox, Chrome

### OS

Linux

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
cool!
