### ISSUE TITLE
🚀 Add of Dark mode theme to grabtern

### ISSUE THREAD

**Issue by Owais24code** [anmode/grabtern-frontend#421]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context
I wanted to add a dark mode option to the website.

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
I will say again DarK mode is a big issue... it is not white -> black
We have change the behaviour of other colors in dark mode if you can do that then I'll assign you!

**Comment by anmode** [comment]
You can take idea as we are replicating this: https://grabtern-new-frontend.vercel.app/

**Comment by Owais24code** [comment]
> You can take idea as we are replicating this: https://grabtern-new-frontend.vercel.app/

@anmode Thank you for the idea 
I will give my best to make the website look good in dark mode, I would like to know if there is any community on Discord so I can update you with my work.

**Comment by anmode** [comment]
No time boundation...please there is  discord channel of gssoc you tag me @anmode

**Comment by Manice18** [comment]
@anmode can i work on this issue ?
