### ISSUE TITLE
🐞 [BUG] - Hamburger not responsive

### ISSUE THREAD

**Issue by Dev-Ahmadubah** [anmode/grabtern-frontend#428]
### Description

Hamburger while clicked on mobile view is not working properly

### Current behaviour

In the home page when clicked the hamburger icon on mobile view

### Expected behaviour

When clicked it suppose show a cancel icon for a user to cancel 

### Reproduction steps

```bash
1. Go to the webpage
2. clicked the hamburger icon
```

### Screenshots

![Screenshot_20230623_222805](https://github.com/anmode/grabtern-frontend/assets/60859825/7b55696a-87f1-4801-8ab5-a95712d8d480)

### Browsers

Chrome

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
here is PR: https://github.com/anmode/grabtern-frontend/pull/372
