### ISSUE TITLE
🚀 [Feature Request] - Add Captch in Login and Signup Form

### ISSUE THREAD

**Issue by AlfiyaSiddique** [anmode/grabtern-frontend#429]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement
## Description

I want to implement a captcha feature in the login and signup form. As captcha helps to identify between human users and bots it is an essential part of input forms. So we should implement it in our form.

## Request
If you find this issue worth implementing then please assign me.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. First Write a function to generate a captcha
2. Compare Generated captcha with the input value
3. Result Correct or incorrect captcha
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
actually we not needed this! thanks for raising issue
