### ISSUE TITLE
🚀 [Feature Request] - New UI for Mentor login page

### ISSUE THREAD

**Issue by Sh4dab** [anmode/grabtern-frontend#432]
### Is your feature request related to a problem ? Please describe. ✍️

I would like like to create a new UI for the mentors login page.
I have added the screenshot of the new UI.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

New UI will look like this:

![image](https://github.com/anmode/grabtern-frontend/assets/97034961/34c4e3be-4e98-4440-a916-ccde8908b1bf)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
You can remove confirm password
