### ISSUE TITLE
🚀 [Feature Request] - Redesigning login/Register page

### ISSUE THREAD

**Issue by shraddha761** [anmode/grabtern-frontend#440]
### Is your feature request related to a problem ? Please describe. ✍️

Redesign of login and register page 

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
@shraddha761 wanna design register page in new theme?

**Comment by shraddha761** [comment]
@anmode Yahh I'll do it

**Comment by anmode** [comment]
cool start krdo, Register page ko new theme m

**Comment by Abhinavcode13** [comment]
@shraddha761 update?

**Comment by shraddha761** [comment]
@Abhinavcode13 Working on it. Will raise the pr by today itself
