### ISSUE TITLE
🚀 [Feature Request] - Transition to new HomePage

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#442]
### Is your feature request related to a problem ? Please describe. ✍️

We will be moving to the new HomePage...
new theme is: https://grabtern-new-frontend.vercel.app/ ( light theme)

- We have card now ( login card ) we will remove that.. infact clicking on signIn button open a page ( which is currently developed )

source code you can take help : https://github.com/anmode/grabtern-NewFrontend ( tailwind classes are there you can copy directly)
Our theme color new is `#845ec2`
Remember background should not be pure white* See the new theme

### Describe briefly how you would implement this enhancement.

```bash
Null
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
The PR: https://github.com/anmode/grabtern-frontend/pull/328 ( hero section)

**Comment by Isha988** [comment]
@anmode I want to work on this issue.

**Comment by anmode** [comment]
I assigned you but @Isha988 would you like to work on refactoring first?? please till that time the PR i listed would be completed

**Comment by Isha988** [comment]
One question is this issue and uniformity pr same?

**Comment by anmode** [comment]
> > I assigned you but @Isha988 would you like to work on refactoring first?? please till that time the PR i listed would be completed
> 
> Okay, no problem I will work on refactoring first. Just brief me about your expectations and exactly work you want to get done in refactoring.

so refactoring firstly.. if you see there are same code used.
1. You can make button components or button Folder it should contains all types of button which are there and can be used.
2. A example we have used alert library as you know.. but i think it good to have alert component and it can be used anywhere.

like wise you can create issue for refactoring and can start working! if need more clarity. I am up for meet thanks

**Comment by anmode** [comment]
```
- components/
  - Layout/
    - Header/
      - Header.js
      - Header.module.css
      - ...
    - Footer/
      - Footer.js
      - Footer.module.css
      - ...
    - ...
  - UI/
    - Button/
      - Button.js
      - Button.module.css
      - ...
    - Input/
      - Input.js
      - Input.module.css
      - ...
    - ...

```

**Comment by Isha988** [comment]
> > > I assigned you but @Isha988 would you like to work on refactoring first?? please till that time the PR i listed would be completed
> > 
> > 
> > Okay, no problem I will work on refactoring first. Just brief me about your expectations and exactly work you want to get done in refactoring.
> 
> so refactoring firstly.. if you see there are same code used.
> 
> 1. You can make button components or button Folder it should contains all types of button which are there and can be used.
> 2. A example we have used alert library as you know.. but i think it good to have alert component and it can be used anywhere. ( In our UI design)
> 3. The card you created in registration component can be placed in basic folder as card can be used anywhere
>    like wise you can create issue for refactoring and can start working! if need more clarity. I am up for meet thanks
> 
> may be u interested: #316

Okay, got it

**Comment by Isha988** [comment]
> ```
> - components/
>   - Layout/
>     - Header/
>       - Header.js
>       - Header.module.css
>       - ...
>     - Footer/
>       - Footer.js
>       - Footer.module.css
>       - ...
>     - ...
>   - UI/
>     - Button/
>       - Button.js
>       - Button.module.css
>       - ...
>     - Input/
>       - Input.js
>       - Input.module.css
>       - ...
>     - ...
> ```

One Question, Should I create component according to new theme or the current theme?

**Comment by anmode** [comment]
I did not get!... 
woh astro wali theme copy kr rhe h ..structure nii
and current structure ko refactor kr rhe with that new theme.
