### ISSUE TITLE
🚀 [Feature Request] - "Why to be Mentor at Grabtern?" Section Alignment Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [anmode/grabtern-frontend#448]
### Is your feature request related to a problem ? Please describe. ✍️

No. It's an enhancement in the existing design.

### Describe briefly how you would implement this enhancement.

```bash
Step to implement this enhancement-
1. Making the content of this section equally aligned from all sides.
```

### Additional context or screenshots

Current Design
![grabtern (3)](https://github.com/anmode/grabtern-frontend/assets/115794049/78812773-e769-4d1e-9d96-93bee3f88f85)

Expected Updated Design
![grabtern (4)](https://github.com/anmode/grabtern-frontend/assets/115794049/8fb6821a-1e91-4200-b153-ee6d58076479)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
will be creating more nice issues sorry!!
soon
