### ISSUE TITLE
🐞 [BUG] - Inconsistent Contact Form Behavior and Lack of Error Handling

### ISSUE THREAD

**Issue by kirtiraj22** [anmode/grabtern-frontend#451]
### Description

The **contact form** on the website is experiencing inconsistent behavior and lacks proper error handling. This issue aims to address these problems and improve the overall user experience.

### Current behaviour

- When submitting the contact form **without filling** in the required fields, a generic **" Sent! "** alert message is displayed, even though **no message was actually sent**.
- A **basic alert message** is shown while sending a message, which negatively impacts the user interface.

### Expected behaviour

- If the user clicks the send button **without completing** the required fields, a **toast notification** should be displayed, indicating that the form is incomplete and prompting the user to fill in the necessary details.
- Upon **successful submission** of the message, a **success toast notification** should confirm that the message was sent.
- In the event of a **failure** to send the message, an **error toast notification** should be shown, informing the user about the issue.

### Reproduction steps

```bash
1. Go to the contact page
2. Click on send(without filling any of the fields)
3. See error (sent alert will be displayed)
```

### Screenshots

![Screenshot (172)](https://github.com/anmode/grabtern-frontend/assets/83873093/ca1217f4-288f-4b36-ab6f-2b0702b06e15)

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by naim16031988** [comment]
i think i can work on this , can you assign me this

**Comment by kirtiraj22** [comment]
hey @naim16031988 , I have already raised this particular issue and I'm keen on working on it. 
I appreciate your enthusiasm, and I encourage you to explore other issues within the project.🙂

**Comment by anmode** [comment]
yeah! wait for some time.. there is pR alredy for designing after you can work on functionality.. till the time can work on other issues

**Comment by naim16031988** [comment]
allright thinks
