### ISSUE TITLE
🚀 [Feature Request] - Adding hover effects with linkedIn urls over the team section

### ISSUE THREAD

**Issue by Akanksha-202** [anmode/grabtern-frontend#453]
### Is your feature request related to a problem ? Please describe. ✍️

There is no way to reach the creative team of the website. This gives more opportunities and reach to the team!

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1: Adding hover effects with the LinkedIn URL of the respective team member.
```

### Additional context or screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/100708686/b5794bf7-ab58-46a0-a86c-6c676343e15d)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
We need a grabtern community page... as of now we hv a section will move to this page.. if you are up for desinging it lemme know.

**Comment by Akanksha-202** [comment]
Sure, I can
