### ISSUE TITLE
🚀 [Feature Request] - Footer Design for new theme 

### ISSUE THREAD

**Issue by ShreyaDhiman24** [anmode/grabtern-frontend#454]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

before:

![image](https://github.com/anmode/grabtern-frontend/assets/98320971/b67a1caa-419d-4d1b-b885-6520f6270d49)

template (after):

![image](https://github.com/anmode/grabtern-frontend/assets/98320971/353f0dd6-66de-4b83-8330-109010297fe9)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
It is already in new theme  :)
