### ISSUE TITLE
🚀 [Feature Request] - Want to add styling to the scroll bar of the website 

### ISSUE THREAD

**Issue by HimanshuNarware** [anmode/grabtern-frontend#456]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement: I Want to add styling to the scroll bar of the website, This will improve the UI of the website.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Added background color to the scrollbar track
2. Added hover effect on the scrollbar thumb
3. Added background on the scrollbar track
```

### Additional context or screenshots

Additional context
![6](https://github.com/anmode/grabtern-frontend/assets/83147410/ec1e3d5c-c503-429e-9ae3-05746141add0)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
can you suggest the design. and website using the scroll bars? As i think using scroll bar is not good practice. If you can convince then you feel free to work thanks

**Comment by HimanshuNarware** [comment]
> can you suggest the design. and website using the scroll bars? As i think using scroll bar is not good practice. If you can convince then you feel free to work thanks

 I want to add a design similar to the theme of the website, and also help users to move anywhere to the top of the website within a second, that is why I think it's important

**Comment by anmode** [comment]
Ok! lets see how it look.
