### ISSUE TITLE
🚀 [Feature Request] - Create Internship Page with Search, Filter, and Exploration Functionality

### ISSUE THREAD

**Issue by Nishitbaria** [anmode/grabtern-frontend#457]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement
Currently, there is no dedicated page for internships on the website. It would be beneficial to create an Internship page that allows users to search, filter, and explore internship opportunities. This feature will greatly enhance the user experience and provide a valuable resource for students and job seekers looking for internships.

### Describe briefly how you would implement this enhancement.

```bash
## Feature Description
The Internship page should include the following functionality:

1. Search: Users should be able to search for internships based on keywords, such as job title, company name, or location. The search functionality should provide relevant results and support advanced search options if possible.

2. Filter: Users should be able to filter internships based on various criteria, such as industry, duration, paid/unpaid, remote/on-site, and application deadline. This will help users narrow down their options and find internships that align with their preferences.

3. Sorting: The ability to sort internship listings based on criteria like relevance, date posted, or application deadline will help users prioritize and find the most suitable internships.


4. Exploration and Recommendations: The page should offer features for users to explore internships based on popular categories, trending industries, or recommended opportunities. This will help users discover internships they might not have considered otherwise.

## Benefits
- Provides a dedicated platform for users to find and apply for internships.
- Streamlines the internship search process by offering search, filter, and sorting options.
- Increases user engagement and satisfaction by providing relevant and comprehensive internship information.
- Helps connect students and job seekers with internship opportunities that match their preferences and career goals.
- Enhances the website's value as a comprehensive resource for career development.
```

### Additional context or screenshots

- The internship page should have a user-friendly interface and ensure seamless navigation and interaction.
- It should integrate well with the existing website design and maintain consistency in terms of branding and aesthetics.
- The implementation should consider scalability and flexibility to accommodate future updates and enhancements.
- It would be beneficial to incorporate user feedback and iterate on the features based on user needs and preferences.

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Nishitbaria** [comment]
@anmode please assign me this issue

**Comment by anmode** [comment]
> @anmode Do you want description in internship or just like hackathon page only images.
> 

Description - short with site link attached....it would be great if mentor related to that intern can show up in that section...
It would be cool...think of how you can achieve this

**Comment by Nishitbaria** [comment]
Can you explain in more detail or with some images what you want me to do for better understanding?

**Comment by anmode** [comment]
Actually this is somethings new:
I will explain better on meet!

**Comment by anmode** [comment]
@Nishitbaria ?

**Comment by Nishitbaria** [comment]
@anmode I  am sorry,I forgot ,Can you please tell me time in which I should come on meet

**Comment by anmode** [comment]
@Nishitbaria what is the update?? choti choti PRs m tod lete h....`internship page pR 1` ......pR 2....

**Comment by Nishitbaria** [comment]
@anmode ,Today i will make intail pull request

**Comment by Nishitbaria** [comment]
@anmode,please preivew and merge my pull request

**Comment by Nishitbaria** [comment]
@anmode ,which next fucntionality you want to add to internship page?
