### ISSUE TITLE
🚀 [Feature Request] - Create an FAQ section for the website

### ISSUE THREAD

**Issue by abhi03ruchi** [anmode/grabtern-frontend#459]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement : I would like to Create an FAQ section for the website where general queries of the mentors and students are addressed..

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
There is faq section for mentor page... in mentorPage in components folder. you can reuse that...make is reusable component and trasfer it to basic folder.
