### ISSUE TITLE
🐞 [BUG] - Scroll to Top Button is not visible .

### ISSUE THREAD

**Issue by abhi03ruchi** [anmode/grabtern-frontend#460]
### Description

The Scroll to Top Button is not visible on every page. I would like to resolve this issue and add scroll to top button .

### Current behaviour

--

### Expected behaviour

--

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
--
```

### Screenshots

![DESCRIPTION](LINK.png)

### Logs

```bash
-
```

### Browsers

Chrome

### OS

Mac

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
please create PR
