### ISSUE TITLE
🐞 [BUG] - 404 error through breadcrumb navigation

### ISSUE THREAD

**Issue by SVyusti** [anmode/grabtern-frontend#462]
### Description

On trying to navigate using the breadcrumb component, being redirected to "404 error page not found".

https://github.com/anmode/grabtern-frontend/assets/101053307/7db02a4c-7cd6-4be9-8331-c5d26b9c3664

### Current behaviour

On trying to navigate to home using the breadcrumb component in contact or mentors page , being redirected to "404 error page not found".

### Expected behaviour

should be able to navigate to home using the breadcrumb component in contact or mentors page.

### Reproduction steps

```bash
1. Go to 'https://www.grabtern.com/contact#'
2. Click on 'home' in the breadcrumb component
3. See error
```

### Screenshots

![DESCRIPTION](LINK.png)

### Browsers

Firefox, Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
we will remove that!

**Comment by tech-bash** [comment]
In my case its working just fine.
