### ISSUE TITLE
🐞 [BUG] - Card Content Overflow 

### ISSUE THREAD

**Issue by vaibhav-xt** [anmode/grabtern-frontend#463]
### Description

Our Featured Internships Cards content is overflowing. I can make this look far better. All text and image height will be consistent.  

### Current behaviour

Cart content overflowing. 

### Expected behaviour

Should be consistent and not go outside the card.

### Screenshots

![Screenshot (109)](https://github.com/anmode/grabtern-frontend/assets/90946899/edebc955-f297-4665-9d2b-63582de3dbd5)

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by vaibhav-xt** [comment]
I would like to work on this issue.

**Comment by anmode** [comment]
@vaibhav-xt so sorry.. I will creating more descent issue. It wil really great hope you will also enjoying solving it
