### ISSUE TITLE
🚀 [Feature Request] - improve the mentors page 

### ISSUE THREAD

**Issue by karthiknadar1204** [anmode/grabtern-frontend#467]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement:
I was thinking of beautifying the individual cards of the mentors and highlighting their info displayed on the cards in a much better way to make it look for attractive, right now the cards have a lot of blank space which makes it look weird.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Enlarge the image
2. make the name and image credentials have a larger font size to make them look more prominent.
3. make the buttons look uniform on all the cards.
4. add some better hover effect to the social icons on the cards.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by anmode** [comment]
can you suggest a figma design first?

**Comment by karthiknadar1204** [comment]
@anmode I don't have any figma design as such, I have a design in mind, if you don't mind, I can share a preview of my design before I submit a pr, if you want any changes, you can suggest to me looking at the preview, will add the changes accordingly.
fine?

**Comment by anmode** [comment]
That's cool!

**Comment by karthiknadar1204** [comment]
Works, will fully furnish the page and share a preview here soon
Thank you

**Comment by karthiknadar1204** [comment]
@anmode There seems to be some error , I set up the project on my system, the original hosted version has a different UI from the one I have set up locally for the mentors page
original:
<img width="1791" alt="Screenshot 2023-06-30 at 4 50 19 PM" src="https://github.com/anmode/grabtern-frontend/assets/95973644/83856224-3a02-4379-9030-61c2a648c63f">



Local setup:
<img width="1792" alt="Screenshot 2023-06-30 at 4 50 33 PM" src="https://github.com/anmode/grabtern-frontend/assets/95973644/ff16c7b4-98c9-4b67-b6c2-25ebbdfe11c0">


Also there are a bunch of warnings in the terminal when setting up the project

<img width="1460" alt="Screenshot 2023-06-30 at 4 52 24 PM" src="https://github.com/anmode/grabtern-frontend/assets/95973644/1cebcf73-13be-438f-8732-5c0889960ddf">

**Comment by karthiknadar1204** [comment]
How to proceed

**Comment by anmode** [comment]
No problem ignore the warning... or you can try to refactor after this issue!

**Comment by karthiknadar1204** [comment]
Could you please assign it to me though, it seems I haven't been assigned yet @anmode

**Comment by anmode** [comment]
> ok, will check in in a few days if the issue has been resolved, then will resume work

this is not an issue.. what issue you are saying? you have to apply changes on development level.. do not see production one

**Comment by karthiknadar1204** [comment]
> > ok, will check in in a few days if the issue has been resolved, then will resume work
> 
> this is not an issue.. what issue you are saying? you have to apply changes on development level.. do not see production one

ohk, because the design I had in mind was wrt the one in production level, will get working with the one in development level and share preview tomorrow at this time sure thing.

**Comment by anmode** [comment]
that's cool...waiting

**Comment by karthiknadar1204** [comment]
@anmode Have resumed the work, so in the development version, since it is so very different from the production version, I'll try to imitate the cards in the production version including the social links and the book session button,
Is that fine?

**Comment by anmode** [comment]
Current design of card look me good....but if you provide a more optimized, see topmate.io , mentro.tech and other sites which have cards..
forget production version.... just see development mode
