### ISSUE TITLE
🚀 [Feature Request] - Logo is not visible in dark mode in new theme.

### ISSUE THREAD

**Issue by ShreyaDhiman24** [anmode/grabtern-frontend#468]
### Is your feature request related to a problem ? Please describe. ✍️

![Screenshot_20230630_040419_Chrome](https://github.com/anmode/grabtern-frontend/assets/98320971/6cd7e0c2-6ff4-4ba0-b846-0e1c3f7f6865)

### Describe briefly how you would implement this enhancement.

```bash
Change logo to white for dark theme
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
arey! we do not have dark theme and we will not replicate dark theme .. we will just copy hompage design of light mode

**Comment by ShreyaDhiman24** [comment]
> arey! we do not have dark theme and we will not replicate dark theme .. we will just copy hompage design of light mode

okayy!
