### ISSUE TITLE
🚀 [Feature Request] - Schedule of mentor improvment

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#471]
### Is your feature request related to a problem ? Please describe. ✍️

can we have something like:
<img width="544" alt="Screenshot 2023-06-30 at 1 10 12 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/bcb9e271-fa62-4332-b4ac-20acc2caa96a">

but in current theme of grabtern

### Describe briefly how you would implement this enhancement.

```bash
it will like grabtern schedule picker component...
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
@Isha988 are you interested in this?

**Comment by anmode** [comment]
Great, Agreed!

**Comment by shraddha761** [comment]
@anmode I can add this feature. After user click to book session then he'll redirect to this page

**Comment by anmode** [comment]
actually this is for mentor Registration form not user side

**Comment by shraddha761** [comment]
Ohh ok when mentor session book then he'll allot
