### ISSUE TITLE
🚀 [Feature Request] - Make search bar working

### ISSUE THREAD

**Issue by vaibhav-xt** [anmode/grabtern-frontend#477]
### Describe briefly how you would implement this enhancement.
The search bar is not working.  
![Screenshot (123)](https://github.com/anmode/grabtern-frontend/assets/90946899/b835fdec-f3c3-4043-96f6-f56ac50735ab)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
ig it is working?
