### ISSUE TITLE
[Improvement] Mentor Registor Form

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#48]
There is a need to improve the Mentor register form. 
1. Can't handle profile pic of large size. [If not able to take a large image then put condition then if the limit exceeds]
2. On click button it took so a loader can be made so mentor gets to know ok! 

Debug!

**Comment by Swetha-Baskaran** [comment]
I wish to contribute to this. Assign this to me with the gssoc'23 label.

**Comment by anmode** [comment]
sure!

**Comment by anmode** [comment]
R u working? if any issue feel free to ask.

**Comment by Swetha-Baskaran** [comment]
Yeah I'm working on this.

**Comment by anmode** [comment]
Hii? @Swetha-Baskaran are you active on this?

**Comment by Swetha-Baskaran** [comment]
Yes, I'll give the pr by today

**Comment by Abhinavcode13** [comment]
issue resolved? @Swetha-Baskaran

**Comment by Swetha-Baskaran** [comment]
Will you pls confirm what is maximum image file size should be allowed to upload?

**Comment by anmode** [comment]
We take image from google and other you can keep a minimal size for regular person to upload. like 2mb.

**Comment by anmode** [comment]
our inspiration: https://mentro.tech/mentor/apply

**Comment by anmode** [comment]
@Swetha-Baskaran ? are you there

**Comment by Swetha-Baskaran** [comment]
Yeah I'm here. One more thing, will you give more details about the loader?

And the I made the message text box as fixed for now. You want to make it's height equal to the height of the para? Even it's so long?

**Comment by Abhinavcode13** [comment]
Make a PR and provide the screenshot will review it @Swetha-Baskaran !!

**Comment by anmode** [comment]
@Swetha-Baskaran we are thinking as some what like this -https://mentro.tech/mentor/apply

**Comment by Abhinavcode13** [comment]
no response closing as of now @anmode
