### ISSUE TITLE
🚀 [Feature Request] - Add captcha verification in Register Page

### ISSUE THREAD

**Issue by Manice18** [anmode/grabtern-frontend#482]
### Is your feature request related to a problem ? Please describe. ✍️

A captcha helps to prevent bot from signing up and helps differentiate a real user from a bot.
Hence I will like to add a captcha verification in the Register Page.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. I will add the captcha below the confirm password
2. Will make any necessary changes in the UI so that the UI is not hampered
```

### Additional context or screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/91601706/5456a5a9-198d-4c11-85bd-f47fa592cdf0)
This is where i will like to add the captcha verification

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Not needed!
