### ISSUE TITLE
Enhancing UI of User Login Page

### ISSUE THREAD

**Issue by MAXASSASSINS** [anmode/grabtern-frontend#487]
### Description
I want to make some enhancements to the `USER LOGIN` page

### Solutions Proposed
- Change the colour of the login button to white
- Removing redundant labels "Email" and "Password".
- Improving hover effect on `Forgot Password`. 
- Add colour and underline to `Register here`.

#### Before
<img width="1440" alt="Screenshot 2023-07-05 at 4 49 26 PM" src="https://github.com/anmode/grabtern-frontend/assets/97503316/4e292de4-c590-4b5a-83f4-3c0087515871">

#### After
<img width="1440" alt="Screenshot 2023-07-05 at 5 05 42 PM" src="https://github.com/anmode/grabtern-frontend/assets/97503316/8fedc50c-c9ea-4af6-8f3a-584f00d672ec">

### Additional Context
Please assign me this task under GSSoC'23.

### Checklist
- [x]  I have checked the existing [issues](https://github.com/anmode/grabtern-frontend/issues)
- [x]  I have read the [Contributing Guidelines](https://github.com/anmode/grabtern-frontend/blob/develop/CONTRIBUTING.md)
- [x]  I would like to be assigned this task.
- [x]  I am a GSSoC'23 contributor

**Comment by anmode** [comment]
Hey, tum toggle pr work kr rhe the n?

**Comment by MAXASSASSINS** [comment]
Nahi mai nahi kar raha tha @anmode

**Comment by anmode** [comment]
okk
