### ISSUE TITLE
🚀 [Feature Request] - New Hero Section

### ISSUE THREAD

**Issue by ShreyaDhiman24** [anmode/grabtern-frontend#493]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

Slider form design of login for user and mentor (new theme)

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
@ShreyaDhiman24 Cool you wanna work on this??

**Comment by ShreyaDhiman24** [comment]
> @ShreyaDhiman24 Cool you wanna work on this??

Yeah! under GSSoC'23

**Comment by Abhinavcode13** [comment]
Go ahead @ShreyaDhiman24

**Comment by anmode** [comment]
Wait wait

**Comment by anmode** [comment]
This: https://github.com/anmode/grabtern-frontend/issues/295

**Comment by ShreyaDhiman24** [comment]
> This: #295 R u up @ShreyaDhiman24 ??
> 
> If yes you can directly create pR nd in this issue you just have to copy paste the code from the repo code i provided nd it work here

okay! but what I have to do?

**Comment by anmode** [comment]
> > This: #295 R u up @ShreyaDhiman24 ??
> > 
> > If yes you can directly create pR nd in this issue you just have to copy paste the code from the repo code i provided nd it work here
> 
> okay! but what I have to do?

See in issue...just go to issue link. And also see the convo in issue

**Comment by anmode** [comment]
Have a look to this pR: https://github.com/anmode/grabtern-frontend/pull/491

Same you have to do....but please use tailwind and try to create exact copy of theme.

**Comment by anmode** [comment]
@ShreyaDhiman24 just to confirm till which i date i can expect the PR?? actually we are going to launch new theme soon

**Comment by anmode** [comment]
@ShreyaDhiman24 Could you start work on toggle, please?? if you haven't touched homepage

**Comment by ShreyaDhiman24** [comment]
> @ShreyaDhiman24 just to confirm till which i date i can expect the PR?? actually we are going to launch new theme soon

within 1-2 days..

**Comment by ShreyaDhiman24** [comment]
> @ShreyaDhiman24 just to confirm till which i date i can expect the PR?? actually we are going to launch new theme soon
@anmode Checkout I have completed.

**Comment by ShreyaDhiman24** [comment]
> @ShreyaDhiman24 Could you start work on toggle, please?? if you haven't touched homep

> @ShreyaDhiman24 Could you start work on toggle, please?? if you haven't touched homepage

Can I create new issue for that ?
