### ISSUE TITLE
🚀 [Feature Request] - Create Toggle ( mentor/user - as login)

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#494]
### Is your feature request related to a problem ? Please describe. ✍️

<img width="831" alt="Screenshot 2023-07-08 at 4 40 06 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/e67a6fab-af3e-49b8-a18a-7e6423d79158">

Just a example. 

### Describe briefly how you would implement this enhancement.

```bash
Provided a example
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
@crocmons , I just provided this as an example.

**Comment by crocmons** [comment]
Can I create like a sliding way with one side user & another side mentor for the login page only? @anmode  - 

![Screenshot (8)](https://github.com/anmode/grabtern-frontend/assets/106610322/4eb9f9e3-1bd8-40b0-b281-340c597ed38f)

**Comment by anmode** [comment]
sure it would be good!! Just the thing is theme should be applied.

**Comment by anmode** [comment]
Hi, I have to plan things.. could you please provide the date upto which you can create PR for it. please

**Comment by anmode** [comment]
@crocmons ?

**Comment by crocmons** [comment]
Ah, @anmode I can't do that right now as I need to submit other projects this week.. So, yeah, you can assign this problem to any other one..

**Comment by anmode** [comment]
> Ah, @anmode I can't do that right now as I need to submit other projects this week.. So, yeah, you can assign this problem to any other one..

Oh ok @crocmons. Please ping in this issue when you get free. I see if nobody takes over you can work. thanks

**Comment by ShreyaDhiman24** [comment]
I would like to work on this issue @anmode

**Comment by anmode** [comment]
Ok

**Comment by anmode** [comment]
This Issue still pending :)
