### ISSUE TITLE
🚀 [Feature Request] - Add Contributor Page

### ISSUE THREAD

**Issue by SubhamB2003** [anmode/grabtern-frontend#495]
### Is your feature request related to a problem ? Please describe. ✍️

Hey, Is there a need for a contributor page? If yes can you please assign it to me I want to add this page.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
sorry but do not need this. Thankss
