### ISSUE TITLE
🚀 [Feature Request] - Optimize Image cropper and reduce image while uploading

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#496]
### Is your feature request related to a problem ? Please describe. ✍️

Optimization in Mentor Form... To have image cropper.
We have image cropper.
/component/basic/imageCropper.js

### Describe briefly how you would implement this enhancement.

```bash
Optimization....and use it, actually as of now we are not using it.
```

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by MAXASSASSINS** [comment]
Hey, @anmode can you please assign this issue to me? 

I have added the image cropper component. 
Below is the video demonstrating the same.

https://github.com/anmode/grabtern-frontend/assets/97503316/846beb9f-35f7-40ec-9c0e-08d1be21741e

**Comment by anmode** [comment]
cool! please try to compress the image too before uploading on cloudinary and also it is taking time too... please see this PR to keeping in mind you can code-

**Comment by anmode** [comment]
btw what you showed in demo is responsive too isn't?

**Comment by MAXASSASSINS** [comment]
Yes, it is responsive @anmode. When I created the image cropper component I already took care of this.

https://github.com/anmode/grabtern-frontend/assets/97503316/50f04fd4-2099-4d00-a4ae-8d989a430480

**Comment by MAXASSASSINS** [comment]
As far as image size is concerned we have already compressed the image size by cropping it.
I have checked the blob size after cropping it is coming out to be 63 which is very low.

**Comment by MAXASSASSINS** [comment]
Hey @anmode I have added the upload to Cloudinary functionality. I have checked the execution of the upload function it is taking around 1 sec.
Should I create a PR now?

**Comment by anmode** [comment]
yeah sure please create PR
