### ISSUE TITLE
🚀 [Feature Request]- Adding a dark mode to the website

### ISSUE THREAD

**Issue by deepshikha2708** [anmode/grabtern-frontend#499]
### Is your feature request related to a problem ? Please describe. ✍️

Adding a dark mode button for the website, for better user experience.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by deepshikha2708** [comment]
@anmode I am facing issue in running it using npm run dev. Please help me out. It is showing server error.

**Comment by anmode** [comment]
what error...ping me on discord.

**Comment by deepshikha2708** [comment]
discord username?

**Comment by Abhinavcode13** [comment]
Need a update, what's the progress? @deepshikha2708

**Comment by anmode** [comment]
Yeh darkk kbse chl rha abhi tk kisi pr complete ni hua :)
@Abhinavcode13 wanna try?
