### ISSUE TITLE
🚀 [Feature Request] - Add a "Scroll To Top" Button & Scroll Bar

### ISSUE THREAD

**Issue by 5h0ov** [anmode/grabtern-frontend#500]
### Is your feature request related to a problem ? Please describe. ✍️

# Enhancement

I would like to add a scroll to top button with the following concept:

![scrollbutton](https://github.com/anmode/grabtern-frontend/assets/83227649/e3ef8373-488c-48f5-9a32-983627107dbd)

I would also like to add a scroll bar

It would be great to contribute to this repo under GSSoC'23!

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
But this scroll should be in our UI design please

**Comment by Abhinavcode13** [comment]
@5h0ov ?? Need update on this

**Comment by 5h0ov** [comment]
@Abhinavcode13  hm i am having some problems so imma close it for now
