### ISSUE TITLE
🚀 [Feature Request] - META ELEMENTS TO IMPROVE SEO

### ISSUE THREAD

**Issue by 0xabdulkhalid** [anmode/grabtern-frontend#501]
### Is your feature request related to a problem ? Please describe. ✍️

- The `<meta>` elements in HTML are used to provide metadata or additional information about an HTML document. 
- They help with specifying the character encoding, defining the viewport for responsive design, setting the page title, and providing page descriptions. 
- They assist search engines, browsers, and other web applications in understanding and processing the webpage's content effectively.

### Describe briefly how you would implement this enhancement.
- I want to add important Meta elements because in HTML they play a crucial role in providing information about the webpage to browsers and search engines and for the above mentioned reasons.

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by 0xabdulkhalid** [comment]
Hey there @anmode 👋🏻 , Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by anmode** [comment]
cool!
