### ISSUE TITLE
🚀 [Feature Request] - Changing Favicon to new logo

### ISSUE THREAD

**Issue by ShreyaDhiman24** [anmode/grabtern-frontend#507]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

![Screenshot from 2023-07-13 04-12-24](https://github.com/anmode/grabtern-frontend/assets/98320971/c430fcbd-4b7d-4ff8-b496-f4d9a782e3cf)

### Describe briefly how you would implement this enhancement.

```bash
Changing favicon
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Abhinavcode13** [comment]
Go ahead @ShreyaDhiman24

**Comment by Abhinavcode13** [comment]
Do you have new logo design @ShreyaDhiman24 ?

**Comment by ShreyaDhiman24** [comment]
> Do you have new logo design @ShreyaDhiman24 ?

Yeah That is on the code space itself..ig
