### ISSUE TITLE
🚀 [Feature Request] - Improving Privacy Policy Section

### ISSUE THREAD

**Issue by Vidip-Ghosh** [anmode/grabtern-frontend#510]
### Is your feature request related to a problem ? Please describe. ✍️

Reducing the paragraph contents 
Adding styles 

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Abhinavcode13** [comment]
@Vidip-Ghosh please follow code of conduct, don't make a PR unless you're assigned.
