### ISSUE TITLE
🚀 [Feature Request] - Convert mentor page nd redesign `/mentor`

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#514]
### Is your feature request related to a problem ? Please describe. ✍️

Mentor page is not designed into new theme

### Describe briefly how you would implement this enhancement.

```bash
null
```

### Additional context or screenshots

It is mentor page which open when we click on `be a mentor`.
it is already coded needs to be redesigned

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by harshita-2003** [comment]
assign me

**Comment by anmode** [comment]
cool ok

**Comment by anmode** [comment]
Hey, how's work going?? you can create a PR with WIP

**Comment by rishuraj1** [comment]
Hey @anmode please assign this task to me, since no one is assigned, I would really love to work on this one. Thanks!

**Comment by anmode** [comment]
okk
