### ISSUE TITLE
🚀 [Feature Request] - explore top hackathon section ui improvement

### ISSUE THREAD

**Issue by harshita-2003** [anmode/grabtern-frontend#516]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement of the ui section of top hackathons 
as now they does not aligned equally to each other 

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 cards ui 
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
It is fixed!
