### ISSUE TITLE
🐞 [BUG] - Home link error

### ISSUE THREAD

**Issue by rishuraj1** [anmode/grabtern-frontend#518]
### Description

The home link in the mentors page is broken, it does not redirects us to the homepage, as it should do..
We might want to fix that.

Please assign me this issue under GSSoC '23. Thank You !

### Current behaviour

It redirects us the page not found page..

### Expected behaviour

It should redirect us to the homepage of the application.

### Reproduction steps

```bash
1. Go to mentors page
2. Click on home button
3. See error
```

### Screenshots

<img width="960" alt="Screenshot 2023-07-16 110350" src="https://github.com/anmode/grabtern-frontend/assets/47839626/d03667dc-e69b-4d88-90b1-27726d28a5cd">

![image](https://github.com/anmode/grabtern-frontend/assets/47839626/1a501211-0f8c-48f9-a9f6-2ab3409ab7e1)

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
No worries.. i fixed it
