### ISSUE TITLE
🚀 [Feature Request] - Add show/hide password functionality

### ISSUE THREAD

**Issue by rishuraj1** [anmode/grabtern-frontend#519]
### Is your feature request related to a problem ? Please describe. ✍️

I believe we should add a show/hide password button in the signin and signup forms for better user interface and user experience.
I have attached screenshots with marked area where the feature is to be implemented.

Please assign me this task under GSSoC '23. Thank You !

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. adding the icons for show/hide button
2. adding functionality to that icon/button
```

### Additional context or screenshots

<img width="960" alt="Screenshot 2023-07-16 110021" src="https://github.com/anmode/grabtern-frontend/assets/47839626/70b65651-33ac-4274-b5f5-bd055b4dd324">

<img width="960" alt="Screenshot 2023-07-16 105939" src="https://github.com/anmode/grabtern-frontend/assets/47839626/b2482f3b-8d7a-461f-8821-fce463dfb2d5">

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
<img width="737" alt="Screenshot 2023-07-16 at 11 42 29 AM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/8a786e3e-4ba2-442e-8395-549034d82fea">
I think you are seeing production changes.. try to run project on local and see
