### ISSUE TITLE
🚀 [Feature Request] - Add styles to improve UI of contact form

### ISSUE THREAD

**Issue by rishuraj1** [anmode/grabtern-frontend#520]
### Is your feature request related to a problem ? Please describe. ✍️

We might want to improve UI for the contact form for better user exp.
adding some icons and styles to the form might help.

Could you please assign this task to me under GSSoC '23. Thank You !

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Adding appropriate icons for the input fields
2. adding a suitable bg for the form
3. changes in style of overall form.
```

### Additional context or screenshots

<img width="960" alt="image" src="https://github.com/anmode/grabtern-frontend/assets/47839626/c502a0ea-39d4-4b58-a42d-46c408ac631c">

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
It has been updated already. Please see develoop branch on local
