### ISSUE TITLE
🚀 [Feature Request] - Add footer to the mentors page

### ISSUE THREAD

**Issue by rishuraj1** [anmode/grabtern-frontend#521]
### Is your feature request related to a problem ? Please describe. ✍️

Currently, there is no footer attached to the mentors page.
We should add the footer in the mentors page.

Its an easy task, please assign me this under GSSoC '23. Thank You !

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Actually it is not needed, I advised you to run project locally on develop branch.
Hope to see nice issues from your side
