### ISSUE TITLE
🐞Section Improvement

### ISSUE THREAD

**Issue by akanksha984** [anmode/grabtern-frontend#524]
### Description

![image](https://github.com/anmode/grabtern-frontend/assets/97845909/5c7350f2-2ba4-4b86-9ed9-442485c90e7d)

Improve the ui of this section Please assign it to me under gssoc'23.
I want to work upon these issues.

### Current behaviour

-

### Expected behaviour

-

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
See development one, do not see production, the card has been changed. you created issues, by seeing the production. 
I'll create some issues of mentor Dashboard...
