### ISSUE TITLE
🐞 Move to top button missing

### ISSUE THREAD

**Issue by akanksha984** [anmode/grabtern-frontend#528]
### Description

I want to add move to top button in the website. Please assign it to me under gssoc'23

### Current behaviour

-

### Expected behaviour

-

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by akanksha984** [comment]
@anmode  please check it https://github.com/anmode/grabtern-frontend/pull/539

**Comment by anmode** [comment]
left you comment

**Comment by anshulsoni4** [comment]
hey @anmode can you assign this to me, i can add this quickly

**Comment by akanksha984** [comment]
@anshulsoni4 I have already created it, Just the pr needs to be merged

**Comment by anmode** [comment]
> hey @anmode can you assign this to me, i can add this quickly

there are more issues.. please look
