### ISSUE TITLE
🚀 [Feature Request] - Create/Modify Sidebar for MentorDashboard

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#530]
### Is your feature request related to a problem ? Please describe. ✍️

You will find... 
pages/dashboard/mentor

Modify sidebar.js

### Describe briefly how you would implement this enhancement.

```bash
See the UI of our website.. you can use components from UI folder..
and make sidebar in our UI
```

### Additional context or screenshots

Try to apply routing too, 
url should change according to click...
for more refer any dashboard... how it's sidebar works

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
<img width="291" alt="Screenshot 2023-07-17 at 10 52 33 AM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/f58e5010-a313-45ed-9ad5-76df3785d15a">

**Comment by coder12git** [comment]
@anmode I want to work on this issue. Please assign it to me.

Note -> I am a contributor in GSSOC'23.

**Comment by coder12git** [comment]
@anmode Please add level label

**Comment by coder12git** [comment]
@anmode  I have created a PR for this.
PR no - #564

**Comment by anmode** [comment]
cool, Good to merge
