### ISSUE TITLE
🚀 [Feature Request] -Create Service Page/ Session page for Mentor Dashbaord.

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#531]
### Is your feature request related to a problem ? Please describe. ✍️

You have create the page... where all session of mentor can be edit and send to backend through a api,
Do not worry update API is ready..... you just have to show the payload and develop the frontend part.

### Describe briefly how you would implement this enhancement.

```bash
You will get the data from api ... see how mentor card are forming ( in mentorUsername page)
now in session page.. mentor should be able to edit it's ssesions and send to backend to update them.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
I will have meet, to explain things in more details... who willl be working on mentorDashboard Issuess

**Comment by mandliyarajendra11** [comment]
@anmode assign me pls

**Comment by anmode** [comment]
sure

**Comment by anmode** [comment]
@mandliyarajendra11 ?? what happened... if facing any issue please let me know

**Comment by mandliyarajendra11** [comment]
> @mandliyarajendra11 ?? what happened... if facing any issue please let me know

sorry , I am shifting rooms, so I could not work

**Comment by anmode** [comment]
no worries
