### ISSUE TITLE
🐞 [BUG] - why confirm

### ISSUE THREAD

**Issue by mandliyarajendra11** [anmode/grabtern-frontend#536]
### Description

why confirm password at login page

### Current behaviour

ask for confirm pass

### Expected behaviour

login page doesnot need confirm password

### Reproduction steps

```bash
1. Go to 'mentor login'
```

### Screenshots

![Screenshot (183)](https://github.com/anmode/grabtern-frontend/assets/119125519/103f4065-978a-4878-b2e1-a35fae66850c)

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
it's great.. there is PR assigned.. I'll this point there. 
Thanks
