### ISSUE TITLE
🚀 [Feature Request] - Social links should open in a new tab

### ISSUE THREAD

**Issue by 777Prabhjot** [anmode/grabtern-frontend#537]
### Is your feature request related to a problem ? Please describe. ✍️

Social links are getting opened in same tab i think they should be opened in new tab so that the user don't have to go back and forward.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to reproduce
1. Go to the footer
2. Click any of the social links
3. They are getting opened in same tab
```

### Additional context or screenshots

Additional context

https://github.com/anmode/grabtern-frontend/assets/68184118/55cbdfde-92a5-47a0-9dad-bba39070d018

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
please check the develoopment version not the production one.. try to setup the project locally and see
