### ISSUE TITLE
[style]: Improve the UI Experience of Grabtern Community Section

### ISSUE THREAD

**Issue by harmeetsingh11** [anmode/grabtern-frontend#540]
## Description:
The current UI of `Grabtern Community` section on `Home` page is very basic, we need to improve it.

I want to add some hover zooming effect and some box shadow to the profile Card to make the UI Experience more enhanced.

## Screenshot
![Capture](https://github.com/anmode/grabtern-frontend/assets/130365071/b08dfd87-8649-431f-9a1f-ec389e235769)

## Record
- [x] I agree to follow this project's Code of Conduct 
- [x] I'm a GSSoC'23 contributor
- [x] I want to work on this issue

Please assign me this issue under GSSoC'23
Thanks

**Comment by anmode** [comment]
please check the development version, not the production one

**Comment by anmode** [comment]
@harmeetsingh11 actually it is not needed... could you seperate grabtern community to different page??

**Comment by harmeetsingh11** [comment]
Yes, I can do that.

**Comment by anmode** [comment]
cool
