### ISSUE TITLE
🚀 [Feature Request] - Footer in mentors

### ISSUE THREAD

**Issue by BhartiNagpure** [anmode/grabtern-frontend#544]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

In mentor page missing footer.
I would like to add footer.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. go to mentor page
2. add footer component
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by KartikAhluwalia** [comment]
Hi I would like to contribute on this feature. I am a GSSoC 2023 contributor. Kindly assign me this issue.

**Comment by KartikAhluwalia** [comment]
Hi can you assingn me this issue. Would love to work on this.

**Comment by anmode** [comment]
sorry, This will be infinite loading page... footer not required
