### ISSUE TITLE
🚀 [Feature Request] - Back to top 

### ISSUE THREAD

**Issue by BhartiNagpure** [anmode/grabtern-frontend#545]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

I would like to add back to top button in the website.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Go to website
2. Add back to top button where scroll is more 
3. give top path to button.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Abhinavcode13** [comment]
Already in progress #528 @BhartiNagpure
