### ISSUE TITLE
🚀 [Feature Request] - i want add a 3d illustration on home page so that it looks more attractive

### ISSUE THREAD

**Issue by anshulsoni4** [anmode/grabtern-frontend#553]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement
the current svg is not that good, i can modify that to 3d 

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. eliminate current image
2. search for liable 3d assets
3. replace
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
cool
