### ISSUE TITLE
🚀 [Feature Request] - github profile

### ISSUE THREAD

**Issue by BhartiNagpure** [anmode/grabtern-frontend#557]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

I would like to add github link to community profile.
When user click on profile photo it redirect to its github account.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Add github link 
2. write function for onclick
3. click profile it redirect github account
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
We have took that data.. actually this is not neccassary loook at this: https://github.com/anmode/grabtern-frontend/issues/566
