### ISSUE TITLE
🚀 [Feature Request] - Convert forgot pass page and reset password page into New theme

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#566]
### Is your feature request related to a problem ? Please describe. ✍️

see login page.. just have same theme

### Describe briefly how you would implement this enhancement.

```bash
See theme and use components
```

### Additional context or screenshots

please use our button component..

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by coder12git** [comment]
@anmode I want to work on this. Please assign me this issue!

**Comment by anmode** [comment]
assinged you!

**Comment by coder12git** [comment]
> assinged you!

Please add level labels
