### ISSUE TITLE
🚀 [Test Grabtern] - Create Test folder, and include Jest test for each component and files

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#572]
### Is your feature request related to a problem ? Please describe. ✍️

This Issue not assigned to one....many people can be assigned..
Just comment down by which file you will be convering your PR and create PR.. 
I will add levels to PR as level on PR is important for Gssoc.

### Describe briefly how you would implement this enhancement.

```bash
Just create Jest Test
```

### Additional context or screenshots

It would be good if first PR to this Issue also create a github CI test to run test files and check.

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Killer2OP** [comment]
@anmode I can make the jest-test files for UI components.

**Comment by anmode** [comment]
cool

**Comment by anmode** [comment]
@Killer2OP kaafi multiple PR bna skte ho.. and In my case all will be level 3 and level 2

**Comment by Killer2OP** [comment]
> @Killer2OP kaafi multiple PR bna skte ho.. and In my case all will be level 3 and level 2

OK :)

**Comment by coder12git** [comment]
@anmode I also want to work for UI-components.
Please assign me

**Comment by coder12git** [comment]
@anmode just want to let you know that I am working on the date and time component.
