### ISSUE TITLE
🚀 [Feature Request] Register Button Renaming

### ISSUE THREAD

**Issue by ShreyaDhiman24** [anmode/grabtern-frontend#577]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement
![image](https://github.com/anmode/grabtern-frontend/assets/98320971/d4cf6801-aacf-47c3-b6ed-82182652c90e)

I think this "Registration" should be just "Register".

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
okkk
