### ISSUE TITLE
[REVAMP]: LIST ITEMS DESIGN ON HOMEPAGE 🪄

### ISSUE THREAD

**Issue by 0xabdulkhalid** [anmode/grabtern-frontend#581]
## Description
- I would like to revamp the design of list items present on the Homepage of new Grabtern UI.
- The current design not looks good in terms of UI, i can revamp the design.
- I already made a sample revamp changes on browser itself to share the screenshots to you for your comparison.
- Make sure to properly review the below table, if this needs to be done then you can assign me to complete this work.

## Screenshots
<table border="1">
        <tr>
            <th>C U R R E N T &nbsp; S T A T E</th>
            <th>D E S I R E D &nbsp; S T A T E</th>
        </tr>
        <tr>
            <td>
                <table border="1">
                    <tr>
                        <th>MOBILE</th>
                        <th>DESKTOP</th>
                    </tr>
                    <tr>
                        <td>

![Screen Shot 2023-07-23 at 08 00 50](https://github.com/anmode/grabtern-frontend/assets/92252895/424b0bca-f98e-4829-9340-8cf3374ad470)

</td>
                        <td>

![Screenshot 2023-07-23 at 08-00-08 GrabTern Grab Your Internship](https://github.com/anmode/grabtern-frontend/assets/92252895/be541d05-ae9a-4ef2-82b7-ae8c0469f2a9)

</td>
                    </tr>
                </table>
            </td>
            <td>
                <table border="1">
                    <tr>
                        <th>MOBILE</th>
                        <th>DESKTOP</th>
                    </tr>
                    <tr>
                        <td>

![Screen Shot 2023-07-23 at 07 57 03](https://github.com/anmode/grabtern-frontend/assets/92252895/ef017288-d573-4c98-9504-0395f9b335cd)

</td>
                        <td>

![Screenshot 2023-07-23 at 07-51-24 GrabTern Grab Your Internship](https://github.com/anmode/grabtern-frontend/assets/92252895/8eb73155-e7d9-4210-8bf6-95e3663355d4)

</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

**Comment by 0xabdulkhalid** [comment]
Hey there @anmode 👋🏻

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by anmode** [comment]
yeah, some places it needs... ok go for it
