### ISSUE TITLE
🚀 [Feature Request] - Dockerizing the app

### ISSUE THREAD

**Issue by Viveksati5143** [anmode/grabtern-frontend#584]
### Is your feature request related to a problem ? Please describe. ✍️

Making it accessible for all by providing an Consistent & Isolated Environment .

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Create a Docker-compose file containing all the tech stacks used in it 
2. i.e. Mongodb, nextjs, nodejs
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Viveksati5143** [comment]
@anmode I would like to work in this issue as my first one in your repo. 
Thanks

**Comment by anmode** [comment]
Size max: 500mb
and image should be multi stage builded
