### ISSUE TITLE
Initialize Commit Lint in Project 🚀

### ISSUE THREAD

**Issue by Nishitbaria** [anmode/grabtern-frontend#599]
[Description]:
As part of our efforts to maintain code quality and enforce consistent commit messages, we will be integrating Commit Lint into our project's repository. Commit Lint helps us ensure that commits follow a specific format and adhere to a set of guidelines. This will make it easier for team members to understand the changes made in each commit and facilitate better collaboration.

[Steps]:
1. Install Commit Lint: We will add the necessary dependencies to the project's development environment to enable Commit Lint.

2. Configure Commit Lint Rules: We will define the commit message format and rules that contributors need to follow when making commits. This might include rules for commit message length, required fields (such as issue references), and commit type categories (e.g., feat, fix, chore, docs, etc.).

3. Pre-commit Hook: We will set up a pre-commit hook that will automatically check commit messages against the defined rules before allowing a commit to be made.

4. CI/CD Integration: We will integrate Commit Lint into our Continuous Integration/Continuous Deployment (CI/CD) pipeline to ensure that commits pushed to the repository comply with the defined guidelines.

5. Documentation: We will update the project's documentation to include information about Commit Lint, the commit message guidelines, and how contributors can adhere to the rules.

[Benefits]:
- Improved Code Readability: Consistent commit messages make it easier for team members to understand the purpose and scope of changes in each commit.
- Standardization: By enforcing commit guidelines, we can establish a consistent commit history, making it easier to navigate through the project's development timeline.
- Better Collaboration: Clear commit messages facilitate smoother collaboration among team members, especially when working on shared codebases.
- Automated Validation: With the pre-commit hook and CI/CD integration, we can automatically validate commit messages, reducing the chances of improper commits.

**Comment by anmode** [comment]
we have prettier...

**Comment by anmode** [comment]
the thing is left is pre commit hook
