### ISSUE TITLE
🚀 [Feature Request] - Add Changelog Workflow that generates a conventional changelog 🚀

### ISSUE THREAD

**Issue by Nishitbaria** [anmode/grabtern-frontend#600]
### Is your feature request related to a problem ? Please describe. ✍️

**Description:**

**Goal:** Add a new GitHub Actions workflow that generates a conventional changelog and creates a release when changes are pushed to the `main` branch.

### Describe briefly how you would implement this enhancement.

```bash
**Workflow:**


name: Changelog

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: "false"

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
```

### Additional context or screenshots

**Note:** This workflow utilizes the `TriPSs/conventional-changelog-action@v3` action to generate a conventional changelog based on the commit messages. It then uses the `actions/create-release@v1` action to create a release on GitHub if changes were made during the push to the `main` branch. The release name will be the same as the generated changelog's tag, and the changelog content will be used as the release body.

Before adding this workflow, ensure that you have the required permissions and secrets set up on your repository. Also, review and test the workflow in a safe environment before using it in your production environment.

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
cool!

**Comment by anmode** [comment]
@Nishitbaria ? what about this?

**Comment by Nishitbaria** [comment]
@anmode  I will Make PR now IF you are Ready to merge  it now
