### ISSUE TITLE
🐞 [BUG] - Newsletter Subscription Not Working and Integration with Hashnode Newsletter

### ISSUE THREAD

**Issue by Nishitbaria** [anmode/grabtern-frontend#601]
### Description

Currently, the newsletter subscription feature on our platform is not functioning as expected. Users are unable to subscribe to our newsletter, resulting in missed opportunities to engage with our audience and keep them informed about our latest updates, news, and content.

### Current behaviour

Currently, when users visit our website and attempt to subscribe to the newsletter, they encounter issues with the subscription process. The newsletter subscription feature seems to be malfunctioning, preventing users from successfully subscribing to our mailing list.On clicking subscribe button ,it redirects to homepage

### Expected behaviour

When users visit our website, they should be able to easily subscribe to our newsletter by providing their email address and receiving a confirmation email. Once subscribed, they should receive periodic newsletters with updates and relevant content.

### Reproduction steps

```bash
Steps to Reproduce:
1. Go to the website's homepage.
2. Look for the newsletter subscription section or form.
3. Enter your email address and attempt to subscribe.
```

### Screenshots

![DESCRIPTION](LINK.png)

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Nishitbaria** [comment]
@anmode ,please assign me this issue

**Comment by anmode** [comment]
sure

**Comment by anmode** [comment]
Whenenver new mentor register... I think it is good to tell all users.. via a email

**Comment by Nishitbaria** [comment]
@anmode ,I can   only save the subscriber in  database,send them wecome email on subscribing,send email to owner of newsletter and most important "I can link your newsletter with your hashnode newsletter  means subscriber subscring here will recieve all updates on your hashnode domain "

**Comment by anmode** [comment]
@Nishitbaria done here is the username: grabtern.hashnode.dev

**Comment by anmode** [comment]
1. We can send updated on new mentor registration.
2. Any internship comes so this news letter should send email to user that we have mentors
3. Any upfated in grabtern it should send email to mentors

is this possible through hashnode?

**Comment by Nishitbaria** [comment]
@anmode , My task will be that i will be connecting your website newsletter subscribers to  your hashnodenewsletter  for example:if they submit email in newsletter they will get confirmation email from hashnode ,if they confirm they will be subscribed to your hashnode newsletter .Now you can use all functionalites of hashnode newsletter  like sending email to all subscriber on publishing  a new article  to your website subscribers.

**Comment by anmode** [comment]
cool@

**Comment by Nishitbaria** [comment]
@anmode ,i want to add a controller for making post request to hashnode where i can add it?
