### ISSUE TITLE
🚀 [Feature Request] - Testimonial section for ``/mentor`` page

### ISSUE THREAD

**Issue by rishuraj1** [anmode/grabtern-frontend#604]
### Is your feature request related to a problem ? Please describe. ✍️

We might want to add a testimonial section in the /mentor page to attract more mentors and provide some insights.

Please assign this task to me under GSSoC '23. Thank You!

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Create a testimonial component 
2. include it in mentor page
```

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
cool!!
