### ISSUE TITLE
🚀 Add mongoose properties to the mentor profile page.

### ISSUE THREAD

**Issue by Pragati-3003** [anmode/grabtern-frontend#606]
### Is your feature request related to a problem ? Please describe. ✍️

Add the properties to the mentor profile page.
Related to issue#532

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Rest functionality no worries I'll see you did great work

**Comment by Pragati-3003** [comment]
> Rest functionality no worries I'll see you did great work

OKIE.
