### ISSUE TITLE
🚀 [Feature Request] - Improve Sidebar

### ISSUE THREAD

**Issue by rishuraj1** [anmode/grabtern-frontend#621]
### Is your feature request related to a problem ? Please describe. ✍️

Sidebar is not properly working and needs to be fixed.

My idea is to make width of the sidebar small enough only to show the icons of profile, home etc.
Upon hover over the sidebar, it will fully expand to show the name etc.

This will also fix the bug associated to it in the desktop mode to ellapse and close it.

Please assign this task to me under GSSoC '23. Thank You!

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

current:
![image](https://github.com/anmode/grabtern-frontend/assets/47839626/3f30d803-3ab9-41c3-a568-40168b71096f)

proposed idea:
![image](https://github.com/anmode/grabtern-frontend/assets/47839626/ea4c97c8-7a09-4c71-9ca2-29a835190643)

on hover:
![image](https://github.com/anmode/grabtern-frontend/assets/47839626/b9eb34d2-45e8-46f6-8d46-534f571c2d0e)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Yes, please try to design according to OUR ui...
You know well :)

**Comment by anmode** [comment]
One more thing.. need mobile optimization:
![d665f2b1-2c2a-4153-b32c-5ae9a8d27c2c](https://github.com/anmode/grabtern-frontend/assets/88332977/0ab702d1-b9bb-4ac4-84f3-ad985ea66d49)
