### ISSUE TITLE
🚀 [Feature Request] - Mentor Booking Session Frontend

### ISSUE THREAD

**Issue by MAXASSASSINS** [anmode/grabtern-frontend#622]
### Is your feature request related to a problem ? Please describe. ✍️

Currently profile page contains a lot of redundant HTML and inline styles too.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Make a list of inputs.
2. Update styles with tailwind classes
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by MAXASSASSINS** [comment]
Hey @anmode please assign this issue to me

**Comment by anmode** [comment]
Could you please work on booking page?? Instead of profile

**Comment by MAXASSASSINS** [comment]
> Could you please work on booking page?? Instead of profile

@anmode can I work on both issues side by side? I will make a PR for this issue by today itself.

**Comment by anmode** [comment]
> > Could you please work on booking page?? Instead of profile
> 
> @anmode can I work on both issues side by side? I will make a PR for this issue by today itself.

Actually on profile section on Team mate is working that's why... I created more issues you can take them all if you want. All are level 3

**Comment by anmode** [comment]
Booking page... should be like... let me show you: This is perpective from user but you have to design for mentor.
<img width="1280" alt="Screenshot 2023-07-29 at 10 28 09 AM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/a6b826c0-2bcf-485f-befb-f7ed36d67b2d">

**Comment by MAXASSASSINS** [comment]
> Actually on profile section a Team mate is working that's why... I created more issues you can take them all if you want. All are level 3

Sure, let's start with this.

**Comment by MAXASSASSINS** [comment]
> Booking page... should be like... let me show you: This is perpective from user but you have to design for mentor. <img alt="Screenshot 2023-07-29 at 10 28 09 AM" width="1280" src="https://user-images.githubusercontent.com/88332977/256964511-a6b826c0-2bcf-485f-befb-f7ed36d67b2d.png">

@anmode  do we require all these fields on our page?
Like date and time can be clubbed together same goes for amount and rate as well.
And what about the statuses of the sessions? The screenshot is having 4. Do we need all 4?

**Comment by anmode** [comment]
> > Booking page... should be like... let me show you: This is perpective from user but you have to design for mentor. <img alt="Screenshot 2023-07-29 at 10 28 09 AM" width="1280" src="https://user-images.githubusercontent.com/88332977/256964511-a6b826c0-2bcf-485f-befb-f7ed36d67b2d.png">
> 
> @anmode  do we require all these fields on our page?
> Like date and time can be clubbed together same goes for amount and rate as well.
> And what about the statuses of the sessions? The screenshot is having 4. Do we need all 4?
> 

Sorry for late reply...
The thing you have to show to mentor 

The user name , date and time , and which session..nd at backend we have flag which is `isbooked`..
So the value of this decided it should be in pending state or completed

**Comment by anmode** [comment]
> > Booking page... should be like... let me show you: This is perpective from user but you have to design for mentor. <img alt="Screenshot 2023-07-29 at 10 28 09 AM" width="1280" src="https://user-images.githubusercontent.com/88332977/256964511-a6b826c0-2bcf-485f-befb-f7ed36d67b2d.png">
> 
> @anmode  do we require all these fields on our page?
> Like date and time can be clubbed together same goes for amount and rate as well.
> And what about the statuses of the sessions? The screenshot is having 4. Do we need all 4?
> 

Sorry for late reply...
The thing you have to show to mentor 

The user name , date and time , and which session..nd at backend we have flag which is `isbooked`..
So the value of this decided it should be in pending state or completed

**Comment by anmode** [comment]
If any further questions or need more detailing please contact me on discord...will meet
