### ISSUE TITLE
🚀 [Feature Request] - Design Mentor Home Page

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#624]
### Is your feature request related to a problem ? Please describe. ✍️

You just focus on UI, data will comes from backend.... for now dev purpose you can take dummy data.

From api you will get all data which is possible of mentor.

### Describe briefly how you would implement this enhancement.

```bash
1. Design in our UI do not exact copy Topmate..
```

### Additional context or screenshots

<img width="1270" alt="Screenshot 2023-07-29 at 10 21 59 AM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/91ff1fe7-6076-4cee-9dd4-f764dcac3fae">

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Vidip-Ghosh** [comment]
Can I work on this issue?

**Comment by anmode** [comment]
sure..

**Comment by Vidip-Ghosh** [comment]
@anmode  Can you please share the color scheme of this page?

**Comment by Vidip-Ghosh** [comment]
https://github.com/anmode/grabtern-frontend/assets/91741581/ced7279b-e209-459e-8a95-9398ba0b237b

Also, will this type of sidebar be alright for mentors page?
