### ISSUE TITLE
🚀 [Feature Request] - Enhancing Profile Sharing with Social Media Links

### ISSUE THREAD

**Issue by Akanksha-202** [anmode/grabtern-frontend#629]
### Is your feature request related to a problem ? Please describe. ✍️

Allowing users to share profiles through various social media platforms like Facebook, Twitter, WhatsApp, LinkedIn, etc. in addition to the existing option of copying the profile link to the clipboard.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Update Share Component
2. Using Facebook and Twitter share APIs, "whatsapp://send" link for WhatsApp, and LinkedIn share API.
3. Styling and Layout
```

### Additional context or screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/100708686/cc5cb83e-773f-44fe-9c67-013a554f3c3e)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Akanksha-202** [comment]
hey @anmode, i tried setting up the repo on my local server but I'm not getting any mentors in the mentors section:
![image](https://github.com/anmode/grabtern-frontend/assets/100708686/25181cde-0e9c-4789-b280-cfde52d28350)

I checked that 
![Screenshot 2023-07-30 200033](https://github.com/anmode/grabtern-frontend/assets/100708686/220f65ae-28b7-4b54-9218-26135c52c8c3)
No content is there in the directed path
![image](https://github.com/anmode/grabtern-frontend/assets/100708686/65eaecbd-628e-4c4e-b094-a46b96cd4b55)


Am I missing any step, can you please tell.

**Comment by anmode** [comment]
Oh it's my fault.. give me time I will recreate demo data

**Comment by anmode** [comment]
Ah, could you try to create a mentor? a demo mentor:

1. Register as mentor and fill all details:
2. Email will be recieve and you have to verify: check the inbox credentials from readme.
3. After verfication card will be shown in mentor page.


let me know when you done with this!

**Comment by Akanksha-202** [comment]
ok so, before creating a demo mentor, i had to sign in, and that is also not happening, neither through form nor through google authentication.
![image](https://github.com/anmode/grabtern-frontend/assets/100708686/7d40e547-6609-4139-acf3-c4fcdc7d963e)

Console window:
![image](https://github.com/anmode/grabtern-frontend/assets/100708686/b53bd8c3-777b-4cc5-8a4e-cd8e8fb9ee06)

**Comment by Akanksha-202** [comment]
It is asking to sign up first and I'm filling in details but signup is not taking place.
I'm getting a toast message which I sent in the last comment.

**Comment by Akanksha-202** [comment]
Any updates??

**Comment by anmode** [comment]
oh ok! Let me check the demo version! just give me 1 hour

**Comment by anmode** [comment]
Done I fixed!

**Comment by Akanksha-202** [comment]
Yes! Will update about PRs soon :)
