### ISSUE TITLE
🐞 [BUG] - User & Mentor login api getting called without any input value

### ISSUE THREAD

**Issue by 777Prabhjot** [anmode/grabtern-frontend#638]
### Description

Login api getting called for both Mentor and User section even if the fields are empty.

### Current behaviour

Email & Password fields are empty but api is getting called for both Mentor & User login section.

### Expected behaviour

Validation should be implemented to prevent api call for empty data submission for both sections. so that unnecessary api calls not got executed.

### Reproduction steps

```bash
1. Go to 'SignIn page'
2. Click on 'Login button without providing any input value'
3. Check the network tab api is getting called
```

### Screenshots

https://github.com/anmode/grabtern-frontend/assets/68184118/0e598c9f-35ab-43e1-b22e-fac8b160b65a

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Thanks! See other places too...and fix

**Comment by 777Prabhjot** [comment]
@anmode sure
