### ISSUE TITLE
Lets Animate The Project 

### ISSUE THREAD

**Issue by Souravvmishra** [anmode/grabtern-frontend#639]
### Is your feature request related to a problem ? Please describe. ✍️

Let me describe how can adding Animations to the site will improve the overall quality : 

- Animation can **attract and retain** the attention of your visitors, making them more likely to explore your site and learn about your products or services¹².
- Animation can **enhance your brand identity** and create a memorable impression on your audience. 
- Animation can **increase user engagement** and interaction. 
- Animation can **improve user experience** and navigation. 
- Animation can **boost conversion rates** and sales. 
- Animation can **increase social media shares** and viral potential. 
- Animation can **educate and inform** your audience. 
- Animation can **entertain and delight** your audience. 
- Animation can **set you apart from the competition** and make you stand out. 

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-

Use the framer-motion to add animations
```

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Animation slows down too! by using library build size too increases.
Ok if you can give at which place you will apply animation and what... please create PR directly no worries
