### ISSUE TITLE
Is the 'top' span required? 

### ISSUE THREAD

**Issue by Souravvmishra** [anmode/grabtern-frontend#640]
![Screenshot_2023-07-31-10-03-41-358-edit_com.android.chrome.jpg](https://github.com/anmode/grabtern-frontend/assets/89072785/2c9986d4-70ef-4589-b1a3-b1b9163a0a8c)

Do we really need to tell user that this button will take you to the top of the screen?

**Comment by anmode** [comment]
remove it! please
