### ISSUE TITLE
🚀 [Feature Request] - design a home page for ``dashboard/mentor/``

### ISSUE THREAD

**Issue by rishuraj1** [anmode/grabtern-frontend#646]
### Is your feature request related to a problem ? Please describe. ✍️

There is a scope to improve the ``dashboard/mentor/profile`` page as it is not responsive and simple at this moment.

Idea:
- we can make the page more interactive and appealing by adding apt. icons and colors from the pallete of the overall webapp.\
- will try to add additional functionalities too.
- making it responsive will be my secondary task.

Please assign this task to me under GSSoC '23.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/47839626/337d3e76-aaa1-4338-aa22-340ee78ea658)

![image](https://github.com/anmode/grabtern-frontend/assets/47839626/5ec3f5be-4847-4971-9166-cf91dcfea95f)

@anmode 

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
One contributor is working... on this pR.. please could you take another issue of mentor Dashboard

**Comment by anmode** [comment]
No no please wait

**Comment by anmode** [comment]
Ok can you design a Home page? 
A simple home page , Saying Hi, and displaying all things

**Comment by rishuraj1** [comment]
Alright @anmode thanks for the opportunity, can I get a reference or an image for an heads up. I'll start by editing the title for this issue. 😅

**Comment by anmode** [comment]
There are some homepgaes::
Ab exact copy ni kr skte.. but yess kch basic s would be fine.. :). 

<img width="1277" alt="Screenshot 2023-08-01 at 3 15 51 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/83bf9f13-9c74-4127-8479-faf4a78eed70">
<img width="1278" alt="Screenshot 2023-08-01 at 3 16 22 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/93178639-7a3d-487a-84a1-588dc843f393">

**Comment by anmode** [comment]
Cool

**Comment by rishuraj1** [comment]
@anmode  just one question,
am I supposed to redesign this home page ``dashboard/mentor/sessions`` or create a new page.
<img width="960" alt="image" src="https://github.com/anmode/grabtern-frontend/assets/47839626/a1940c35-0491-4c72-9a25-5468fcd3f02b">

**Comment by anmode** [comment]
actually this is session page.. you can remove or put that code in differnet file..

**Comment by rishuraj1** [comment]
@anmode  I am working on overall structure of the page and figuring out what functionalities to show......going good, I will ask when help is needed. Thanks

**Comment by anmode** [comment]
Wow.. sounds good!
