### ISSUE TITLE
🚀 [Feature Request] - Create Grabtern a PWA ( progressive web app)

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#648]
### Is your feature request related to a problem ? Please describe. ✍️

Create grabtern a progressive web app;

### Describe briefly how you would implement this enhancement.

```bash
Null
```

### Additional context or screenshots

<img width="87" alt="Screenshot 2023-08-01 at 3 19 08 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/6a68983d-7555-465b-be56-ef9a94bac146">

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by SubhamB2003** [comment]
@anmode Can I try ? 
And one thing in offline mode is if I use an illustration that says to go to online mode to view the site. Is it ok??

**Comment by anmode** [comment]
Sure

**Comment by SubhamB2003** [comment]
@anmode Hey is it ok?
Can I create the PR?

https://github.com/anmode/grabtern-frontend/assets/94003231/f0a53200-16df-4b11-93e7-b3b64092c072
