### ISSUE TITLE
🚀 [Feature Request] - make social anchors accessible ✨ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [anmode/grabtern-frontend#663]
### Is your feature request related to a problem ? Please describe. ✍️

This feature is related to the problems faced by peoples who have some sort of disabilities.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. add proper aria-label for all social anchors to make them announced by screen readers
2. add title for them to announce that the link will navigate to another external source
3. adding proper referrer relations with rel attribute
```

### Additional context or screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/92252895/437274b9-f2a0-4ab9-ae21-24c9c82088c7)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
> Hey there @anmode 👋🏻
> 
> Please make sure to assign this issue to me to make the work done, Thank you!

is this any action of your account?? or you write this comment :)

**Comment by 0xabdulkhalid** [comment]
@anmode nope 😆 

I think if it was a feature like workflows, i can create like this one for me to comment on all issues.
