### ISSUE TITLE
🚀 [Feature Request] - Add Github Contributor into grabtern Community section

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#670]
### Is your feature request related to a problem ? Please describe. ✍️

To give credits to you! We decide to took this step

### Describe briefly how you would implement this enhancement.

```bash
Just fetch all contributors from github
```

### Additional context or screenshots

Null

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by parasss19** [comment]
Hey @anmode  I want to work on this issue

**Comment by anmode** [comment]
sure
