### ISSUE TITLE
🚀 [Feature Request] - Animation on hover

### ISSUE THREAD

**Issue by parasss19** [anmode/grabtern-frontend#672]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement
- Right now the find mentor page cards have no hover effect
- I will add hover animation on images of mentor which looks good with the UI of the website

## Sample 
https://github.com/Opentek-Org/opentek/assets/101205226/c4727de5-5afb-4a86-ad74-aba1cbc66bc9

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. I will apply proper css to apply hover animation effect on mentor cards
```

### Additional context or screenshots

NA

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by parasss19** [comment]
Hey @anmode Please review it

**Comment by anmode** [comment]
thanks but  we do not need feature
