### ISSUE TITLE
🐞 [BUG] - During  Registration, the eye button in the "Password" section reveals the password in the "Confirm Password" but vice-versa does not work

### ISSUE THREAD

**Issue by Sch476** [anmode/grabtern-frontend#681]
### Description

On filling both "Password" and "Confirm Password" section and clicking on the eye button of "Password" section, both the entered fields are displayed. Whereas on clicking on the eye button of "Confirm Password" section, no password is revealed.

### Current behaviour

On clicking on the eye button of "Password" section, both the entered fields are displayed. Whereas on clicking on the eye button of "Confirm Password" section, no password is revealed.

### Expected behaviour

On clicking on the eye button of "Password" section, only the password entered by the user under the "Password" section , should be visible and the password entered by the user under the "Confirm Password" section , should not be visible. On clicking on the eye button of "Confirm Password" section, the password entered by the user under the "Confirm Password" section should be revealed.

### Reproduction steps

```bash
1. Go to 'https://www.grabtern.com/'
2. Click on 'Sign Up'
3. Fill both the Password fields 
4. Click on the eye button under "Password" section
5. Click on the eye button under "Confirm Password" section
4. See error
```

### Screenshots

https://github.com/anmode/grabtern-frontend/assets/127319225/01f7b600-cd93-4df6-988d-8bc5ceebe5cb

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
is this on develop branch? or production ( www.grabtern.com)

**Comment by Sch476** [comment]
Production

**Comment by anmode** [comment]
please see develop branch! is it there or not

**Comment by Sch476** [comment]
@anmode Checked the develop branch, no error is happening when the eye button under the "Password" section is clicked and only the password under the respective section is shown. But when the eye button in "Confirm Password" is clicked, an error happens . 


I am attaching a video . Please check it and assign me this issue.

**Comment by anmode** [comment]
cool fix it please
