### ISSUE TITLE
🚀 [Feature Request] - Create Coming Soon Page for mentor Dashboard

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#696]
### Is your feature request related to a problem ? Please describe. ✍️

Some feature are yet to made so in place of it we will have coming soon page.

### Describe briefly how you would implement this enhancement.

```bash
null
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by rishuraj1** [comment]
@anmode assign this to me please.
