### ISSUE TITLE
🚀 [Feature Request] - Testimonial Section Content Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [anmode/grabtern-frontend#717]
### Is your feature request related to a problem ? Please describe. ✍️

No. It's an enhancement in the existing design. The updated change will bring:
_**The content of this section from left-centered to center-aligned in order to enhance text importance and increase user focus.**_

### Describe briefly how you would implement this enhancement.

```bash
Working on the styling of the content of this section to improve the design.
```

### Additional context or screenshots

_Current Design_

![i (3)](https://github.com/anmode/grabtern-frontend/assets/115794049/3b4064d9-7d21-4bff-b446-05e6e6355e69)

_Expected Updated Design_

![i (4)](https://github.com/anmode/grabtern-frontend/assets/115794049/bb9c17ac-0d07-48e5-998c-7008a01e04eb)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
it is good! Here we not need improvment. thanks
