### ISSUE TITLE
🚀 [Feature Request] - 'Sign Up' Form Input Area Improved Styling

### ISSUE THREAD

**Issue by iamRabia-N** [anmode/grabtern-frontend#718]
### Is your feature request related to a problem ? Please describe. ✍️

No. It's an enhancement in the existing design. The current design of the form is nice but it can be improved by making some design adjustments in the styling of the form. By such adjustments, I can improve the design of the form especially the input area of the form.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Removing unwanted styling or adjusting them i.e. the dark border on the bottom is creating sharp design which creating negative intense impact on the overall design of the form.
2. Making the styling of the input areas of the form more smooth and minimal yet elegant.
3. Choosing the color scheme that goes with the theme of the form and overall website.
```

### Additional context or screenshots

_Current Design_

![i (5)](https://github.com/anmode/grabtern-frontend/assets/115794049/d8877cc4-19a9-4402-8696-d8b1c39f1098)

_Expected Updated Design_

![i](https://github.com/anmode/grabtern-frontend/assets/115794049/58c8d9ba-9545-465a-a9ae-847bbc30a188)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by iamRabia-N** [comment]
Hi @anmode 
Kindly assign me this issue.

**Comment by anmode** [comment]
mobiile mode k bhi kyhal rkhna please... assigned
