### ISSUE TITLE
Create Login Card.

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#75]
1.  Create card, We have component but i think it is not used!  (https://github.com/anmode/grabtern-frontend/blob/develop/components/LoginDropdown.js)
<img width="436" alt="Screenshot 2023-04-14 at 6 30 21 AM" src="https://user-images.githubusercontent.com/88332977/231914521-6deede1d-eca0-44ec-9622-07675cad8240.png">

https://github.com/anmode/grabtern-frontend/blob/5a753b4f85c0c7a7f5254e8ebdeec6ff31e17ed0/components/Header.js#L138 
@Sayyidalijufri Do you wanna give a try?

cc @sayyedarib @muhammadjufry

**Comment by Swetha-Baskaran** [comment]
@anmode I wish to try this. Assign this to me with the label GSSOC'23

**Comment by anmode** [comment]
@Swetha-Baskaran ? r u up for it?

**Comment by Swetha-Baskaran** [comment]
Yeah I can do this

**Comment by anmode** [comment]
Go ahead please

**Comment by anmode** [comment]
could you please choose one issue #75 or #43?

**Comment by Swetha-Baskaran** [comment]
I can take 48

**Comment by anmode** [comment]
okk

**Comment by crocmons** [comment]
I want to work on this

**Comment by crocmons** [comment]
> @crocmons what's the update?

I'm not started yet.. do you want to work this issue?

**Comment by AmanJain18** [comment]
It occurs due to errors, Don't worry i will add labels properly to all pr and issues when i get time.
