### ISSUE TITLE
add discord link and check other link

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#90]
<img width="382" alt="Screenshot 2023-04-20 at 8 52 45 AM" src="https://user-images.githubusercontent.com/88332977/233250287-24b45247-1a9e-4aff-ba93-b2242536ddb2.png">

**Comment by ritik48** [comment]
@anmode Please assign this to me under GSSoC'23

**Comment by mfatima05** [comment]
@anmode Kindly assign this to me under GSSoC'23

**Comment by anmode** [comment]
@ritik48 you have other issue assigned please complete them first!

**Comment by ePSA-eJya** [comment]
please assign this issue to me @anmode . i am a gssoc 23 contributor

**Comment by mfatima05** [comment]
@anmode in which file the code for adding discord link and check other link is present?

**Comment by anmode** [comment]
@mfatima05 it has been solved  by @ePSA-eJya please could you look at other issues.
