### ISSUE TITLE
Add the management team and left team pic.

### ISSUE THREAD

**Issue by anmode** [anmode/grabtern-frontend#91]
<img width="957" alt="Screenshot 2023-04-20 at 8 59 13 AM" src="https://user-images.githubusercontent.com/88332977/233251117-fb3efc78-2c36-466d-a3e5-76da684b52a0.png">

**Comment by Isha988** [comment]
@anmode I want to work on this issue under gssoc program. Would you please assign it to me.
And please also provide the link of the page on which the carousel have to be moved

**Comment by anmode** [comment]
Actually this can't gssoc an issue! Sorry!. Look out other

**Comment by Swapnalighadge** [comment]
i would like to work on this issue under SSOC.
